#!/usr/bin/env node
/**
 * test/agent/assemble.mjs
 *
 * For every benchmark fixture, concatenate its prompt layers in init order
 * (Layer 1 CORE → Layer 2 language → Layer 2 framework) into a single system
 * prompt, emit the archetype task sheet, and write an executable launcher so a
 * sub-agent can drive the real tools with one command.
 *
 *   built/<fixture>.prompt.md   the assembled system prompt under test
 *   built/<fixture>.tasks.md    the 4 archetype tasks for this fixture
 *   built/<fixture>             launcher (sets fixture, trace, retrieval mode)
 *
 * Launcher retrieval mode:  AGENT_MODE=semantic (default, Ollama 11434) | lexical (BM25 only).
 * Per-call archetype tag:   AGENT_TASK=symbol|behaviour|keyword|crosscut (recorded in trace).
 *
 * Usage: node test/agent/assemble.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { BENCHMARKS } from './benchmark.config.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '../..');
const PROMPTS = path.join(REPO, 'prompts');
const BUILT = path.join(HERE, 'built');
const TRACES = path.join(HERE, 'traces');
const SEMANTIC_HOST = process.env.OLLAMA_SEMANTIC_HOST || 'http://localhost:11434';

fs.mkdirSync(BUILT, { recursive: true });
fs.mkdirSync(TRACES, { recursive: true });

for (const b of BENCHMARKS) {
    const body = b.layers
        .map(rel => fs.readFileSync(path.join(PROMPTS, rel), 'utf-8').trimEnd())
        .join('\n\n');
    fs.writeFileSync(path.join(BUILT, `${b.fixture}.prompt.md`), body + '\n');

    const taskSheet = Object.entries(b.tasks).map(([kind, t]) =>
        `## Task: ${kind}\n${t.prompt}\n`).join('\n');
    fs.writeFileSync(path.join(BUILT, `${b.fixture}.tasks.md`), taskSheet);

    const launcher = `#!/usr/bin/env bash
# Auto-generated by assemble.mjs — drives the real graph-indexer tools for "${b.fixture}".
export AGENT_FIXTURE="${b.fixture}"
if [ "\${AGENT_MODE:-semantic}" = "lexical" ]; then
  export OLLAMA_HOST="http://127.0.0.1:1"          # dead host → query embedding fails → BM25 only
else
  export OLLAMA_HOST="\${OLLAMA_HOST:-${SEMANTIC_HOST}}"
fi
export AGENT_TRACE="\${AGENT_TRACE:-${path.join(TRACES, b.fixture + '.jsonl')}}"
exec node "${path.join(HERE, 'agent-cli.mjs')}" "$@"
`;
    const launcherPath = path.join(BUILT, b.fixture);
    fs.writeFileSync(launcherPath, launcher);
    fs.chmodSync(launcherPath, 0o755);

    const tokens = Math.ceil(body.length / 4);
    console.log(`${b.fixture.padEnd(12)} layers=${b.layers.length}  prompt≈${tokens} tok  tasks=${Object.keys(b.tasks).length}`);
}

console.log(`\nWrote prompts + task sheets + launchers to ${path.relative(REPO, BUILT)}/`);
