/**
 * test/suites/axios.mjs
 *
 * Ground-truth query set for Axios v1.6.0 (JavaScript).
 * Source: https://github.com/axios/axios (tag v1.6.0)
 *
 * Query categories:
 *   easy   — exact symbol name as query; lexical TF-IDF should score it #1
 *   medium — partial name or related technical terms
 *   hard   — semantic / conceptual description only, no symbol name in query
 *
 * expected_names: the chunk's `name` field must contain one of these (substring match)
 * expected_files: the chunk's `file_path` must contain one of these (substring match)
 * Either condition passing counts as a hit.
 */

export const META = {
    id: 'axios',
    displayName: 'Axios v1.6.0',
    language: 'JavaScript',
    version: 'v1.6.0',
    url: 'https://github.com/axios/axios',
    expectedMinChunks: 80,
    expectedMinFiles: 30,
};

export const QUERIES = [
    // ── EASY — exact class / function name ────────────────────────────────────

    {
        id: 'AX01',
        query: 'InterceptorManager',
        difficulty: 'easy',
        topK: 5,
        description: 'Axios interceptor manager class (request/response interceptors)',
        expected_names: ['InterceptorManager'],
        expected_files: ['InterceptorManager'],
    },
    {
        id: 'AX02',
        query: 'CancelToken',
        difficulty: 'easy',
        topK: 5,
        description: 'Cancel token class for aborting in-flight requests',
        expected_names: ['CancelToken'],
        expected_files: ['CancelToken'],
    },
    {
        id: 'AX03',
        query: 'dispatchRequest',
        difficulty: 'easy',
        topK: 5,
        description: 'Core function that dispatches an HTTP request via the adapter',
        expected_names: ['dispatchRequest'],
        expected_files: ['dispatchRequest'],
    },
    {
        id: 'AX04',
        query: 'mergeConfig',
        difficulty: 'easy',
        topK: 5,
        description: 'Merge two Axios config objects (defaults + request config)',
        expected_names: ['mergeConfig'],
        expected_files: ['mergeConfig'],
    },
    {
        id: 'AX05',
        query: 'CanceledError',
        difficulty: 'easy',
        topK: 5,
        description: 'Error subclass thrown when a request is cancelled',
        expected_names: ['CanceledError'],
        expected_files: ['CanceledError'],
    },

    // ── MEDIUM — partial name, related terms, or multi-token ─────────────────

    {
        id: 'AX06',
        query: 'createInstance axios defaults',
        difficulty: 'medium',
        topK: 5,
        description: 'Factory that creates an Axios instance bound to default config',
        expected_names: ['createInstance'],
        expected_files: ['lib/axios'],
    },
    {
        id: 'AX07',
        query: 'settle promise resolve reject response',
        difficulty: 'medium',
        topK: 5,
        description: 'Helper that resolves or rejects the promise based on response status',
        expected_names: ['settle'],
        expected_files: ['settle'],
    },
    {
        id: 'AX08',
        query: 'buildURL params serializer',
        difficulty: 'medium',
        topK: 5,
        description: 'Builds the full URL string by appending serialised query params',
        expected_names: ['buildURL'],
        expected_files: ['buildURL'],
    },
    {
        id: 'AX09',
        query: 'http adapter node request',
        difficulty: 'medium',
        topK: 5,
        description: 'Node.js HTTP adapter that makes the actual http.request() call',
        // CORRECTION: axios indexes http.js's default export (the httpAdapter fn) as
        // `http_export_statement`; its internals (setProxy/dispatchBeforeRedirect) are
        // the named chunks. `httpAdapter` is not an indexed name (verified unresolvable).
        expected_names: ['http_export_statement', 'setProxy', 'dispatchBeforeRedirect'],
        expected_files: ['adapters/http'],
    },
    {
        id: 'AX10',
        query: 'xhr adapter XMLHttpRequest browser',
        difficulty: 'medium',
        topK: 5,
        description: 'Browser XHR adapter wrapping XMLHttpRequest',
        // CORRECTION: xhr.js's default export is an anonymous function → indexed as
        // `xhr_export_statement`; `xhrAdapter` is not an indexed name (verified).
        expected_names: ['xhr_export_statement', 'progressEventReducer'],
        expected_files: ['adapters/xhr'],
    },

    // ── HARD — semantic / conceptual descriptions only ────────────────────────

    {
        id: 'AX11',
        query: 'transform response data pipeline',
        difficulty: 'hard',
        topK: 10,
        description: 'Data transformation applied to request/response (maps transformData)',
        expected_names: ['transformData', 'transformResponse', 'transformRequest'],
        expected_files: ['transformData', 'defaults'],
    },
    {
        id: 'AX12',
        query: 'cancel ongoing request abort controller',
        difficulty: 'hard',
        topK: 10,
        description: 'Mechanism to cancel an in-flight request (CancelToken or AbortController)',
        expected_names: ['CancelToken', 'isCancel', 'CanceledError'],
        expected_files: ['cancel/'],
    },
    {
        id: 'AX13',
        query: 'combine base url with relative path',
        difficulty: 'hard',
        topK: 10,
        description: 'Utility that joins a baseURL with a relative requestedURL',
        expected_names: ['combineURLs', 'buildFullPath'],
        expected_files: ['buildFullPath', 'combineURLs'],
    },
    {
        id: 'AX14',
        query: 'interceptor chain promise pipeline',
        difficulty: 'hard',
        topK: 10,
        description: 'The request promise chain that threads interceptors together',
        expected_names: ['Axios', 'request'],
        expected_files: ['core/Axios'],
    },
    {
        id: 'AX15',
        query: 'Intercepting and modifying HTTP requests globally before they leave the browser to add authentication headers',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for the interceptor manager without using the class name',
        expected_names: ['InterceptorManager', 'request'],
        expected_files: ['InterceptorManager', 'core/Axios'],
    },
    {
        id: 'AX16',
        query: 'Stopping an HTTP network call that takes too long or is no longer needed by the user UI',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent describing request cancellation behavior',
        expected_names: ['CancelToken', 'CanceledError', 'isCancel'],
        expected_files: ['cancel/CancelToken', 'cancel/isCancel'],
    },
    {
        id: 'AX17',
        query: 'Converting raw JSON strings from the server into JavaScript objects automatically upon receiving a 200 OK',
        difficulty: 'semantic',
        topK: 10,
        description: 'Conceptual search for default response data transformation',
        expected_names: ['transformData', 'transformResponse', 'defaults'],
        expected_files: ['transformData', 'defaults'],
    },
    {
        id: 'AX18',
        query: 'The low-level layer that actually makes the network call using browser built-in APIs',
        difficulty: 'semantic',
        topK: 10,
        description: 'Searching for the browser XHR adapter conceptually',
        // CORRECTION: see AX10 — xhr default export is anonymous (`xhr_export_statement`).
        expected_names: ['xhr_export_statement', 'progressEventReducer'],
        expected_files: ['adapters/xhr'],
    },
    {
        id: 'AX19',
        query: 'Combining default global configuration with user-provided settings for a specific API call',
        difficulty: 'semantic',
        topK: 10,
        description: 'Locating the config merging logic',
        expected_names: ['mergeConfig'],
        expected_files: ['core/mergeConfig'],
    },

    // ── HELD-OUT (validation only — authored fresh, NEVER used to tune ranking;
    //    evaluate.mjs reports these separately so learned/changed ranking can be
    //    validated on data it did not see). Targets verified to exist in the index. ──
    { id: 'HO-AX1', query: 'buildFullPath', difficulty: 'easy', expected_names: ['buildFullPath'], heldOut: true },
    { id: 'HO-AX2', query: 'combine a base URL with a relative path into one absolute request URL', difficulty: 'semantic', topK: 10, expected_names: ['buildFullPath'], heldOut: true },
    { id: 'HO-AX3', query: 'AxiosHeaders normalize set get header value', difficulty: 'medium', expected_names: ['AxiosHeaders'], heldOut: true },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "AX20",
        query: "AxiosError",
        difficulty: "easy",
        topK: 5,
        description: "Custom error class carrying request config, request, response and an error code",
        expected_names: ["AxiosError"],
        expected_files: ["core/AxiosError"],
    },
    {
        id: "AX21",
        query: "toFormData serialize object into multipart form data",
        difficulty: "medium",
        topK: 5,
        description: "Helper that converts a plain object into a FormData instance for multipart uploads",
        expected_names: ["toFormData"],
        expected_files: ["helpers/toFormData"],
    },
    {
        id: "AX22",
        query: "wrap the validateStatus check so a bad HTTP status rejects the promise with an error",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent pointing at settle, which resolves/rejects based on validateStatus",
        expected_names: ["settle"],
        expected_files: ["core/settle"],
    },
    {
        id: "AX23",
        query: "configure an HTTP proxy and inject Proxy-Authorization on the outgoing node request",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent for setProxy in the node http adapter (identifier not spoken)",
        expected_names: ["setProxy"],
        expected_files: ["adapters/http"],
    },
    {
        id: "AX24",
        query: "parseHeaders parse a raw HTTP header block into an object",
        difficulty: "medium",
        topK: 5,
        description: "Keyword lookup for the raw-header parser and its duplicate-key guard",
        expected_names: ["parseHeaders_export_statement","ignoreDuplicateOf"],
        expected_files: ["helpers/parseHeaders"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-AX4",
        query: "AxiosURLSearchParams",
        difficulty: "easy",
        topK: 5,
        description: "Custom URLSearchParams implementation that serialises params to a query string",
        expected_names: ["AxiosURLSearchParams"],
        expected_files: ["helpers/AxiosURLSearchParams"],
        heldOut: true,
    },
    {
        id: "HO-AX5",
        query: "speedometer",
        difficulty: "easy",
        topK: 5,
        description: "Computes the data transfer rate over a sliding window of recent byte samples",
        expected_names: ["speedometer"],
        expected_files: ["helpers/speedometer"],
        heldOut: true,
    },
    {
        id: "HO-AX6",
        query: "isAbsoluteURL",
        difficulty: "easy",
        topK: 5,
        description: "Predicate that tests whether a URL is absolute (scheme:// or protocol-relative)",
        expected_names: ["isAbsoluteURL"],
        expected_files: ["helpers/isAbsoluteURL"],
        heldOut: true,
    },
    {
        id: "HO-AX7",
        query: "knownAdapters getAdapter pick http or xhr adapter",
        difficulty: "medium",
        topK: 5,
        description: "Registry that resolves a named adapter (http/xhr/fetch) to its implementation",
        expected_names: ["knownAdapters"],
        expected_files: ["adapters/adapters"],
        heldOut: true,
    },
    {
        id: "HO-AX8",
        query: "progressEventReducer throttle upload download progress events",
        difficulty: "medium",
        topK: 5,
        description: "Builds a throttled progress listener that reports rate and loaded/total bytes",
        expected_names: ["progressEventReducer"],
        expected_files: ["adapters/xhr"],
        heldOut: true,
    },
    {
        id: "HO-AX9",
        query: "parseProtocol extract the scheme from a url string",
        difficulty: "medium",
        topK: 5,
        description: "Helper that returns the protocol/scheme prefix of a URL (e.g. data, http)",
        expected_names: ["parseProtocol"],
        expected_files: ["helpers/parseProtocol"],
        heldOut: true,
    },
    {
        id: "HO-AX10",
        query: "formDataToJSON turn submitted form fields with bracket paths into a nested object",
        difficulty: "medium",
        topK: 5,
        description: "Helper that rebuilds nested JSON from FormData keys like a[b][c]",
        expected_names: ["formDataToJSON","parsePropPath"],
        expected_files: ["helpers/formDataToJSON"],
        heldOut: true,
    },
    {
        id: "HO-AX11",
        query: "deep merge two plain config objects recursively combining nested keys",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent for the utils deep-merge primitive (not mergeConfig, the low-level merge)",
        expected_names: ["merge"],
        expected_files: ["lib/utils"],
        heldOut: true,
    },
    {
        id: "HO-AX12",
        query: "rate limiter that ignores calls happening more often than a fixed frequency",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent for throttle decorator used to limit progress callbacks",
        expected_names: ["throttle"],
        expected_files: ["helpers/throttle"],
        heldOut: true,
    },
    {
        id: "HO-AX13",
        query: "throw a CanceledError if the token has already been aborted before sending",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent for the pre-dispatch cancellation guard (pivotal for a cancel-flow trace)",
        expected_names: ["throwIfCancellationRequested","CanceledError"],
        expected_files: ["core/dispatchRequest","cancel/CanceledError"],
        heldOut: true,
    },
    {
        id: "HO-AX14",
        query: "normalize a header name to lowercase and coerce its value before storing",
        difficulty: "hard",
        topK: 10,
        description: "NL-intent for the AxiosHeaders private normalizers (header casing + value coercion)",
        expected_names: ["normalizeHeader","normalizeValue"],
        expected_files: ["core/AxiosHeaders"],
        heldOut: true,
    },
    {
        id: "HO-AX15",
        query: "Building a single absolute request URL by serialising query parameters and joining the base URL with the relative path",
        difficulty: "semantic",
        topK: 10,
        description: "Cross-cutting URL-assembly chain across buildURL/combineURLs/buildFullPath",
        expected_names: ["buildURL","combineURLs","buildFullPath"],
        expected_files: ["helpers/buildURL","helpers/combineURLs","core/buildFullPath"],
        heldOut: true,
    },
    {
        id: "HO-AX16",
        query: "Streaming a multipart upload body part by part so large files are not buffered entirely in memory",
        difficulty: "semantic",
        topK: 10,
        description: "Conceptual search for the Node form-data streaming helper and its part class",
        expected_names: ["formDataToStream","FormDataPart"],
        expected_files: ["helpers/formDataToStream"],
        heldOut: true,
    },
    {
        id: "HO-AX17",
        query: "Following a redirect while re-applying the same proxy settings the original request used",
        difficulty: "semantic",
        topK: 10,
        description: "Conceptual search for the before-redirect proxy/config hooks in the node adapter",
        expected_names: ["dispatchBeforeRedirect","setProxy"],
        expected_files: ["adapters/http"],
        heldOut: true,
    },
    {
        id: "HO-AX18",
        query: "Decompressing a gzip or brotli encoded HTTP response body stream as it arrives",
        difficulty: "semantic",
        topK: 10,
        description: "Conceptual search for the node adapter decompression option blocks",
        expected_names: ["zlibOptions","brotliOptions","supportedProtocols"],
        expected_files: ["adapters/http"],
        heldOut: true,
    },
    {
        id: "HO-AX19",
        query: "Reading the value of a browser cookie by name to attach the XSRF token to a request",
        difficulty: "semantic",
        topK: 10,
        description: "Conceptual search for the standard-browser cookie read/write helper",
        expected_names: ["cookies_export_statement"],
        expected_files: ["helpers/cookies"],
        heldOut: true,
    },
];
