/**
 * test/suites/cjson.mjs
 *
 * Ground-truth query set for cJSON (C) — a subset of DaveGamble/cJSON.
 * Source: https://github.com/DaveGamble/cJSON
 *
 * Key source layout:
 *   cJSON.c        — the whole public API + internal parser/printer:
 *                      cJSON_Parse / cJSON_ParseWithOpts / cJSON_ParseWithLength,
 *                      parse_value / parse_string / parse_number / parse_hex4 /
 *                      utf16_literal_to_utf8, cJSON_Print / cJSON_PrintUnformatted /
 *                      cJSON_PrintBuffered, print_value, cJSON_Minify / minify_string /
 *                      skip_oneline_comment / skip_multiline_comment,
 *                      cJSON_CreateObject / cJSON_CreateArray / cJSON_CreateString,
 *                      cJSON_AddItemToObject / cJSON_AddStringToObject,
 *                      cJSON_GetObjectItem / cJSON_GetObjectItemCaseSensitive /
 *                      cJSON_GetArrayItem, cJSON_Delete, cJSON_Duplicate,
 *                      cJSON_Compare, cJSON_InitHooks, internal_malloc/internal_free
 *   cJSON.h        — struct cJSON, cJSON_Hooks
 *   cJSON_Utils.c  — JSON Pointer (RFC 6901) + JSON Patch (RFC 6902) helpers:
 *                      cJSONUtils_GetPointer, cJSONUtils_ApplyPatches,
 *                      cJSONUtils_MergePatch, cJSONUtils_GenerateMergePatch
 *   tests/         — Unity-based unit tests (not the public API)
 */

export const META = {
    id: 'cjson',
    displayName: 'cJSON',
    language: 'C',
    version: 'subset',
    url: 'https://github.com/DaveGamble/cJSON',
    expectedMinChunks: 200,
    expectedMinFiles: 30,
};

export const QUERIES = [
    // ── EASY (symbolic keyword lookup) ─────────────────────────────────────────

    {
        id: 'CJ01',
        query: 'cJSON_Minify',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'cJSON_Minify — strips whitespace and comments from a JSON string in place',
        expected_names: ['cJSON_Minify'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ02',
        query: 'cJSON_Delete free item',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'cJSON_Delete — recursively frees a cJSON item and its children',
        expected_names: ['cJSON_Delete'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ03',
        query: 'duplicate clone a JSON item recursively',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'cJSON_Duplicate — deep-copies a JSON item and its subtree (adapted from seed)',
        expected_names: ['cJSON_Duplicate'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ04',
        query: 'get object item by key string lookup',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'cJSON_GetObjectItem — looks up a child of an object by its key',
        expected_names: ['cJSON_GetObjectItem', 'cJSON_GetObjectItemCaseSensitive'],
        expected_files: ['cJSON.c'],
    },

    // ── MEDIUM (keyword over a small cluster) ──────────────────────────────────

    {
        id: 'CJ05',
        query: 'print render JSON tree to string formatted unformatted',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'cJSON_Print / cJSON_PrintUnformatted — serialise a tree back to a JSON text string',
        expected_names: ['cJSON_Print', 'cJSON_PrintUnformatted', 'cJSON_PrintBuffered'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ06',
        query: 'create object array string number node',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'cJSON_Create* constructors that allocate new typed value nodes',
        expected_names: ['cJSON_CreateObject', 'cJSON_CreateArray', 'cJSON_CreateString', 'cJSON_CreateNumber'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ07',
        query: 'add item to object set key value pair',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'cJSON_AddItemToObject / cJSON_AddStringToObject — attach a child under a key',
        expected_names: ['cJSON_AddItemToObject', 'cJSON_AddStringToObject', 'add_item_to_object'],
        expected_files: ['cJSON.c'],
    },

    // ── NL / SEMANTIC (behavioural — never naming the symbol) ──────────────────

    {
        id: 'CJ08',
        query: 'parse a JSON text string into an in-memory tree of value nodes',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'cJSON_Parse — the top-level entry point that turns JSON text into a value tree (seed)',
        expected_names: ['cJSON_Parse', 'cJSON_ParseWithOpts', 'cJSON_ParseWithLength'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ09',
        query: 'remove the whitespace and comments from a block of text so it becomes compact',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Behavioural search for the minifier (cJSON_Minify / minify_string and comment skippers)',
        expected_names: ['cJSON_Minify', 'minify_string', 'skip_oneline_comment', 'skip_multiline_comment'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ10',
        query: 'decode an escaped unicode character sequence into its actual UTF-8 bytes',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Behavioural search for the \\uXXXX escape decoder (parse_hex4 / utf16_literal_to_utf8)',
        expected_names: ['utf16_literal_to_utf8', 'parse_hex4'],
        expected_files: ['cJSON.c'],
    },

    // ── XC (cross-cutting concerns, phrased behaviourally) ─────────────────────

    {
        id: 'CJ11',
        query: 'compare two JSON values for deep structural equality',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'cJSON_Compare — recursively checks two values for equality (seed)',
        expected_names: ['cJSON_Compare'],
        expected_files: ['cJSON.c'],
    },
    {
        id: 'CJ12',
        query: 'navigate into a nested document by following a slash-separated path expression',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'JSON Pointer (RFC 6901) traversal — cJSONUtils_GetPointer / get_item_from_pointer',
        expected_names: ['cJSONUtils_GetPointer', 'get_item_from_pointer', 'cJSONUtils_GetPointerCaseSensitive'],
        expected_files: ['cJSON_Utils.c'],
    },

    // ── HELD-OUT (validation only — fresh, different targets, never tuned) ──────
    {
        id: 'HO-CJ1',
        query: 'override the default memory allocator with custom malloc and free hooks',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'cJSON_InitHooks — installs caller-provided malloc/free implementations',
        expected_names: ['cJSON_InitHooks'],
        expected_files: ['cJSON.c'],
        heldOut: true,
    },
    {
        id: 'HO-CJ2',
        query: 'apply a sequence of JSON patch operations to mutate a document',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'cJSONUtils_ApplyPatches — applies an RFC 6902 patch array',
        expected_names: ['cJSONUtils_ApplyPatches', 'cJSONUtils_ApplyPatchesCaseSensitive'],
        expected_files: ['cJSON_Utils.c'],
        heldOut: true,
    },
    {
        id: 'HO-CJ3',
        query: 'cJSON_GetArrayItem',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'cJSON_GetArrayItem — returns the element of an array at a given index',
        expected_names: ['cJSON_GetArrayItem'],
        expected_files: ['cJSON.c'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "CJ13",
        query: "cJSON_GetArraySize",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "cJSON_GetArraySize — counts the number of elements in an array node",
        expected_names: ["cJSON_GetArraySize"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ14",
        query: "cJSON_GetStringValue cJSON_GetNumberValue accessors",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Typed value accessors that read the string / number payload out of an item",
        expected_names: ["cJSON_GetStringValue","cJSON_GetNumberValue"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ15",
        query: "type predicate check whether item is array object string number",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "cJSON_Is* type-introspection predicates that test the type flag of a node",
        expected_names: ["cJSON_IsArray","cJSON_IsObject","cJSON_IsString","cJSON_IsNumber","cJSON_IsBool"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ16",
        query: "detach an item from a parent without freeing it",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "cJSON_DetachItem* — unlinks a child from its array/object parent and returns it (caller owns memory)",
        expected_names: ["cJSON_DetachItemViaPointer","cJSON_DetachItemFromArray","cJSON_DetachItemFromObject"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ17",
        query: "convert four hex digits of a unicode escape into a code point",
        kind: "nl",
        difficulty: "hard",
        topK: 5,
        description: "parse_hex4 — reads a 4-digit hexadecimal escape into a numeric code unit",
        expected_names: ["parse_hex4"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ18",
        query: "grow the output buffer reallocating when more space is needed while printing",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "ensure — guarantees the print buffer has at least N free bytes, reallocating as needed",
        expected_names: ["ensure"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ19",
        query: "create reference node that shares a child without owning it",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "create_reference / cJSON_Create*Reference — wrap an existing item so it is not duplicated or freed",
        expected_names: ["create_reference","cJSON_CreateObjectReference","cJSON_CreateArrayReference","cJSON_CreateStringReference"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ20",
        query: "skip a UTF-8 byte order mark at the start of input",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "skip_utf8_bom — advances past a leading BOM before parsing begins",
        expected_names: ["skip_utf8_bom"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ21",
        query: "build a cJSON array directly from a C array of ints or floats",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "cJSON_Create*Array bulk constructors that turn a native numeric array into a JSON array",
        expected_names: ["cJSON_CreateIntArray","cJSON_CreateFloatArray","cJSON_CreateDoubleArray","cJSON_CreateStringArray"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ22",
        query: "render a single number node into text choosing the shortest precise representation",
        kind: "nl",
        difficulty: "hard",
        topK: 5,
        description: "print_number — serialises a double using the minimal round-trippable formatting",
        expected_names: ["print_number"],
        expected_files: ["cJSON.c"],
    },
    {
        id: "CJ23",
        query: "cJSON_SetValuestring cJSON_SetNumberHelper mutate value in place",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Setters that overwrite the string / number payload of an existing item",
        expected_names: ["cJSON_SetValuestring","cJSON_SetNumberHelper","cJSON_SetBoolValue"],
        expected_files: ["cJSON.c","cJSON.h"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-CJ4",
        query: "cJSON_HasObjectItem",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "cJSON_HasObjectItem — boolean check for whether an object contains a given key",
        expected_names: ["cJSON_HasObjectItem"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ5",
        query: "cJSON_ReplaceItemInObject",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "cJSON_ReplaceItemInObject — swaps the child stored under a key for a new item",
        expected_names: ["cJSON_ReplaceItemInObject","cJSON_ReplaceItemInObjectCaseSensitive","replace_item_in_object"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ6",
        query: "cJSONUtils_MergePatch",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "cJSONUtils_MergePatch — applies an RFC 7386 JSON merge patch to a target document",
        expected_names: ["cJSONUtils_MergePatch","cJSONUtils_MergePatchCaseSensitive"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ7",
        query: "install a custom memory allocator pair for malloc and free",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "internal_malloc / internal_free / internal_realloc — the default hook implementations wrapping stdlib allocation",
        expected_names: ["internal_malloc","internal_free","internal_realloc"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ8",
        query: "insert a new element at a specific position inside an array",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "cJSON_InsertItemInArray / insert_item_in_array — splices a node into the linked list at an index",
        expected_names: ["cJSON_InsertItemInArray","insert_item_in_array"],
        expected_files: ["cJSON.c","cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ9",
        query: "attach a child as a non-owning reference so it is not freed twice",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "cJSON_AddItemReferenceTo* — adds an item by reference without transferring ownership",
        expected_names: ["cJSON_AddItemReferenceToObject","cJSON_AddItemReferenceToArray"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ10",
        query: "sort the keys of an object alphabetically",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "cJSONUtils_SortObject / sort_object / sort_list — orders object members by key name",
        expected_names: ["cJSONUtils_SortObject","sort_object","sort_list","cJSONUtils_SortObjectCaseSensitive"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ11",
        query: "compute the diff between two documents and emit patch operations",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "cJSONUtils_GeneratePatches / create_patches — produce an RFC 6902 patch array describing changes from one tree to another",
        expected_names: ["cJSONUtils_GeneratePatches","create_patches","cJSONUtils_GeneratePatchesCaseSensitive"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ12",
        query: "percent-encode a key segment so it can be embedded in a JSON pointer",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "encode_string_as_pointer / pointer_encoded_length — escape ~ and / characters for an RFC 6901 pointer token",
        expected_names: ["encode_string_as_pointer","pointer_encoded_length"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ13",
        query: "translate the op field of a patch entry into an enum operation code",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "decode_patch_operation — maps the add/remove/replace/move/copy/test string to an internal enum",
        expected_names: ["decode_patch_operation"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ14",
        query: "find the JSON pointer path that leads from a root object to a target node",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "cJSONUtils_FindPointerFromObjectTo — builds the pointer string locating a descendant within a tree",
        expected_names: ["cJSONUtils_FindPointerFromObjectTo"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ15",
        query: "recursively decide if two value trees are structurally equal",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "compare_json — the cJSON_Utils deep-equality walk used by patch generation (distinct from public cJSON_Compare)",
        expected_names: ["compare_json"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ16",
        query: "remove the node addressed by a slash path then return it to the caller",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "detach_path — resolves a JSON pointer path and detaches the addressed item",
        expected_names: ["detach_path"],
        expected_files: ["cJSON_Utils.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ17",
        query: "compare two strings for equality optionally ignoring case",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "case_insensitive_strcmp — the byte-wise key comparison used for object lookups",
        expected_names: ["case_insensitive_strcmp"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
    {
        id: "HO-CJ18",
        query: "cJSON_AddNumberToObject cJSON_AddBoolToObject typed convenience adders",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Typed convenience helpers that create and attach a scalar child under a key in one call",
        expected_names: ["cJSON_AddNumberToObject","cJSON_AddBoolToObject","cJSON_AddNullToObject","cJSON_AddTrueToObject","cJSON_AddFalseToObject"],
        expected_files: ["cJSON.c"],
        heldOut: true,
    },
];
