/**
 * test/suites/laravel.mjs
 *
 * Ground-truth query set for a Laravel / PHP subset of koel/koel.
 * Source: https://github.com/koel/koel
 *
 * NOTE on granularity: chunks here are file-level — each chunk's `name` is the
 * top-level class declared in that PHP file (so expected_names are class names
 * drawn from bench/_chunks/laravel.json's `names` universe; class_context for a
 * file-level chunk equals that same class name). There are no per-method chunks.
 *
 * Key source layout (under App/):
 *   Console/Commands/ScanCommand.php           — `koel:scan` artisan command
 *   Services/Scanners/DirectoryScanner.php     — walks the media directory
 *   Services/Streamer/Streamer.php             — picks a streaming adapter, streams a song
 *   Http/Controllers/Subsonic/StreamController.php — Subsonic stream endpoint
 *   Services/Playlist/PlaylistService.php      — create / update / add songs to playlists
 *   Services/Playlist/SmartPlaylistService.php — resolves songs for rule-based playlists
 *   Values/SmartPlaylist/SmartPlaylistRule.php — a single smart-playlist rule
 *   Services/SearchService.php                 — multi-entity excerpt search
 *   Services/Auth/AuthenticationService.php    — email/password login, tokens
 *   Services/Auth/TwoFactorAuthenticator.php   — TOTP enrolment / verification
 *   Services/Upload/UploadService.php          — handle an uploaded song file
 *   Services/Integrations/LastfmService.php    — Last.fm scrobble / now-playing
 *   Services/Transcoding/TranscodeStrategyFactory.php — picks a transcoding strategy
 *   Models/Song.php, Models/Playlist.php, Models/User.php — Eloquent models
 */

export const META = {
    id: 'laravel',
    displayName: 'Koel (Laravel subset)',
    language: 'PHP/Laravel',
    version: 'subset',
    url: 'https://github.com/koel/koel',
    expectedMinChunks: 400,
    expectedMinFiles: 400,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'LV01',
        query: 'PlaylistService',
        difficulty: 'easy',
        topK: 5,
        description: 'PlaylistService — create, update and add songs to playlists',
        expected_names: ['PlaylistService'],
        expected_files: ['Services/Playlist/PlaylistService.php'],
    },
    {
        id: 'LV02',
        query: 'SearchService excerpt search',
        difficulty: 'easy',
        topK: 5,
        description: 'SearchService — runs a keyword search across songs, artists, albums, podcasts',
        expected_names: ['SearchService'],
        expected_files: ['Services/SearchService.php'],
    },

    // ── MEDIUM (domain-keyword lookup) ──────────────────────────────────────────

    {
        id: 'LV03',
        query: 'scan music library directory import songs command',
        kind: 'nl',
        difficulty: 'medium',
        topK: 5,
        description: 'Scan the media directory and import songs (adapted from search-cases scan-library)',
        expected_names: ['ScanCommand', 'DirectoryScanner'],
        expected_files: ['Console/Commands/ScanCommand.php', 'Services/Scanners'],
    },
    {
        id: 'LV04',
        query: 'stream audio file song controller play',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Stream an audio file for a song (adapted from search-cases stream-audio)',
        expected_names: ['StreamController', 'Streamer'],
        expected_files: ['StreamController.php', 'Services/Streamer/Streamer.php'],
    },
    {
        id: 'LV05',
        query: 'upload song file handle duplicate detection',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'UploadService — stores an uploaded file, detects duplicates, scans and persists it',
        expected_names: ['UploadService'],
        expected_files: ['Services/Upload/UploadService.php'],
    },
    {
        id: 'LV06',
        query: 'two factor authenticator totp recovery code',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'TwoFactorAuthenticator — TOTP enrolment, verification and recovery codes',
        expected_names: ['TwoFactorAuthenticator'],
        expected_files: ['Services/Auth/TwoFactorAuthenticator.php'],
    },

    // ── HARD / SEMANTIC (cross-cutting, behavioural) ────────────────────────────

    {
        id: 'LV07',
        query: 'add a set of songs to an existing playlist',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Adding songs to a playlist (adapted from search-cases playlist-add)',
        expected_names: ['PlaylistService', 'Playlist'],
        expected_files: ['Services/Playlist/PlaylistService.php', 'Models/Playlist.php'],
    },
    {
        id: 'LV08',
        query: 'choose the right way to convert an audio file to a lower bitrate depending on where it is stored',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Behavioural search for the transcoding strategy selection',
        expected_names: ['TranscodeStrategyFactory', 'TranscodingStrategy'],
        expected_files: ['Services/Transcoding'],
    },

    // ── SEMANTIC (intent-only, target name never spoken) ────────────────────────

    {
        id: 'LV09',
        query: 'verify a user email and password and issue an access token so they can sign in',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for the login / credential authentication flow',
        expected_names: ['AuthenticationService'],
        expected_files: ['Services/Auth/AuthenticationService.php'],
    },
    {
        id: 'LV10',
        query: 'build a playlist whose contents are decided automatically by matching rules instead of a fixed song list',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for the smart (rule-based) playlist machinery',
        expected_names: ['SmartPlaylistService', 'SmartPlaylistRule'],
        expected_files: ['Services/Playlist/SmartPlaylistService.php', 'Values/SmartPlaylist'],
    },
    {
        id: 'LV11',
        query: 'report the song a user is currently listening to and record a completed play to their external scrobbling account',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for the Last.fm now-playing / scrobble integration',
        expected_names: ['LastfmService'],
        expected_files: ['Services/Integrations/LastfmService.php'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    {
        id: 'HO-LV1',
        query: 'EqualizerPresetService',
        difficulty: 'easy',
        topK: 5,
        expected_names: ['EqualizerPresetService'],
        expected_files: ['Services/EqualizerPresetService.php'],
        heldOut: true,
    },
    {
        id: 'HO-LV2',
        query: 'resize and store an uploaded cover image for an album or artist',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        expected_names: ['ImageStorage', 'ImageWriter'],
        expected_files: ['Services/Image'],
        heldOut: true,
    },
    {
        id: 'HO-LV3',
        query: 'periodically fetch a podcast RSS feed and store any new episodes',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        expected_names: ['PodcastService', 'SyncPodcastsCommand'],
        expected_files: ['Services/Podcast/PodcastService.php', 'Console/Commands/SyncPodcastsCommand.php'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "LV12",
        query: "QueueService",
        difficulty: "easy",
        topK: 5,
        description: "QueueService — read/save a user's play queue and update playback status",
        expected_names: ["QueueService"],
        expected_files: ["Services/QueueService.php"],
    },
    {
        id: "LV13",
        query: "DownloadService download limit songs album",
        difficulty: "easy",
        topK: 5,
        description: "DownloadService — assert within download limit and build a downloadable for songs/album/artist/playlist",
        expected_names: ["DownloadService"],
        expected_files: ["Services/DownloadService.php"],
    },
    {
        id: "LV14",
        query: "toggle favorite song star unstar user",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "FavoriteService — toggle a favourite on a favoriteable entity for a user",
        expected_names: ["FavoriteService"],
        expected_files: ["Services/FavoriteService.php"],
    },
    {
        id: "LV15",
        query: "detect duplicate uploaded song by hash keep discard",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "DuplicateUploadService — detect a duplicate upload and keep/discard duplicates",
        expected_names: ["DuplicateUploadService"],
        expected_files: ["Services/Upload/DuplicateUploadService.php"],
    },
    {
        id: "LV16",
        query: "playlist collaboration invite token accept collaborator",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "PlaylistCollaborationService — create a collaboration token and accept it to join a playlist",
        expected_names: ["PlaylistCollaborationService"],
        expected_files: ["Services/Playlist/PlaylistCollaborationService.php"],
    },
    {
        id: "LV17",
        query: "find song by file path or hash recently added most played",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "SongRepository — query songs by path, hash, and aggregate lists (recently added, most/least played)",
        expected_names: ["SongRepository"],
        expected_files: ["Repositories/SongRepository.php"],
    },
    {
        id: "LV18",
        query: "authenticate a request using a trusted reverse-proxy header and provision the user from SSO",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "ProxyAuthService — trust proxy IP, read the user header, create or update the SSO user",
        expected_names: ["ProxyAuthService"],
        expected_files: ["Services/Auth/ProxyAuthService.php"],
    },
    {
        id: "LV19",
        query: "browse the media library as folders and list the songs inside a folder",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "MediaBrowser — build a subfolder view and lazily create the folder structure for a song",
        expected_names: ["MediaBrowser"],
        expected_files: ["Services/MediaBrowser.php"],
    },
    {
        id: "LV20",
        query: "pick a storage backend implementation based on where songs are kept",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "SongStorageFactory — match a storage type enum to the concrete local/cloud SongStorage",
        expected_names: ["SongStorageFactory","SongStorage"],
        expected_files: ["Services/SongStorages/SongStorageFactory.php","Services/SongStorages/SongStorage.php"],
    },
    {
        id: "LV21",
        query: "rotate or mint API tokens for a user and revoke them on logout",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "TokenManager — create/refresh personal access tokens and destroy them",
        expected_names: ["TokenManager"],
        expected_files: ["Services/Auth/TokenManager.php"],
    },
    {
        id: "LV22",
        query: "remove songs, albums and artists that no longer have any tracks on disk",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Pruning orphaned library records — LibraryManager.prune driven by the artisan command",
        expected_names: ["LibraryManager","PruneLibraryCommand"],
        expected_files: ["Services/LibraryManager.php","Console/Commands/PruneLibraryCommand.php"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-LV4",
        query: "RatingService",
        difficulty: "easy",
        topK: 5,
        description: "RatingService — set a user's rating on a rateable model",
        expected_names: ["RatingService"],
        expected_files: ["Services/RatingService.php"],
        heldOut: true,
    },
    {
        id: "HO-LV5",
        query: "UserInvitationService",
        difficulty: "easy",
        topK: 5,
        description: "UserInvitationService — invite users by email with a role and accept invitations",
        expected_names: ["UserInvitationService"],
        expected_files: ["Services/UserInvitationService.php"],
        heldOut: true,
    },
    {
        id: "HO-LV6",
        query: "EmbedService resolve embed",
        difficulty: "easy",
        topK: 5,
        description: "EmbedService — resolve a shareable embed for an embeddable entity and user",
        expected_names: ["EmbedService"],
        expected_files: ["Services/EmbedService.php"],
        heldOut: true,
    },
    {
        id: "HO-LV7",
        query: "increase play count interaction when a song is played",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "InteractionService — register a play and increase the play count for a playable",
        expected_names: ["InteractionService"],
        expected_files: ["Services/InteractionService.php"],
        heldOut: true,
    },
    {
        id: "HO-LV8",
        query: "generate two factor recovery backup codes",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "RecoveryCodeFactory — generate a batch of one-time recovery codes",
        expected_names: ["RecoveryCodeFactory"],
        expected_files: ["Services/Auth/RecoveryCodeFactory.php"],
        heldOut: true,
    },
    {
        id: "HO-LV9",
        query: "sanitize uploaded SVG cover art to strip scripts",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "SvgSanitizer — clean a raw SVG string before storing it",
        expected_names: ["SvgSanitizer"],
        expected_files: ["Services/Image/SvgSanitizer.php"],
        heldOut: true,
    },
    {
        id: "HO-LV10",
        query: "subsonic password authenticator credentials attempt",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "PasswordAuthenticator — attempt a Subsonic login from credentials",
        expected_names: ["PasswordAuthenticator"],
        expected_files: ["Services/Subsonic/Authenticators/PasswordAuthenticator.php"],
        heldOut: true,
    },
    {
        id: "HO-LV11",
        query: "delete a podcast automatically once its last subscriber unsubscribes",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "DeletePodcastIfNoSubscribers — event listener that prunes a podcast with no remaining subscribers",
        expected_names: ["DeletePodcastIfNoSubscribers"],
        expected_files: ["Listeners/DeletePodcastIfNoSubscribers.php"],
        heldOut: true,
    },
    {
        id: "HO-LV12",
        query: "when someone starts playing a track tell Last.fm what they are listening to now",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "UpdateLastfmNowPlaying — playback-started listener that pushes now-playing to Last.fm",
        expected_names: ["UpdateLastfmNowPlaying"],
        expected_files: ["Listeners/UpdateLastfmNowPlaying.php"],
        heldOut: true,
    },
    {
        id: "HO-LV13",
        query: "block access to paid plus-only features for unlicensed installations",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "RestrictPlusFeatures — middleware that gates premium endpoints behind a license",
        expected_names: ["RestrictPlusFeatures"],
        expected_files: ["Http/Middleware/RestrictPlusFeatures.php"],
        heldOut: true,
    },
    {
        id: "HO-LV14",
        query: "decide whether a user is allowed to edit or delete a playlist they do not own",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "PlaylistPolicy — authorization checks for access/own/edit/delete/collaborate on a playlist",
        expected_names: ["PlaylistPolicy"],
        expected_files: ["Policies/PlaylistPolicy.php"],
        heldOut: true,
    },
    {
        id: "HO-LV15",
        query: "stream a song while transcoding it on the fly to a different format",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "TranscodingStreamerAdapter — streaming adapter that pipes through a transcoder",
        expected_names: ["TranscodingStreamerAdapter"],
        expected_files: ["Services/Streamer/Adapters/TranscodingStreamerAdapter.php"],
        heldOut: true,
    },
    {
        id: "HO-LV16",
        query: "edit and persist environment variables in the .env file",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "DotenvEditor — read and write key/value pairs in the dotenv configuration file",
        expected_names: ["DotenvEditor"],
        expected_files: ["Services/DotenvEditor.php"],
        heldOut: true,
    },
    {
        id: "HO-LV17",
        query: "resize and store album and artist artwork and keep the model image in sync",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Image pipeline — write/resize artwork and observe model image changes to clean up old files",
        expected_names: ["ImageWriter","ModelImageObserver"],
        expected_files: ["Services/Image/ImageWriter.php","Services/Image/ModelImageObserver.php"],
        heldOut: true,
    },
    {
        id: "HO-LV18",
        query: "build a zip archive of songs and enforce the per-request download limit before serving it",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Bulk download flow — DownloadService limit + the bulk songs download controller",
        expected_names: ["DownloadService","DownloadSongsController"],
        expected_files: ["Services/DownloadService.php","Http/Controllers/Download/DownloadSongsController.php"],
        heldOut: true,
    },
];
