/**
 * test/suites/nvm.mjs
 *
 * Ground-truth query set for nvm (Bash) — a subset of nvm-sh/nvm.
 * Source: https://github.com/nvm-sh/nvm
 *
 * Key source layout (POSIX shell functions, all prefixed nvm_):
 *   nvm.sh      — the core script: install/use/ls implementations plus every
 *                   internal nvm_* helper (version resolution, path management,
 *                   downloads, checksums, aliases, shell detection, ...).
 *   install.sh  — the bootstrap installer: nvm_download, nvm_detect_profile,
 *                   install_nvm_from_git, install_nvm_as_script, nvm_do_install.
 *   rename_test.sh, test/common.sh, update_test_mocks.sh — test/dev helpers.
 *
 * Bash chunks carry no class_context and a single "unknown" type, so the
 * strict relevance predicate keys off the function name (and expected_files).
 */

export const META = {
    id: 'nvm',
    displayName: 'nvm (subset)',
    language: 'Bash',
    version: 'subset',
    url: 'https://github.com/nvm-sh/nvm',
    expectedMinChunks: 120,
    expectedMinFiles: 5,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'NV01',
        query: 'nvm_get_arch',
        difficulty: 'easy',
        topK: 5,
        description: 'Determines the system CPU architecture (x64, arm64, ...) for selecting a binary',
        expected_names: ['nvm_get_arch'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV02',
        query: 'nvm_get_os operating system',
        difficulty: 'easy',
        topK: 5,
        description: 'Maps uname output to an OS slug (linux, darwin, win, ...)',
        expected_names: ['nvm_get_os'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV03',
        query: 'nvm_ls_remote list available versions',
        difficulty: 'easy',
        topK: 5,
        description: 'Lists Node.js versions available for download from the remote index',
        expected_names: ['nvm_ls_remote', 'nvm_ls_remote_index_tab'],
        expected_files: ['nvm.sh'],
    },

    // ── MEDIUM (domain-keyword lookup) ──────────────────────────────────────────

    {
        id: 'NV04',
        query: 'is version installed check directory exists',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Checks whether a given Node version is already installed locally',
        expected_names: ['nvm_is_version_installed'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV05',
        query: 'resolve alias name to version number',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Resolves a named alias (default, stable, ...) to the version it points to',
        expected_names: ['nvm_resolve_alias', 'nvm_resolve_local_alias'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV06',
        query: 'compare two semantic version numbers greater',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Compares two dotted version strings to decide which is greater',
        expected_names: ['nvm_version_greater', 'nvm_version_greater_than_or_equal_to'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV07',
        query: 'detect shell profile file bashrc zshrc',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Locates the user shell profile to append nvm sourcing lines to',
        expected_names: ['nvm_detect_profile'],
        expected_files: ['install.sh'],
    },

    // ── NL / SEMANTIC (behavioural, no symbol name in the query) ────────────────

    {
        id: 'NV08',
        query: 'download a remote node binary tarball over the network for a version',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Generic network download helper that fetches a remote artifact',
        expected_names: ['nvm_download'],
        expected_files: ['nvm.sh', 'install.sh'],
    },
    {
        id: 'NV09',
        query: 'compute a cryptographic hash of a downloaded file to verify its integrity',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Computes a sha256/sha1 checksum of a file using whatever tool is available',
        expected_names: ['nvm_compute_checksum', 'nvm_compare_checksum', 'nvm_get_checksum'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV10',
        query: 'figure out which Node version to use from a .nvmrc file in the project tree',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Walks up the directory tree to find the nearest .nvmrc version file',
        expected_names: ['nvm_find_nvmrc', 'nvm_find_up', 'nvm_rc_version'],
        expected_files: ['nvm.sh'],
    },

    // ── XC (cross-cutting concern, phrased behaviourally) ───────────────────────

    {
        id: 'NV11',
        query: 'upgrade to the newest npm for the active node version',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Installs the latest working npm release for the current Node version',
        expected_names: ['nvm_install_latest_npm'],
        expected_files: ['nvm.sh'],
    },
    {
        id: 'NV12',
        query: 'add and remove the active version directory from the PATH environment variable',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Rewrites PATH so the chosen Node version is in front, stripping old nvm entries',
        expected_names: ['nvm_change_path', 'nvm_strip_path'],
        expected_files: ['nvm.sh'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──────────────────
    {
        id: 'HO-NV1',
        query: 'download and unpack a precompiled binary archive into the version directory',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        expected_names: ['nvm_install_binary', 'nvm_extract_tarball'],
        expected_files: ['nvm.sh'],
        heldOut: true,
    },
    {
        id: 'HO-NV2',
        query: 'nvm_check_file_permissions',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        expected_names: ['nvm_check_file_permissions'],
        expected_files: ['nvm.sh'],
        heldOut: true,
    },
    {
        id: 'HO-NV3',
        query: 'compile node from source code with the platform make jobs',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        expected_names: ['nvm_install_source', 'nvm_get_make_jobs'],
        expected_files: ['nvm.sh'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "NV13",
        query: "nvm_get_mirror",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Returns the configured download mirror URL for node or io.js releases",
        expected_names: ["nvm_get_mirror"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV14",
        query: "nvm_ls list installed versions",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Lists locally installed Node versions matching a pattern",
        expected_names: ["nvm_ls"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV15",
        query: "nvm_install_source",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Compiles and installs node from source code",
        expected_names: ["nvm_install_source"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV16",
        query: "build the download slug filename flavor os arch for a binary",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Builds the node-VERSION-OS-ARCH artifact name used to fetch a binary",
        expected_names: ["nvm_get_download_slug"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV17",
        query: "pick tarball compression format zip tar.gz tar.xz",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Chooses the artifact compression extension based on OS and xz support",
        expected_names: ["nvm_get_artifact_compression"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV18",
        query: "current active node version in use right now",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Reports the version currently on PATH (or system/none)",
        expected_names: ["nvm_ls_current"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV19",
        query: "pad a version string to full major.minor.patch form",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Normalizes a partial version into a three-part dotted version",
        expected_names: ["nvm_format_version","nvm_num_version_groups"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV20",
        query: "fetch a node artifact from the mirror checking binary availability",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Downloads the binary or source artifact for a version from the resolved mirror",
        expected_names: ["nvm_download_artifact"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV21",
        query: "translate a node version into the iojs- prefixed form and strip it back off",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Adds or removes the io.js naming prefix on a version string",
        expected_names: ["nvm_add_iojs_prefix","nvm_strip_iojs_prefix","nvm_iojs_prefix"],
        expected_files: ["nvm.sh"],
    },
    {
        id: "NV22",
        query: "warn the user about globally installed npm packages on their system node",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Detects pre-existing global npm modules and warns before install",
        expected_names: ["nvm_check_global_modules"],
        expected_files: ["install.sh"],
    },
    {
        id: "NV23",
        query: "redact the NVM_DIR and HOME prefixes from a path before printing it",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Replaces real home/nvm paths with placeholders for safe display",
        expected_names: ["nvm_sanitize_path"],
        expected_files: ["nvm.sh"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-NV4",
        query: "nvm_normalize_lts",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Expands an lts/-N relative alias into a concrete lts/<codename> alias",
        expected_names: ["nvm_normalize_lts"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV5",
        query: "nvm_get_make_jobs",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Determines how many parallel make jobs to use when compiling",
        expected_names: ["nvm_get_make_jobs"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV6",
        query: "nvm_curl_use_compression",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Decides whether curl should request compressed transfers",
        expected_names: ["nvm_curl_use_compression","nvm_curl_libz_support"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV7",
        query: "nvm_supports_xz xz tarball",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Tests whether the OS and node version can extract xz-compressed tarballs",
        expected_names: ["nvm_supports_xz"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV8",
        query: "map the configured color letters to terminal escape codes",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Translates the NVM_COLORS letter codes into ANSI color sequences",
        expected_names: ["nvm_get_colors","nvm_print_color_code"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV9",
        query: "extract just the major dot minor part of a version",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Derives the X.Y minor version from a full version string",
        expected_names: ["nvm_get_minor_version"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV10",
        query: "check whether a profile path is a bash or zsh rc file",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Tests if a profile filename ends in bashrc/zshrc/etc",
        expected_names: ["nvm_profile_is_bash_or_zsh"],
        expected_files: ["install.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV11",
        query: "is the user using a node from outside nvm a system node",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Detects a node/iojs binary present on the system independent of nvm",
        expected_names: ["nvm_has_system_node","nvm_has_system_iojs"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV12",
        query: "resolve a version pattern with no network using only local installs and cache",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Offline version resolution from installed versions then cached downloads",
        expected_names: ["nvm_offline_version","nvm_ls_cached"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV13",
        query: "follow the latest.nvm.sh redirect to discover the newest nvm release tag",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Queries the latest endpoint to find the most recent nvm version",
        expected_names: ["nvm_get_latest"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV14",
        query: "abort installation when a stray npm prefix or globalconfig is set",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Refuses to proceed when PREFIX or an npmrc prefix would break nvm",
        expected_names: ["nvm_die_on_prefix","nvm_npmrc_bad_news_bears"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV15",
        query: "clone or update the nvm repository from git during bootstrap",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Installs nvm itself by cloning/fetching its git repo into the install dir",
        expected_names: ["install_nvm_from_git"],
        expected_files: ["install.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV16",
        query: "create the default alias pointing at a freshly installed version",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Sets the default alias after install if one is not already defined",
        expected_names: ["nvm_ensure_default_set"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV17",
        query: "recursively verify that a version directory and its files are writable and self-owned",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Walks a directory tree checking write permission and ownership",
        expected_names: ["nvm_check_file_permissions"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV18",
        query: "resolve the implicit stable or lts alias to a real remote version number",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Validates and prints the version an implicit alias (stable/lts/*) points to",
        expected_names: ["nvm_validate_implicit_alias","nvm_print_implicit_alias"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
    {
        id: "HO-NV19",
        query: "nvm_install_binary_extract",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Extracts a downloaded binary tarball into the target version directory",
        expected_names: ["nvm_install_binary_extract"],
        expected_files: ["nvm.sh"],
        heldOut: true,
    },
];
