/**
 * test/suites/rails.mjs
 *
 * Ground-truth query set for the Rails (Ruby) fixture — a subset of
 * mastodon/mastodon (a large ActivityPub social-network server).
 *
 * Source layout (files live directly under test/fixtures/rails/):
 *   services/                 — service objects (the "do one thing" command pattern)
 *     post_status_service.rb        — PostStatusService: publish a new status
 *     follow_service.rb             — FollowService: follow another account
 *     fan_out_on_write_service.rb   — FanOutOnWriteService: push a status to feeds
 *     notify_service.rb             — NotifyService: create notifications
 *     mute_service.rb               — MuteService: mute an account
 *     suspend_account_service.rb    — SuspendAccountService: suspend an account
 *     resolve_account_service.rb    — ResolveAccountService: find/create remote acct
 *     fetch_link_card_service.rb    — FetchLinkCardService: fetch link preview cards
 *     process_mentions_service.rb   — ProcessMentionsService: resolve @mentions
 *     batched_remove_status_service.rb — bulk status deletion
 *     translate_status_service.rb   — TranslateStatusService: translate status text
 *     activitypub/process_collection_service.rb — ActivityPub::ProcessCollectionService
 *   models/                   — ActiveRecord models (Status, Account, Follow, PreviewCard, ...)
 *   lib/                      — feed_manager.rb, text_formatter.rb, html_aware_formatter.rb,
 *                               link_details_extractor.rb, webfinger.rb
 *   controllers/concerns/     — signature_verification.rb (HTTP signature auth)
 *
 * NOTE: ActivityPub classes are namespaced (e.g. ActivityPub::ProcessCollectionService).
 * The strict predicate splits on `::`/`.`/`#`, so the bare component name resolves.
 */

export const META = {
    id: 'rails',
    displayName: 'Mastodon (Rails subset)',
    language: 'Ruby/Rails',
    version: 'subset',
    url: 'https://github.com/mastodon/mastodon',
    expectedMinChunks: 80,
    expectedMinFiles: 40,
};

export const QUERIES = [
    // ── EASY (symbolic name / keyword lookup) ───────────────────────────────────

    {
        id: 'RB01',
        query: 'FollowService',
        difficulty: 'easy',
        topK: 5,
        description: 'FollowService — follow another account and create the relationship (adapted seed: follow)',
        expected_names: ['FollowService', 'Follow'],
        expected_files: ['services/follow_service.rb', 'models/follow.rb'],
    },
    {
        id: 'RB02',
        query: 'FeedManager',
        difficulty: 'easy',
        topK: 5,
        description: 'FeedManager — manages Redis-backed home/list timeline feeds',
        expected_names: ['FeedManager'],
        expected_files: ['lib/feed_manager.rb'],
    },
    {
        id: 'RB03',
        query: 'PreviewCard',
        difficulty: 'easy',
        topK: 5,
        description: 'PreviewCard — model for link preview cards attached to statuses',
        expected_names: ['PreviewCard'],
        expected_files: ['models/preview_card.rb'],
    },

    // ── MEDIUM (keyword lookup over a behavioural concept) ──────────────────────

    {
        id: 'RB04',
        query: 'mute account notifications service',
        difficulty: 'medium',
        topK: 5,
        description: 'MuteService — mutes a target account and optionally hides its notifications',
        expected_names: ['MuteService'],
        expected_files: ['services/mute_service.rb'],
    },
    {
        id: 'RB05',
        query: 'fetch link preview card from url',
        difficulty: 'medium',
        topK: 5,
        description: 'FetchLinkCardService — extracts URLs from a status and builds a link preview card',
        expected_names: ['FetchLinkCardService'],
        expected_files: ['services/fetch_link_card_service.rb'],
    },
    {
        id: 'RB06',
        query: 'process mentions resolve remote users',
        difficulty: 'medium',
        topK: 5,
        description: 'ProcessMentionsService — scans a status for @mentions and resolves the accounts',
        expected_names: ['ProcessMentionsService'],
        expected_files: ['services/process_mentions_service.rb'],
    },

    // ── NL / SEMANTIC (behavioural; target symbol NOT named) ────────────────────

    {
        id: 'RB07',
        query: 'publish a new status for an account with text and media attachments',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'PostStatusService — composes and persists a new status (seed: post-status)',
        expected_names: ['PostStatusService'],
        expected_files: ['services/post_status_service.rb'],
    },
    {
        id: 'RB08',
        query: 'push a newly created post into the home and mentions timelines of all followers',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'FanOutOnWriteService — distributes a status into followers feeds',
        expected_names: ['FanOutOnWriteService'],
        expected_files: ['services/fan_out_on_write_service.rb'],
    },
    {
        id: 'RB09',
        query: 'look up or create the local record for a remote user given their handle, fetching their profile',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'ResolveAccountService — resolves a username@domain via webfinger + ActivityPub',
        expected_names: ['ResolveAccountService'],
        expected_files: ['services/resolve_account_service.rb'],
    },

    // ── XC / CROSS-CUTTING (behavioural, spans files) ───────────────────────────

    {
        id: 'RB10',
        query: 'process an incoming ActivityPub activity delivered to the inbox',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'ActivityPub::ProcessCollectionService — handles an incoming AP payload (adapted seed: process-ap)',
        expected_names: ['ActivityPub', 'ProcessCollectionService'],
        expected_files: ['services/activitypub/process_collection_service.rb'],
    },
    {
        id: 'RB11',
        query: 'verify the cryptographic HTTP signature on an incoming federated request to authenticate the sender',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'SignatureVerification — controller concern that validates HTTP request signatures',
        expected_names: ['SignatureVerification'],
        expected_files: ['controllers/concerns/signature_verification.rb'],
    },
    {
        id: 'RB12',
        query: 'create a notification for a recipient and decide whether it should also be emailed',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'NotifyService — builds notifications and gates email delivery by type',
        expected_names: ['NotifyService'],
        expected_files: ['services/notify_service.rb'],
    },

    // ── HELD-OUT (validation only — authored fresh, distinct targets) ───────────
    {
        id: 'HO-RB1',
        query: 'SuspendAccountService',
        difficulty: 'easy',
        topK: 5,
        expected_names: ['SuspendAccountService'],
        expected_files: ['services/suspend_account_service.rb'],
        heldOut: true,
    },
    {
        id: 'HO-RB2',
        query: 'convert a status body into safe sanitised HTML, linkifying mentions and hashtags',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        expected_names: ['HtmlAwareFormatter', 'TextFormatter'],
        expected_files: ['lib/html_aware_formatter.rb', 'lib/text_formatter.rb'],
        heldOut: true,
    },
    {
        id: 'HO-RB3',
        query: 'delete many statuses at once efficiently and clean them out of timelines',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        expected_names: ['BatchedRemoveStatusService'],
        expected_files: ['services/batched_remove_status_service.rb'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "RB13",
        query: "ReblogService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "ReblogService — reblog/boost a status and notify its remote author",
        expected_names: ["ReblogService"],
        expected_files: ["services/reblog_service.rb"],
    },
    {
        id: "RB14",
        query: "BackupService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "BackupService — export an account's data as a downloadable zip archive",
        expected_names: ["BackupService"],
        expected_files: ["services/backup_service.rb"],
    },
    {
        id: "RB15",
        query: "cast a vote on a poll for an account",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "VoteService — records an account's poll choices under a redis lock and notifies voters",
        expected_names: ["VoteService"],
        expected_files: ["services/vote_service.rb"],
    },
    {
        id: "RB16",
        query: "report an account to moderators and notify staff",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "ReportService — files a report against an account, notifies staff, optionally forwards to origin",
        expected_names: ["ReportService"],
        expected_files: ["services/report_service.rb"],
    },
    {
        id: "RB17",
        query: "favourite a status and notify the remote author",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "FavouriteService — likes a status, registers the trend, creates a notification",
        expected_names: ["FavouriteService"],
        expected_files: ["services/favourite_service.rb"],
    },
    {
        id: "RB18",
        query: "full text search across accounts statuses and hashtags",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "SearchService — top-level search dispatcher over accounts/statuses/tags with a query string",
        expected_names: ["SearchService"],
        expected_files: ["services/search_service.rb"],
    },
    {
        id: "RB19",
        query: "block another account and sever the following relationships",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "BlockService — blocks a target account, unfollows both directions, enqueues BlockWorker",
        expected_names: ["BlockService"],
        expected_files: ["services/block_service.rb"],
    },
    {
        id: "RB20",
        query: "rebuild and warm a user's home and list timelines from scratch in redis",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "PrecomputeFeedService — populates home + owned-list feeds via FeedManager regeneration",
        expected_names: ["PrecomputeFeedService"],
        expected_files: ["services/precompute_feed_service.rb"],
    },
    {
        id: "RB21",
        query: "compute the set of remote inboxes a status should be delivered to",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "StatusReachFinder — collects reachable account/follower/relay inboxes for federation delivery",
        expected_names: ["StatusReachFinder"],
        expected_files: ["lib/status_reach_finder.rb"],
    },
    {
        id: "RB22",
        query: "build ActivityPub URIs and resolve local domain for accounts and statuses",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "TagManager (and ActivityPub/OStatus variants) — generates and parses federation URIs / local-domain checks",
        expected_names: ["TagManager","ActivityPub::TagManager","OStatus::TagManager"],
        expected_files: ["lib/tag_manager.rb","lib/activitypub/tag_manager.rb","lib/ostatus/tag_manager.rb"],
    },
    {
        id: "RB23",
        query: "automatically delete old statuses for an account based on a retention policy",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "AccountStatusesCleanupService — deletes statuses past the policy cutoff within a budget",
        expected_names: ["AccountStatusesCleanupService"],
        expected_files: ["services/account_statuses_cleanup_service.rb"],
    },
    {
        id: "RB24",
        query: "register a new user from an OAuth app and issue an access token",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "AppSignUpService — creates a user + access token inside a transaction for app-based sign-up",
        expected_names: ["AppSignUpService"],
        expected_files: ["services/app_sign_up_service.rb"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-RB4",
        query: "UnfollowService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "UnfollowService — stop following an account and notify the remote user",
        expected_names: ["UnfollowService"],
        expected_files: ["services/unfollow_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB5",
        query: "DeleteAccountService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "DeleteAccountService — purges all of an account's associated records on deletion/suspension",
        expected_names: ["DeleteAccountService"],
        expected_files: ["services/delete_account_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB6",
        query: "Webfinger",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Webfinger — resolves a username@domain handle to its actor URI via the webfinger protocol",
        expected_names: ["Webfinger"],
        expected_files: ["lib/webfinger.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB7",
        query: "PermalinkRedirector",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "PermalinkRedirector — maps a frontend permalink path to its underlying record",
        expected_names: ["PermalinkRedirector"],
        expected_files: ["lib/permalink_redirector.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB8",
        query: "approve a pending follow request and create the follow",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "AuthorizeFollowService — authorizes a FollowRequest and notifies the source account",
        expected_names: ["AuthorizeFollowService"],
        expected_files: ["services/authorize_follow_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB9",
        query: "extract hashtags from status text and attach the tags",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "ProcessHashtagsService — parses #hashtags from a status and assigns/updates the Tag records",
        expected_names: ["ProcessHashtagsService"],
        expected_files: ["services/process_hashtags_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB10",
        query: "translate a status into another language using a backend with caching",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "TranslateStatusService — translates a status' text via a cached translation backend",
        expected_names: ["TranslateStatusService"],
        expected_files: ["services/translate_status_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB11",
        query: "edit an existing status and create an edit snapshot",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "UpdateStatusService — applies an edit to a status, tracking the previous revision",
        expected_names: ["UpdateStatusService"],
        expected_files: ["services/update_status_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB12",
        query: "scrape a web page for its title image and structured metadata to build a link preview",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "LinkDetailsExtractor — pulls Open Graph / JSON-LD metadata out of fetched HTML for preview cards",
        expected_names: ["LinkDetailsExtractor"],
        expected_files: ["lib/link_details_extractor.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB13",
        query: "migrate a user to a new account and redirect followers to the new one",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "MoveService — sets the moved_to redirect and distributes the move to followers",
        expected_names: ["MoveService"],
        expected_files: ["services/move_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB14",
        query: "render a status body as plain text stripping all HTML markup",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "PlainTextFormatter — converts a status' HTML content down to plain text",
        expected_names: ["PlainTextFormatter"],
        expected_files: ["lib/plain_text_formatter.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB15",
        query: "given an arbitrary URL find the local or remote resource it points to",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "ResolveURLService — resolves a pasted URL to an account or status, fetching remotely if needed",
        expected_names: ["ResolveURLService"],
        expected_files: ["services/resolve_url_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB16",
        query: "undo a like on a status and remove the notification",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "UnfavouriteService — removes a favourite and undoes its side effects",
        expected_names: ["UnfavouriteService"],
        expected_files: ["services/unfavourite_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB17",
        query: "fan a freshly published status out to follower feeds asynchronously via a background job",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "DistributionWorker — Sidekiq job that locks and invokes FanOutOnWriteService for a status",
        expected_names: ["DistributionWorker"],
        expected_files: ["workers/distribution_worker.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB18",
        query: "search the database for matching accounts by handle resolving unknown remote ones",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "AccountSearchService / TagSearchService / StatusesSearchService — the per-entity search backends behind SearchService",
        expected_names: ["AccountSearchService","TagSearchService","StatusesSearchService"],
        expected_files: ["services/account_search_service.rb","services/tag_search_service.rb","services/statuses_search_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB19",
        query: "deliver an outgoing webhook event payload to a configured endpoint",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "WebhookService — dispatches a webhook event to its target URL",
        expected_names: ["WebhookService"],
        expected_files: ["services/webhook_service.rb"],
        heldOut: true,
    },
    {
        id: "HO-RB20",
        query: "record how a user voted on a poll choice",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "PollVote — ActiveRecord model for an individual account's vote on a poll option",
        expected_names: ["PollVote"],
        expected_files: ["models/poll_vote.rb"],
        heldOut: true,
    },
];
