/**
 * test/suites/rust.mjs
 *
 * Ground-truth query set for a subset of serde-rs/json (Rust).
 * Source: https://github.com/serde-rs/json
 *
 * Key source layout:
 *   src/de.rs          — struct Deserializer, from_str/from_slice/from_reader,
 *                          StreamDeserializer, disable_recursion_limit
 *   src/ser.rs         — Serializer, to_string / to_string_pretty / to_writer,
 *                          PrettyFormatter, format_escaped_str
 *   src/error.rs       — struct Error, enum Category, classify()
 *   src/number.rs      — struct Number, is_i64/as_i64/as_f64
 *   src/map.rs         — struct Map (ordered), insert/get/entry/sort_keys, Entry
 *   src/raw.rs         — struct RawValue (unparsed JSON)
 *   src/read.rs        — parse_escape / parse_unicode_escape / decode_four_hex_digits
 *   src/value/mod.rs   — enum Value, pointer / pointer_mut, to_value / from_value
 *
 * Names below are drawn ONLY from bench/_chunks/rust.json (the indexed universe).
 */

export const META = {
    id: 'rust',
    displayName: 'serde_json (subset)',
    language: 'Rust',
    version: 'subset',
    url: 'https://github.com/serde-rs/json',
    expectedMinChunks: 80,
    expectedMinFiles: 20,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'RS01',
        query: 'Deserializer',
        difficulty: 'easy',
        topK: 5,
        description: 'Deserializer — drives parsing a JSON document from an input source',
        expected_names: ['Deserializer'],
        expected_files: ['de.rs'],
    },
    {
        id: 'RS02',
        query: 'Number is_i64 as_f64',
        difficulty: 'easy',
        topK: 5,
        description: 'Number type and its as_i64/as_f64 accessors for JSON numeric values',
        expected_names: ['Number', 'as_i64', 'as_f64', 'is_i64'],
        expected_files: ['number.rs'],
    },
    {
        id: 'RS03',
        query: 'RawValue',
        difficulty: 'easy',
        topK: 5,
        description: 'RawValue — a reference to a raw, not-yet-parsed piece of JSON',
        expected_names: ['RawValue'],
        expected_files: ['raw.rs'],
    },
    {
        id: 'RS04',
        query: 'PrettyFormatter pretty print indent',
        difficulty: 'easy',
        topK: 5,
        description: 'PrettyFormatter — formatter that emits indented, human-readable JSON',
        expected_names: ['PrettyFormatter'],
        expected_files: ['ser.rs'],
    },

    // ── MEDIUM (keyword lookup, multiple acceptable targets) ────────────────────

    {
        id: 'RS05',
        query: 'parse json from string slice reader',
        difficulty: 'medium',
        topK: 5,
        description: 'Top-level deserialize entry points reading from a &str, byte slice or reader',
        expected_names: ['from_str', 'from_slice', 'from_reader'],
        expected_files: ['de.rs'],
    },
    {
        id: 'RS06',
        query: 'serialize value to json string writer',
        difficulty: 'medium',
        topK: 5,
        description: 'Top-level serialize entry points producing a String or writing to a writer',
        expected_names: ['to_string', 'to_string_pretty', 'to_writer'],
        expected_files: ['ser.rs'],
    },
    {
        id: 'RS07',
        query: 'map insert get entry by key',
        difficulty: 'medium',
        topK: 5,
        description: 'Map of String keys to Values with insert / get / entry operations',
        expected_names: ['Map', 'insert', 'get', 'entry'],
        expected_files: ['map.rs'],
    },
    {
        id: 'RS08',
        query: 'error category classify io syntax data eof',
        difficulty: 'medium',
        topK: 5,
        description: 'Error type and its Category classification (Io / Syntax / Data / Eof)',
        expected_names: ['Error', 'Category', 'classify'],
        expected_files: ['error.rs'],
    },

    // ── HARD / SEMANTIC (cross-cutting + behavioural; target NOT named) ─────────

    {
        id: 'RS09',
        query: 'decode a backslash escape sequence and a \\u four-hex-digit unicode code point including surrogate pairs',
        difficulty: 'hard',
        topK: 10,
        description: 'String-escape handling while reading: parse \\n, \\t and \\uXXXX unicode escapes',
        expected_names: ['parse_escape', 'parse_unicode_escape', 'decode_four_hex_digits'],
        expected_files: ['read.rs'],
    },
    {
        id: 'RS10',
        query: 'look up a deeply nested value inside a document using a slash-separated path expression',
        difficulty: 'semantic',
        topK: 10,
        description: 'JSON Pointer (RFC 6901) lookup that walks nested objects/arrays by a "/a/b/0" path',
        expected_names: ['pointer', 'pointer_mut'],
        expected_files: ['value/mod.rs'],
    },
    {
        id: 'RS11',
        query: 'convert any serializable Rust data structure into an in-memory dynamic JSON value tree without going through text',
        difficulty: 'semantic',
        topK: 10,
        description: 'to_value — turn a T:Serialize into a Value enum directly',
        expected_names: ['to_value', 'from_value'],
        expected_files: ['value'],
    },
    {
        id: 'RS12',
        query: 'iterate over a stream of concatenated JSON documents one after another from a single input',
        difficulty: 'semantic',
        topK: 10,
        description: 'StreamDeserializer — yields successive JSON values from a continuous input',
        expected_names: ['StreamDeserializer'],
        expected_files: ['de.rs'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    {
        id: 'HO-RS1',
        query: 'sort_keys',
        difficulty: 'easy',
        topK: 5,
        description: 'Reorder a map so its keys are in sorted order',
        expected_names: ['sort_keys'],
        expected_files: ['map.rs'],
        heldOut: true,
    },
    {
        id: 'HO-RS2',
        query: 'turn off the maximum nesting depth guard that protects against stack overflow on deeply nested input',
        difficulty: 'semantic',
        topK: 10,
        description: 'disable_recursion_limit — removes the recursion-depth safety cap on the deserializer',
        expected_names: ['disable_recursion_limit'],
        expected_files: ['de.rs'],
        heldOut: true,
    },
    {
        id: 'HO-RS3',
        query: 'write a string field to the output while escaping characters that are not valid raw JSON',
        difficulty: 'semantic',
        topK: 10,
        description: 'format_escaped_str — emits a JSON string literal with proper escaping',
        expected_names: ['format_escaped_str'],
        expected_files: ['ser.rs'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "RS13",
        query: "contains_key get_key_value",
        difficulty: "easy",
        topK: 5,
        description: "Map lookups: test for a key's presence and fetch the (key, value) pair together",
        expected_names: ["contains_key","get_key_value"],
        expected_files: ["map.rs"],
    },
    {
        id: "RS14",
        query: "remove a map entry by key shifting versus swapping the last element",
        difficulty: "medium",
        topK: 5,
        description: "Two removal strategies on the ordered Map: shift_remove preserves order, swap_remove is O(1)",
        expected_names: ["shift_remove","swap_remove"],
        expected_files: ["map.rs"],
    },
    {
        id: "RS15",
        query: "keep only the map entries that satisfy a predicate closure",
        difficulty: "medium",
        topK: 5,
        description: "retain — drop key/value pairs for which the supplied closure returns false",
        expected_names: ["retain"],
        expected_files: ["map.rs"],
    },
    {
        id: "RS16",
        query: "borrow the inner object map, array vector or string slice out of a Value if it has that shape",
        difficulty: "hard",
        topK: 10,
        description: "Value accessor conversions returning Option references for object/array/string variants",
        expected_names: ["as_object","as_array","as_str"],
        expected_files: ["value/mod.rs"],
    },
    {
        id: "RS17",
        query: "Entry OccupiedEntry VacantEntry",
        difficulty: "easy",
        topK: 5,
        description: "Entry API for the Map: occupied vs vacant slot view for in-place insertion",
        expected_names: ["Entry","OccupiedEntry","VacantEntry"],
        expected_files: ["map.rs"],
    },
    {
        id: "RS18",
        query: "serialize a value into a byte vector of JSON instead of a String",
        difficulty: "medium",
        topK: 5,
        description: "to_vec / to_vec_pretty — produce Vec<u8> JSON output",
        expected_names: ["to_vec","to_vec_pretty"],
        expected_files: ["ser.rs"],
    },
    {
        id: "RS19",
        query: "interpret an array index token from a JSON pointer path segment as a usize",
        difficulty: "hard",
        topK: 10,
        description: "parse_index — convert a pointer path component into a numeric array index, rejecting leading zeros",
        expected_names: ["parse_index"],
        expected_files: ["value/mod.rs"],
    },
    {
        id: "RS20",
        query: "move a Value out leaving Null behind in its place",
        difficulty: "semantic",
        topK: 10,
        description: "take — mem::replace the Value with Value::Null and return the original",
        expected_names: ["take"],
        expected_files: ["value/mod.rs"],
    },
    {
        id: "RS21",
        query: "reject object keys that are not strings or are non-finite floats while serializing a map",
        difficulty: "hard",
        topK: 10,
        description: "Key validation errors raised by the value serializer's MapKeySerializer",
        expected_names: ["key_must_be_a_string","float_key_must_be_finite"],
        expected_files: ["ser.rs"],
    },
    {
        id: "RS22",
        query: "Iter IterMut Keys Values ValuesMut",
        difficulty: "easy",
        topK: 10,
        description: "Map iterator view structs over entries, keys and values (immutable and mutable)",
        expected_names: ["Iter","IterMut","Keys","Values","ValuesMut"],
        expected_files: ["map.rs"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-RS4",
        query: "append",
        difficulty: "easy",
        topK: 5,
        description: "Move all entries from another map into this one, draining the source",
        expected_names: ["append"],
        expected_files: ["map.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS5",
        query: "with_capacity",
        difficulty: "easy",
        topK: 5,
        description: "Construct an empty Map preallocated to hold at least the given number of entries",
        expected_names: ["with_capacity"],
        expected_files: ["map.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS6",
        query: "consume the map and iterate over just its owned values discarding the keys",
        difficulty: "medium",
        topK: 5,
        description: "into_values — owning iterator yielding only the Value of each entry",
        expected_names: ["into_values"],
        expected_files: ["map.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS7",
        query: "check whether a JSON number can be represented exactly as a signed 64-bit, unsigned 64-bit or floating point",
        difficulty: "hard",
        topK: 10,
        description: "Value numeric-kind predicates distinguishing i64 / u64 / f64 representability",
        expected_names: ["is_i64","is_u64","is_f64"],
        expected_files: ["value/mod.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS8",
        query: "build a Number from a 128-bit integer when it fits, signed or unsigned",
        difficulty: "medium",
        topK: 5,
        description: "Number constructors from i128 / u128 that return None when the value is out of range",
        expected_names: ["from_i128","from_u128"],
        expected_files: ["number.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS9",
        query: "from_string_unchecked",
        difficulty: "easy",
        topK: 5,
        description: "Wrap an already-validated numeric string into a Number without re-parsing",
        expected_names: ["from_string_unchecked"],
        expected_files: ["number.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS10",
        query: "convert decimal mantissa and exponent digits into a binary float on the fast and truncated paths",
        difficulty: "hard",
        topK: 10,
        description: "Lexical float assembly entry points for concise vs truncated mantissas",
        expected_names: ["parse_concise_float","parse_truncated_float"],
        expected_files: ["lexical/parse.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS11",
        query: "tiered strategy for parsing a floating point: exact hardware multiply then extended precision then big-integer fallback",
        difficulty: "semantic",
        topK: 10,
        description: "The fast/moderate/fallback ladder of the lexical atof algorithm",
        expected_names: ["fast_path","moderate_path","fallback_path"],
        expected_files: ["lexical/algorithm.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS12",
        query: "compare a JSON value for equality against a raw Rust integer, float, bool or string",
        difficulty: "hard",
        topK: 10,
        description: "PartialEq helpers letting Value be compared directly to primitive operands",
        expected_names: ["eq_i64","eq_u64","eq_f64","eq_bool","eq_str"],
        expected_files: ["value/partial_eq.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS13",
        query: "read the next byte from the input but raise an end-of-file error if the stream is exhausted",
        difficulty: "medium",
        topK: 5,
        description: "next_or_eof / peek_or_eof — byte reads that surface EOF as a parse error",
        expected_names: ["next_or_eof","peek_or_eof"],
        expected_files: ["read.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS14",
        query: "push_wtf8_codepoint",
        difficulty: "easy",
        topK: 5,
        description: "Encode a decoded unicode scalar (including lone surrogates) into the scratch buffer",
        expected_names: ["push_wtf8_codepoint"],
        expected_files: ["read.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS15",
        query: "skip over an escape sequence without decoding it while ignoring a string value",
        difficulty: "medium",
        topK: 5,
        description: "ignore_escape — consume a backslash escape during value-skipping",
        expected_names: ["ignore_escape"],
        expected_files: ["read.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS16",
        query: "decide whether an incoming object key should be treated as a map key or a struct field name",
        difficulty: "hard",
        topK: 10,
        description: "KeyClassifier / KeyClass — classify a deserialized key into number/string/map-key category",
        expected_names: ["KeyClassifier","KeyClass"],
        expected_files: ["value/de.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS17",
        query: "input source readers wrapping an io::Read, a byte slice and a UTF-8 string",
        difficulty: "medium",
        topK: 10,
        description: "The three Read implementations feeding the deserializer",
        expected_names: ["IoRead","SliceRead","StrRead"],
        expected_files: ["read.rs"],
        heldOut: true,
    },
    {
        id: "HO-RS18",
        query: "recursively reorder every nested object in a value so keys are alphabetically sorted",
        difficulty: "semantic",
        topK: 10,
        description: "sort_all_objects — deep key-sorting of all nested Value::Object maps",
        expected_names: ["sort_all_objects"],
        expected_files: ["value/mod.rs"],
        heldOut: true,
    },
];
