/**
 * test/suites/spring.mjs
 *
 * Ground-truth query set for Spring PetClinic (Java / Spring, a subset of
 * spring-projects/spring-petclinic).
 *
 * NOTE on the symbol universe: this fixture indexes at class granularity — the
 * indexed `name` of each chunk is the Java type (Owner, OwnerController,
 * OwnerRepository, PetValidator, …) and there are no per-method chunks. So
 * expected_names here are the REAL class names from bench/_chunks/spring.json;
 * behavioural nl/xc queries describe what a class *does* and resolve to the
 * class that owns that behaviour. SCSS files contribute `*_rule_set` chunks.
 *
 * Key source layout:
 *   model/        BaseEntity (id), NamedEntity (name), Person (first/last name)
 *   owner/        Owner (entity + pets/visits), OwnerController (CRUD web forms),
 *                 OwnerRepository (Spring Data find-by-last-name), Pet, PetType,
 *                 PetController, PetValidator, PetTypeFormatter, PetTypeRepository,
 *                 Visit, VisitController
 *   vet/          Vet, Vets (XML list), VetController, VetRepository, Specialty
 *   system/       CacheConfiguration (JCache for vets), CrashController (throws),
 *                 WelcomeController (home page), WebConfiguration
 *   PetClinicApplication (boot main), PetClinicRuntimeHints (AOT/native hints)
 *   scss/         petclinic / header / responsive / typography rule sets
 */

export const META = {
    id: 'spring',
    displayName: 'Spring PetClinic',
    language: 'Java/Spring',
    version: 'subset',
    url: 'https://github.com/spring-projects/spring-petclinic',
    expectedMinChunks: 40,
    expectedMinFiles: 20,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'SP01',
        query: 'OwnerRepository',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Spring Data repository for Owner entities (find by last name, find by id)',
        expected_names: ['OwnerRepository'],
        expected_files: ['owner/OwnerRepository.java'],
    },
    {
        id: 'SP02',
        query: 'PetValidator',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Validator that checks a Pet form before saving',
        expected_names: ['PetValidator'],
        expected_files: ['owner/PetValidator.java'],
    },
    {
        id: 'SP03',
        query: 'CrashController',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Demo controller whose handler deliberately throws to showcase error handling',
        expected_names: ['CrashController'],
        expected_files: ['system/CrashController.java'],
    },

    // ── MEDIUM (keyword lookup with a bit of intent) ────────────────────────────

    {
        id: 'SP04',
        query: 'owner repository find by last name pageable',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Spring Data query method returning a page of owners whose last name starts with a prefix',
        expected_names: ['OwnerRepository'],
        expected_files: ['owner/OwnerRepository.java'],
    },
    {
        id: 'SP05',
        query: 'PetTypeFormatter parse print pet type',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Spring Formatter that converts between a PetType and its display name string',
        expected_names: ['PetTypeFormatter'],
        expected_files: ['owner/PetTypeFormatter.java'],
    },
    {
        id: 'SP06',
        query: 'vet controller list veterinarians paginated model',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Controller that lists veterinarians as an HTML page and as a JSON/XML resource',
        expected_names: ['VetController', 'Vets'],
        expected_files: ['vet/VetController.java', 'vet/Vets.java'],
    },

    // ── NL / SEMANTIC (behavioural — does NOT name the target symbol) ───────────

    {
        id: 'SP07',
        query: 'handle the web form submission that creates a new pet owner and saves it',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Seed case owner-create — the controller that processes the new-owner form',
        expected_names: ['OwnerController'],
        expected_files: ['owner/OwnerController.java'],
    },
    {
        id: 'SP08',
        query: 'reject the form when a pet is missing its name, type, or birth date',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Seed case pet-validate — validation rules applied to a pet before it is saved',
        expected_names: ['PetValidator'],
        expected_files: ['owner/PetValidator.java'],
    },
    {
        id: 'SP09',
        query: 'record a new appointment booking for a pet belonging to an owner',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Controller handling the visit (appointment) creation form for a pet',
        expected_names: ['VisitController', 'Visit'],
        expected_files: ['owner/VisitController.java', 'owner/Visit.java'],
    },

    // ── XC (cross-cutting concern phrased behaviourally) ────────────────────────

    {
        id: 'SP10',
        query: 'set up an in-memory cache so the veterinarian list is not recomputed on every request',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'JCache configuration that caches the vets listing',
        expected_names: ['CacheConfiguration'],
        expected_files: ['system/CacheConfiguration.java'],
    },
    {
        id: 'SP11',
        query: 'base persistent entity giving every domain object an auto-generated database id',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'Mapped superclass supplying the shared id primary key to all entities',
        expected_names: ['BaseEntity', 'NamedEntity'],
        expected_files: ['model/BaseEntity.java', 'model/NamedEntity.java'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking; ~25%) ───────────

    {
        id: 'HO-SP1',
        query: 'PetTypeRepository',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Repository that loads the available pet types',
        expected_names: ['PetTypeRepository'],
        expected_files: ['owner/PetTypeRepository.java'],
        heldOut: true,
    },
    {
        id: 'HO-SP2',
        query: 'render the application landing page at the site root',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Controller mapping the home page / welcome view',
        expected_names: ['WelcomeController'],
        expected_files: ['system/WelcomeController.java'],
        heldOut: true,
    },
    {
        id: 'HO-SP3',
        query: 'register reflection and serialization hints so the app runs as a GraalVM native image',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'AOT runtime-hints registrar for native-image builds',
        expected_names: ['PetClinicRuntimeHints'],
        expected_files: ['PetClinicRuntimeHints.java'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "SP12",
        query: "VetRepository",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Spring Data repository for Vet entities; findAll is cached under the 'vets' cache",
        expected_names: ["VetRepository"],
        expected_files: ["vet/VetRepository.java"],
    },
    {
        id: "SP13",
        query: "PetController",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Controller handling pet create/update forms nested under an owner",
        expected_names: ["PetController"],
        expected_files: ["owner/PetController.java"],
    },
    {
        id: "SP14",
        query: "Specialty vet specialty entity",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Named entity modelling a veterinarian specialty such as dentistry or surgery",
        expected_names: ["Specialty"],
        expected_files: ["vet/Specialty.java"],
    },
    {
        id: "SP15",
        query: "owner entity address city telephone pets list",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "JPA entity holding owner contact fields and the one-to-many collection of pets",
        expected_names: ["Owner"],
        expected_files: ["owner/Owner.java"],
    },
    {
        id: "SP16",
        query: "pet entity birth date type and visits one to many",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "JPA entity for a pet: birth date, pet type relation, and its visits",
        expected_names: ["Pet"],
        expected_files: ["owner/Pet.java"],
    },
    {
        id: "SP17",
        query: "pet type lookup query order by name find pet types",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Repository exposing the JPQL query that loads all pet types ordered by name",
        expected_names: ["PetTypeRepository"],
        expected_files: ["owner/PetTypeRepository.java"],
    },
    {
        id: "SP18",
        query: "paginate owners by last name prefix and either redirect or show the results list",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "Controller find-form flow: looks up owners by last-name prefix, redirects on single match, paginates on many",
        expected_names: ["OwnerController"],
        expected_files: ["owner/OwnerController.java"],
    },
    {
        id: "SP19",
        query: "block a duplicate pet name and reject a future birth date before saving the pet",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Pet create/update handler that rejects duplicate names and future birth dates",
        expected_names: ["PetController"],
        expected_files: ["owner/PetController.java"],
    },
    {
        id: "SP20",
        query: "let users switch the UI language through a query parameter and remember it in the session",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Internationalization config: locale resolver plus lang-param change interceptor",
        expected_names: ["WebConfiguration"],
        expected_files: ["system/WebConfiguration.java"],
    },
    {
        id: "SP21",
        query: "convert a typed pet type to and from its display name string for form binding",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Spring Formatter that parses and prints a PetType (re-targets PetTypeFormatter behaviourally)",
        expected_names: ["PetTypeFormatter"],
        expected_files: ["owner/PetTypeFormatter.java"],
    },
    {
        id: "SP22",
        query: "shared mapped superclasses giving entities an id and a validated name field",
        kind: "xc",
        difficulty: "semantic",
        topK: 10,
        description: "Cross-cutting persistence base layer: id superclass plus the name-adding superclass",
        expected_names: ["BaseEntity","NamedEntity"],
        expected_files: ["model/BaseEntity.java","model/NamedEntity.java"],
    },
    {
        id: "SP23",
        query: "expose the veterinarian list as both an HTML page and a JSON/XML resource",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Vet listing controller returning both a paginated view and a @ResponseBody Vets payload",
        expected_names: ["VetController","Vets"],
        expected_files: ["vet/VetController.java","vet/Vets.java"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-SP4",
        query: "VetController",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Controller listing veterinarians (HTML view + resource endpoint)",
        expected_names: ["VetController"],
        expected_files: ["vet/VetController.java"],
        heldOut: true,
    },
    {
        id: "HO-SP5",
        query: "WebConfiguration",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "MVC configuration wiring i18n locale resolution and the lang interceptor",
        expected_names: ["WebConfiguration"],
        expected_files: ["system/WebConfiguration.java"],
        heldOut: true,
    },
    {
        id: "HO-SP6",
        query: "Vet entity",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Veterinarian JPA entity with a many-to-many set of specialties",
        expected_names: ["Vet"],
        expected_files: ["vet/Vet.java"],
        heldOut: true,
    },
    {
        id: "HO-SP7",
        query: "PetClinicApplication",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Spring Boot application entrypoint with the main method",
        expected_names: ["PetClinicApplication"],
        expected_files: ["PetClinicApplication.java"],
        heldOut: true,
    },
    {
        id: "HO-SP8",
        query: "visit entity appointment date and description",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "JPA entity for a clinic visit holding the date and a required description",
        expected_names: ["Visit"],
        expected_files: ["owner/Visit.java"],
        heldOut: true,
    },
    {
        id: "HO-SP9",
        query: "pet type entity cat dog hamster",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Named entity for a kind of pet (cat, dog, hamster)",
        expected_names: ["PetType"],
        expected_files: ["owner/PetType.java"],
        heldOut: true,
    },
    {
        id: "HO-SP10",
        query: "vet repository cacheable findAll transactional read only",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Repository whose findAll is annotated Cacheable('vets') and read-only transactional",
        expected_names: ["VetRepository"],
        expected_files: ["vet/VetRepository.java"],
        heldOut: true,
    },
    {
        id: "HO-SP11",
        query: "store an owner's pet collection and look up a pet by id or by name",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "Owner entity behaviour: holds pets and resolves a pet by id/name (behavioural, re-targets Owner)",
        expected_names: ["Owner"],
        expected_files: ["owner/Owner.java"],
        heldOut: true,
    },
    {
        id: "HO-SP12",
        query: "book a new appointment for a pet and ensure the visit date is in the future",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Controller that loads a pet, builds a Visit, and rejects non-future visit dates",
        expected_names: ["VisitController"],
        expected_files: ["owner/VisitController.java"],
        heldOut: true,
    },
    {
        id: "HO-SP13",
        query: "where is the shared first name and last name defined for owners and vets",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Mapped superclass supplying firstName/lastName to Owner and Vet",
        expected_names: ["Person"],
        expected_files: ["model/Person.java"],
        heldOut: true,
    },
    {
        id: "HO-SP14",
        query: "deliberately throw an exception to demonstrate the error page",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Demo handler that throws a RuntimeException to showcase error handling (re-targets CrashController behaviourally)",
        expected_names: ["CrashController"],
        expected_files: ["system/CrashController.java"],
        heldOut: true,
    },
    {
        id: "HO-SP15",
        query: "enforce that a pet has a name, a type, and a birth date before it can be saved",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Hand-written validator rejecting pets missing name/type/birthDate (re-targets PetValidator behaviourally)",
        expected_names: ["PetValidator"],
        expected_files: ["owner/PetValidator.java"],
        heldOut: true,
    },
    {
        id: "HO-SP16",
        query: "check that every UI string is internationalized and translated in all language bundles",
        kind: "xc",
        difficulty: "semantic",
        topK: 10,
        description: "Test that scans HTML for hard-coded strings and verifies message bundle parity across languages",
        expected_names: ["I18nPropertiesSyncTest"],
        expected_files: ["system/I18nPropertiesSyncTest.java"],
        heldOut: true,
    },
    {
        id: "HO-SP17",
        query: "look up an entity from a collection by its id and class throwing if not found",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Test helper generic getById over a collection of BaseEntity, raising ObjectRetrievalFailureException",
        expected_names: ["EntityUtils"],
        expected_files: ["service/EntityUtils.java"],
        heldOut: true,
    },
    {
        id: "HO-SP18",
        query: "spin up a MySQL Testcontainer and run the app against it",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Test configuration providing a MySQLContainer service-connection bean and a mysql-profile main",
        expected_names: ["MysqlTestApplication","MySqlIntegrationTests"],
        expected_files: ["MysqlTestApplication.java","MySqlIntegrationTests.java"],
        heldOut: true,
    },
    {
        id: "HO-SP19",
        query: "model a veterinarian's specialties as a many to many relationship",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Vet entity owning the many-to-many specialties join plus the Specialty entity it links to",
        expected_names: ["Vet","Specialty"],
        expected_files: ["vet/Vet.java","vet/Specialty.java"],
        heldOut: true,
    },
];
