/**
 * test/suites/alamofire.mjs
 *
 * Ground-truth query set for Alamofire (Swift, subset).
 * Source: https://github.com/Alamofire/Alamofire
 *
 * Every expected_name below is a REAL indexed symbol drawn from
 * bench/_chunks/alamofire.json (whole name or a real class_context).
 *
 * Key source layout (under Core/, Features/, Extensions/):
 *   Core/Session.swift            — class Session (creates/manages requests, adapters,
 *                                     retries, SessionDelegate), request(), cancelAllRequests
 *   Core/Request.swift            — class Request (state machine: resume/suspend/cancel,
 *                                     task lifecycle, retry, finish), RequestDelegate
 *   Core/DataRequest.swift        — class DataRequest, response*, validate
 *   Core/DownloadRequest.swift    — class DownloadRequest, suggestedDownloadDestination
 *   Core/HTTPHeaders.swift        — struct HTTPHeaders / HTTPHeader (ordered header pairs)
 *   Core/HTTPMethod.swift         — struct HTTPMethod (GET/POST/...)
 *   Core/ParameterEncoding.swift  — protocol ParameterEncoding, URLEncoding, JSONEncoding
 *   Core/AFError.swift            — enum AFError + nested failure reasons
 *   Features/Validation.swift     — validate(statusCode:)/validate(contentType:)
 *   Features/RetryPolicy.swift    — class RetryPolicy / ConnectionLostRetryPolicy
 *   Features/MultipartFormData.swift — class MultipartFormData, append(...)
 *   Features/ServerTrustEvaluation.swift — ServerTrustEvaluating, PinnedCertificatesTrustEvaluator
 *   Features/NetworkReachabilityManager.swift — startListening / stopListening / status
 *   Features/RedirectHandler.swift — RedirectHandler / Redirector
 *   Features/CachedResponseHandler.swift — CachedResponseHandler / ResponseCacher
 *   Features/AuthenticationInterceptor.swift — AuthenticationInterceptor, Authenticator
 */

export const META = {
    id: 'alamofire',
    displayName: 'Alamofire (subset)',
    language: 'Swift',
    version: 'subset',
    url: 'https://github.com/Alamofire/Alamofire',
    expectedMinChunks: 200,
    expectedMinFiles: 20,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'AF01',
        query: 'HTTPHeaders',
        difficulty: 'easy',
        topK: 5,
        description: 'HTTPHeaders / HTTPHeader — ordered collection of HTTP header name/value pairs',
        expected_names: ['HTTPHeaders', 'HTTPHeader'],
        expected_files: ['HTTPHeaders'],
    },
    {
        id: 'AF02',
        query: 'HTTPMethod',
        difficulty: 'easy',
        topK: 5,
        description: 'HTTPMethod — wrapper for GET/POST/PUT/DELETE verbs',
        expected_names: ['HTTPMethod'],
        expected_files: ['HTTPMethod'],
    },
    {
        id: 'AF03',
        query: 'AFError',
        difficulty: 'easy',
        topK: 5,
        description: 'AFError — the framework error type with nested failure reasons',
        expected_names: ['AFError'],
        expected_files: ['AFError'],
    },

    // ── MEDIUM (keyword lookup of a concrete API) ───────────────────────────────

    {
        id: 'AF04',
        query: 'request state resume suspend cancel task',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Request — the request state machine driving the URLSession task lifecycle',
        expected_names: ['Request'],
        expected_files: ['Core/Request'],
    },
    {
        id: 'AF05',
        query: 'session manager create request adapter retry delegate',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Session — creates and manages requests with interceptors, retries and a delegate',
        expected_names: ['Session'],
        expected_files: ['Core/Session'],
    },
    {
        id: 'AF06',
        query: 'parameter encoding url query json body',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'ParameterEncoding family — encode request parameters as URL query or JSON body',
        expected_names: ['ParameterEncoding', 'URLEncoding', 'JSONEncoding'],
        expected_files: ['ParameterEncoding'],
    },
    {
        id: 'AF07',
        query: 'response validation acceptable status code content type',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'validate() — checks the response status code and content type are acceptable',
        expected_names: ['validate'],
        expected_files: ['Validation'],
    },

    // ── HARD (cross-cutting, phrased behaviourally) ─────────────────────────────

    {
        id: 'AF08',
        query: 'retry a failed network request after a delay with exponential backoff up to a limit',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'RetryPolicy — retrier that re-attempts idempotent requests with backoff',
        expected_names: ['RetryPolicy', 'ConnectionLostRetryPolicy'],
        expected_files: ['RetryPolicy'],
    },
    {
        id: 'AF09',
        query: 'build a multipart form body appending file data with a boundary for upload',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'MultipartFormData — assembles a multipart/form-data body from parts',
        expected_names: ['MultipartFormData', 'BodyPart'],
        expected_files: ['MultipartFormData'],
    },

    // ── SEMANTIC (natural-language intent; target NOT named) ────────────────────

    {
        id: 'AF10',
        query: 'pin a server certificate and reject the connection when the TLS chain does not match',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Pinned-certificate server trust evaluation for TLS pinning',
        expected_names: ['PinnedCertificatesTrustEvaluator', 'ServerTrustEvaluating'],
        expected_files: ['ServerTrustEvaluation'],
    },
    {
        id: 'AF11',
        query: 'watch whether the device currently has an internet connection and notify when it changes',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Network reachability monitoring — start/stop listening for connectivity changes',
        expected_names: ['NetworkReachabilityManager', 'startListening', 'NetworkReachabilityStatus'],
        expected_files: ['NetworkReachabilityManager'],
    },
    {
        id: 'AF12',
        query: 'decide whether a redirect response should be followed or rewritten before continuing',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Redirect handling policy applied when the server responds with a redirect',
        expected_names: ['RedirectHandler', 'Redirector'],
        expected_files: ['RedirectHandler'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    {
        id: 'HO-AF1',
        query: 'OfflineRetrier',
        difficulty: 'easy',
        topK: 5,
        description: 'OfflineRetrier — retrier that waits for connectivity before retrying',
        expected_names: ['OfflineRetrier'],
        expected_files: ['OfflineRetrier'],
        heldOut: true,
    },
    {
        id: 'HO-AF2',
        query: 'attach an OAuth credential to outgoing requests and refresh it when it expires',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Authentication interceptor that adapts requests with a credential and refreshes on expiry',
        expected_names: ['AuthenticationInterceptor', 'Authenticator'],
        expected_files: ['AuthenticationInterceptor'],
        heldOut: true,
    },
    {
        id: 'HO-AF3',
        query: 'customize the cached response stored for a request or prevent it from being cached',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Cached response handling — mutate or drop the URLCache entry for a response',
        expected_names: ['CachedResponseHandler', 'ResponseCacher'],
        expected_files: ['CachedResponseHandler'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "AF13",
        query: "UploadRequest",
        difficulty: "easy",
        topK: 5,
        description: "UploadRequest - DataRequest subclass that uploads a body (data/file/stream/multipart)",
        expected_names: ["UploadRequest"],
        expected_files: ["Core/UploadRequest"],
    },
    {
        id: "AF14",
        query: "Interceptor",
        difficulty: "easy",
        topK: 5,
        description: "Interceptor - composes RequestAdapters and RequestRetriers into one RequestInterceptor",
        expected_names: ["Interceptor"],
        expected_files: ["RequestInterceptor"],
    },
    {
        id: "AF15",
        query: "ServerTrustManager",
        difficulty: "easy",
        topK: 5,
        description: "ServerTrustManager - maps hosts to ServerTrustEvaluating policies",
        expected_names: ["ServerTrustManager"],
        expected_files: ["ServerTrustEvaluation"],
    },
    {
        id: "AF16",
        query: "request adapter retrier protocol adapt retry",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "RequestAdapter / RequestRetrier / RequestInterceptor protocols - adapt outgoing requests and decide retries",
        expected_names: ["RequestAdapter","RequestRetrier","RequestInterceptor"],
        expected_files: ["RequestInterceptor"],
    },
    {
        id: "AF17",
        query: "decode response body into Decodable model JSON string serializer",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "ResponseSerializer family that turns response Data into typed values",
        expected_names: ["DecodableResponseSerializer","JSONResponseSerializer","StringResponseSerializer","DataResponseSerializer"],
        expected_files: ["ResponseSerialization"],
    },
    {
        id: "AF18",
        query: "thread-safe wrapper guarding mutable state with a lock",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Protected<Value> - property-wrapper-like lock-guarded access to shared mutable state",
        expected_names: ["Protected"],
        expected_files: ["Core/Protected"],
    },
    {
        id: "AF19",
        query: "encode Swift parameters into a URL-encoded form body",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "URLEncodedFormEncoder - encodes Encodable values into application/x-www-form-urlencoded",
        expected_names: ["URLEncodedFormEncoder"],
        expected_files: ["URLEncodedFormEncoder"],
    },
    {
        id: "AF20",
        query: "compress an outgoing request body with deflate content-encoding before sending",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "DeflateRequestCompressor - adapter that gzips/deflates the body and sets Content-Encoding",
        expected_names: ["DeflateRequestCompressor"],
        expected_files: ["RequestCompression"],
    },
    {
        id: "AF21",
        query: "observe every stage of a request lifecycle for logging and metrics",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "EventMonitor protocol and composite/closure implementations that receive request lifecycle callbacks",
        expected_names: ["EventMonitor","CompositeEventMonitor","ClosureEventMonitor"],
        expected_files: ["EventMonitor"],
    },
    {
        id: "AF22",
        query: "cancel every in-flight request the session is currently running",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "cancelAllRequests on Session - stops all active requests",
        expected_names: ["cancelAllRequests"],
        expected_files: ["Core/Session"],
    },
    {
        id: "AF23",
        query: "URLConvertible URLRequestConvertible",
        difficulty: "easy",
        topK: 5,
        description: "URLConvertible / URLRequestConvertible - protocols turning a value into a URL or URLRequest",
        expected_names: ["URLConvertible","URLRequestConvertible"],
        expected_files: ["URLConvertible+URLRequestConvertible"],
    },
    {
        id: "AF24",
        query: "preprocess raw response data before serialization stripping XSSI prefix",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "DataPreprocessor implementations - PassthroughPreprocessor and GoogleXSSIPreprocessor clean response data pre-serialization",
        expected_names: ["DataPreprocessor","GoogleXSSIPreprocessor","PassthroughPreprocessor"],
        expected_files: ["ResponseSerialization"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-AF4",
        query: "DownloadRequest",
        difficulty: "easy",
        topK: 5,
        description: "DownloadRequest - Request subclass that streams the response to a file on disk",
        expected_names: ["DownloadRequest"],
        expected_files: ["Core/DownloadRequest"],
        heldOut: true,
    },
    {
        id: "HO-AF5",
        query: "DataStreamRequest",
        difficulty: "easy",
        topK: 5,
        description: "DataStreamRequest - Request that delivers the response body incrementally as a stream",
        expected_names: ["DataStreamRequest"],
        expected_files: ["Core/DataStreamRequest"],
        heldOut: true,
    },
    {
        id: "HO-AF6",
        query: "SessionDelegate",
        difficulty: "easy",
        topK: 5,
        description: "SessionDelegate - URLSession delegate bridging URLSession callbacks to Requests",
        expected_names: ["SessionDelegate"],
        expected_files: ["Core/SessionDelegate"],
        heldOut: true,
    },
    {
        id: "HO-AF7",
        query: "WebSocketRequest",
        difficulty: "easy",
        topK: 5,
        description: "WebSocketRequest - Request subclass driving a URLSessionWebSocketTask",
        expected_names: ["WebSocketRequest"],
        expected_files: ["Core/WebSocketRequest"],
        heldOut: true,
    },
    {
        id: "HO-AF8",
        query: "ParameterEncoder JSONParameterEncoder",
        difficulty: "easy",
        topK: 5,
        description: "ParameterEncoder protocol and JSONParameterEncoder/URLEncodedFormParameterEncoder implementations",
        expected_names: ["ParameterEncoder","JSONParameterEncoder","URLEncodedFormParameterEncoder"],
        expected_files: ["Core/ParameterEncoder"],
        heldOut: true,
    },
    {
        id: "HO-AF9",
        query: "private lock primitive wrapping os_unfair_lock",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "UnfairLock / Lock - low-level mutual-exclusion primitive backing Protected",
        expected_names: ["UnfairLock","Lock"],
        expected_files: ["Core/Protected"],
        heldOut: true,
    },
    {
        id: "HO-AF10",
        query: "structured concurrency async await wrapper around a request",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "DataTask / DownloadTask - async/await value wrappers for awaiting a request's result",
        expected_names: ["DataTask","DownloadTask"],
        expected_files: ["Concurrency"],
        heldOut: true,
    },
    {
        id: "HO-AF11",
        query: "result type returned by a retrier telling the session whether and when to retry",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "RetryResult - enum a RequestRetrier returns (retry / retryWithDelay / doNotRetry)",
        expected_names: ["RetryResult"],
        expected_files: ["RequestInterceptor"],
        heldOut: true,
    },
    {
        id: "HO-AF12",
        query: "trust evaluator that validates the default system certificate chain",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "DefaultTrustEvaluator and related ServerTrustEvaluating implementations for standard chain validation",
        expected_names: ["DefaultTrustEvaluator","RevocationTrustEvaluator","PublicKeysTrustEvaluator"],
        expected_files: ["ServerTrustEvaluation"],
        heldOut: true,
    },
    {
        id: "HO-AF13",
        query: "track which URLSession task belongs to which request in a bidirectional map",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "RequestTaskMap - two-way mapping between Requests and their URLSessionTasks",
        expected_names: ["RequestTaskMap"],
        expected_files: ["Core/RequestTaskMap"],
        heldOut: true,
    },
    {
        id: "HO-AF14",
        query: "assemble a multipart upload writing parts to a temp file when the body is too large for memory",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "MultipartUpload - builds the multipart body, streaming to disk past a memory threshold",
        expected_names: ["MultipartUpload"],
        expected_files: ["MultipartUpload"],
        heldOut: true,
    },
    {
        id: "HO-AF15",
        query: "send a ping over an open websocket and keep the connection alive automatically",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "WebSocket keep-alive ping behavior - sendPing and startAutomaticPing on WebSocketRequest",
        expected_names: ["sendPing","startAutomaticPing"],
        expected_files: ["Core/WebSocketRequest"],
        heldOut: true,
    },
    {
        id: "HO-AF16",
        query: "generate a curl command string equivalent of a request for debugging",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "cURLDescription - renders a Request as an equivalent curl command",
        expected_names: ["cURLDescription"],
        expected_files: ["Core/Request"],
        heldOut: true,
    },
    {
        id: "HO-AF17",
        query: "where the response is downloaded to on disk and how an existing file is handled",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "suggestedDownloadDestination - builds the on-disk destination and overwrite/createIntermediate options",
        expected_names: ["suggestedDownloadDestination"],
        expected_files: ["Core/DownloadRequest"],
        heldOut: true,
    },
    {
        id: "HO-AF18",
        query: "run a request through its adapters then attempt to retry it on failure",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Request's adapt/retry/retryOrFinish/prepareForRetry path through the interceptor pipeline",
        expected_names: ["adapt","retry","retryOrFinish","prepareForRetry"],
        expected_files: ["Core/Request"],
        heldOut: true,
    },
    {
        id: "HO-AF19",
        query: "drive the request state machine between resumed suspended and cancelled",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Request lifecycle controls - resume/suspend/cancel/finish transitions on the URLSession task",
        expected_names: ["resume","suspend","cancel","finish"],
        expected_files: ["Core/Request"],
        heldOut: true,
    },
    {
        id: "HO-AF20",
        query: "Adapter Retrier",
        difficulty: "easy",
        topK: 5,
        description: "Adapter / Retrier - closure-backed concrete RequestAdapter and RequestRetrier wrappers",
        expected_names: ["Adapter","Retrier"],
        expected_files: ["RequestInterceptor"],
        heldOut: true,
    },
];
