/**
 * test/suites/android.mjs
 *
 * Ground-truth query set for the Android "Sunflower" sample (Kotlin), a subset
 * of github.com/android/sunflower.
 * Source: https://github.com/android/sunflower
 *
 * Key source layout (under com/google/samples/apps/sunflower/):
 *   data/
 *     Plant.kt                      — @Entity data class Plant, shouldBeWatered()
 *     GardenPlanting.kt             — @Entity recording a plant added to the garden
 *     PlantDao.kt                   — Room DAO: getPlants / getPlant / upsertAll
 *     GardenPlantingDao.kt          — Room DAO for garden plantings
 *     PlantRepository.kt            — repository over PlantDao
 *     GardenPlantingRepository.kt   — create/remove garden plantings, isPlanted
 *     UnsplashRepository.kt         — paged Unsplash photo search
 *     UnsplashPagingSource.kt       — PagingSource that loads photo pages
 *     Converters.kt                 — Room TypeConverters (Calendar <-> Long)
 *     AppDatabase.kt                — abstract RoomDatabase, getInstance
 *   api/UnsplashService.kt          — Retrofit interface, searchPhotos
 *   di/ NetworkModule.kt, DatabaseModule.kt — Hilt @Module providers
 *   viewmodels/
 *     PlantListViewModel.kt         — plant list + grow-zone filter
 *     PlantDetailViewModel.kt       — single plant + add-to-garden action
 *     GalleryViewModel.kt           — paged Unsplash gallery
 *   workers/SeedDatabaseWorker.kt   — CoroutineWorker seeding the DB from JSON
 *   utilities/GrowZoneUtil.kt       — getZoneForLatitude helper
 *   compose/ ...                    — Jetpack Compose screens (@Composable funcs,
 *                                      indexed as <File>_function_declaration)
 *
 * NOTE: top-level / @Composable functions are indexed under the synthetic name
 * "<FileBaseName>_function_declaration" (e.g. GrowZoneUtil_function_declaration),
 * so those are the real symbol names used in expected_names below.
 */

export const META = {
    id: 'android',
    displayName: 'Android Sunflower',
    language: 'Kotlin/Android',
    version: 'subset',
    url: 'https://github.com/android/sunflower',
    expectedMinChunks: 60,
    expectedMinFiles: 30,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'AN01',
        query: 'GardenPlantingRepository',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Repository that creates and removes garden plantings via the DAO',
        expected_names: ['GardenPlantingRepository'],
        expected_files: ['GardenPlantingRepository.kt'],
    },
    {
        id: 'AN02',
        query: 'PlantDao',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Room Data Access Object for the Plant entity',
        expected_names: ['PlantDao'],
        expected_files: ['PlantDao.kt'],
    },
    {
        id: 'AN03',
        query: 'AppDatabase Room database',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'The abstract Room database holding the DAOs',
        expected_names: ['AppDatabase'],
        expected_files: ['AppDatabase.kt'],
    },

    // ── MEDIUM (keyword lookup) ─────────────────────────────────────────────────

    {
        id: 'AN04',
        query: 'garden planting repository dao insert',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Seed case: garden planting repository over the DAO',
        expected_names: ['GardenPlantingRepository'],
        expected_files: ['GardenPlantingRepository.kt'],
    },
    {
        id: 'AN05',
        query: 'unsplash service retrofit search photos http',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Retrofit network interface calling the Unsplash photo search endpoint',
        expected_names: ['UnsplashService'],
        expected_files: ['api/UnsplashService.kt'],
    },
    {
        id: 'AN06',
        query: 'room type converter calendar timestamp',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Room TypeConverters mapping Calendar to a stored Long timestamp',
        expected_names: ['Converters'],
        expected_files: ['Converters.kt'],
    },

    // ── HARD (cross-cutting, phrased behaviourally) ─────────────────────────────

    {
        id: 'AN07',
        query: 'screen state for a single plant with an add-to-garden action',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Seed case: detail view model exposing a plant and an add-to-garden action',
        expected_names: ['PlantDetailViewModel'],
        expected_files: ['viewmodels/PlantDetailViewModel.kt'],
    },
    {
        id: 'AN08',
        query: 'load pages of remote images for an infinitely scrolling photo grid',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'PagingSource that fetches successive pages of Unsplash photos',
        expected_names: ['UnsplashPagingSource'],
        expected_files: ['data/UnsplashPagingSource.kt'],
    },

    // ── SEMANTIC (natural-language behaviour, target name NOT mentioned) ────────

    {
        id: 'AN09',
        query: 'view model exposing the list of plants and the grow-zone filter',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Seed case: list view model with the grow-zone filter',
        expected_names: ['PlantListViewModel'],
        expected_files: ['viewmodels/PlantListViewModel.kt'],
    },
    {
        id: 'AN10',
        query: 'background job that reads plant records from a bundled JSON file and writes them into the local database on first launch',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'CoroutineWorker that seeds the database from a JSON asset',
        expected_names: ['SeedDatabaseWorker'],
        expected_files: ['workers/SeedDatabaseWorker.kt'],
    },
    {
        id: 'AN11',
        query: 'work out which hardiness zone a location belongs to from its latitude',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Helper mapping a latitude to a plant growing zone',
        expected_names: ['GrowZoneUtil_function_declaration'],
        expected_files: ['utilities/GrowZoneUtil.kt'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──

    {
        id: 'HO-AN1',
        query: 'PlantRepository',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Repository wrapping the Plant DAO',
        expected_names: ['PlantRepository'],
        expected_files: ['PlantRepository.kt'],
        heldOut: true,
    },
    {
        id: 'HO-AN2',
        query: 'decide whether a plant is overdue to be watered based on its watering interval',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Held-out: the Plant entity carrying the should-be-watered logic',
        expected_names: ['Plant'],
        expected_files: ['data/Plant.kt'],
        heldOut: true,
    },
    {
        id: 'HO-AN3',
        query: 'dependency-injection module that provides the configured network client',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Held-out: Hilt module providing the Unsplash network service',
        expected_names: ['NetworkModule'],
        expected_files: ['di/NetworkModule.kt'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "AN12",
        query: "GalleryViewModel",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "View model exposing the paged Unsplash photo stream for the gallery",
        expected_names: ["GalleryViewModel"],
        expected_files: ["viewmodels/GalleryViewModel.kt"],
    },
    {
        id: "AN13",
        query: "GardenPlantingDao",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Room DAO for garden plantings (insert/delete/isPlanted/getPlantedGardens)",
        expected_names: ["GardenPlantingDao"],
        expected_files: ["data/GardenPlantingDao.kt"],
    },
    {
        id: "AN14",
        query: "unsplash repository pager paging stream photo search",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Repository building a Pager flow of Unsplash photos for a query",
        expected_names: ["UnsplashRepository"],
        expected_files: ["data/UnsplashRepository.kt"],
    },
    {
        id: "AN15",
        query: "single host activity that sets the Compose content and enables edge-to-edge",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "The ComponentActivity entry point that hosts the Compose UI tree",
        expected_names: ["GardenActivity"],
        expected_files: ["GardenActivity.kt"],
    },
    {
        id: "AN16",
        query: "application subclass that bootstraps dependency injection and supplies the WorkManager configuration",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Hilt Application class providing the WorkManager Configuration",
        expected_names: ["MainApplication"],
        expected_files: ["MainApplication.kt"],
    },
    {
        id: "AN17",
        query: "dependency-injection module that builds the Room database and provides the DAOs",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Hilt module providing AppDatabase, PlantDao and GardenPlantingDao",
        expected_names: ["DatabaseModule"],
        expected_files: ["di/DatabaseModule.kt"],
    },
    {
        id: "AN18",
        query: "view model streaming the planted plants in the user's garden as state",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "View model exposing the StateFlow of plant-and-garden-planting rows",
        expected_names: ["GardenPlantingListViewModel"],
        expected_files: ["viewmodels/GardenPlantingListViewModel.kt"],
    },
    {
        id: "AN19",
        query: "unsplash photo response model id urls user",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Data class for a single Unsplash photo from the API",
        expected_names: ["UnsplashPhoto"],
        expected_files: ["data/UnsplashPhoto.kt"],
    },
    {
        id: "AN20",
        query: "sealed type enumerating navigation destinations and their route arguments",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Sealed Screen class defining Home/PlantDetail/Gallery nav routes",
        expected_names: ["Screen"],
        expected_files: ["compose/Screen.kt"],
    },
    {
        id: "AN21",
        query: "root composable wiring the navigation host and start destination",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Top-level composable setting up the NavHost between screens",
        expected_names: ["SunflowerApp_function_declaration"],
        expected_files: ["compose/SunflowerApp.kt"],
    },
    {
        id: "AN22",
        query: "presentation wrapper formatting a planting's watering and planted dates for display",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "View model adapting a PlantAndGardenPlantings into formatted date strings",
        expected_names: ["PlantAndGardenPlantingsViewModel"],
        expected_files: ["viewmodels/PlantAndGardenPlantingsViewModel.kt"],
    },
    {
        id: "AN23",
        query: "grid screen rendering the paged photo results with pull-to-refresh",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Composable gallery screen showing the lazy photo grid",
        expected_names: ["GalleryScreen_function_declaration"],
        expected_files: ["compose/gallery/GalleryScreen.kt"],
    },
    {
        id: "AN24",
        query: "Room data access objects defining the SQL queries for plants and garden plantings",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Cross-cutting: both Room DAO interfaces (Plant and GardenPlanting)",
        expected_names: ["PlantDao","GardenPlantingDao"],
        expected_files: ["data/PlantDao.kt","data/GardenPlantingDao.kt"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-AN4",
        query: "GardenPlanting entity",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: Room @Entity recording a plant added to the garden with watering/plant dates",
        expected_names: ["GardenPlanting"],
        expected_files: ["data/GardenPlanting.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN5",
        query: "relation joining a plant with its garden plantings for Room",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: data class capturing the Plant-to-GardenPlanting relationship",
        expected_names: ["PlantAndGardenPlantings"],
        expected_files: ["data/PlantAndGardenPlantings.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN6",
        query: "UnsplashUser",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: data class for an Unsplash photographer with an attribution URL",
        expected_names: ["UnsplashUser"],
        expected_files: ["data/UnsplashUser.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN7",
        query: "UnsplashPhotoUrls",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: data class holding the available image URLs for an Unsplash photo",
        expected_names: ["UnsplashPhotoUrls"],
        expected_files: ["data/UnsplashPhotoUrls.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN8",
        query: "model wrapping the paginated photo search results and total page count",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: data class for the Unsplash search-photos API response",
        expected_names: ["UnsplashSearchResponse"],
        expected_files: ["data/UnsplashSearchResponse.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN9",
        query: "layout modifier that hides an element while keeping its space reserved",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: custom Compose visible/invisible LayoutModifier",
        expected_names: ["VisibleModifier"],
        expected_files: ["compose/Modifiers.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN10",
        query: "centralized compose padding and dimension constants",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: object capturing padding/toolbar dimens used across Compose code",
        expected_names: ["Dimens"],
        expected_files: ["compose/Dimens.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN11",
        query: "derived state deciding whether the collapsing toolbar should be shown while scrolling",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: scroller state class computing toolbar visibility from scroll position",
        expected_names: ["PlantDetailsScroller"],
        expected_files: ["compose/plantdetail/PlantDetailScroller.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN12",
        query: "enum of the two home tabs my garden and plant list with title and icon",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: SunflowerPage enum backing the home pager tabs",
        expected_names: ["SunflowerPage"],
        expected_files: ["compose/home/HomeScreen.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN13",
        query: "top-level screen with a tabbed pager swiping between the garden and the plant list",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: Home composable with the horizontal pager and tab row",
        expected_names: ["HomeScreen_function_declaration"],
        expected_files: ["compose/home/HomeScreen.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN14",
        query: "screen listing all available plants the user can browse",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: composable rendering the full plant catalog list",
        expected_names: ["PlantListScreen_function_declaration"],
        expected_files: ["compose/plantlist/PlantListScreen.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN15",
        query: "reusable card showing a plant thumbnail image and name in a list",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: list-item composable for a single plant/photo card",
        expected_names: ["PlantListItemView_function_declaration"],
        expected_files: ["compose/plantlist/PlantListItemView.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN16",
        query: "detail screen showing one plant's image description and add-to-garden button",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: composable rendering the full plant detail view",
        expected_names: ["PlantDetailView_function_declaration"],
        expected_files: ["compose/plantdetail/PlantDetailView.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN17",
        query: "wrapper that overlays a transient snackbar message over its content",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: composable displaying a text snackbar over wrapped content",
        expected_names: ["TextSnackbarContainer_function_declaration"],
        expected_files: ["compose/utils/TextSnackbarContainer.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN18",
        query: "screen showing the planted garden as a grid or an empty-state prompt to add plants",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: garden composable rendering the planted grid or empty garden",
        expected_names: ["GardenScreen_function_declaration"],
        expected_files: ["compose/garden/GardenScreen.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN19",
        query: "app-wide Material theme wrapper applying color scheme and typography",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: SunflowerTheme composable wrapping content in the app theme",
        expected_names: ["Theme_function_declaration"],
        expected_files: ["ui/Theme.kt"],
        heldOut: true,
    },
    {
        id: "HO-AN20",
        query: "aggregated set of UI click handlers passed through the plant detail composables",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: data class bundling fab/back/share/gallery callbacks for plant detail",
        expected_names: ["PlantDetailsCallbacks"],
        expected_files: ["compose/plantdetail/PlantDetailView.kt"],
        heldOut: true,
    },
];
