/**
 * test/suites/aspnet.mjs
 *
 * Ground-truth query set for eShopOnWeb (C# / ASP.NET Core).
 * Source: https://github.com/dotnet-architecture/eShopOnWeb (subset)
 *
 * Clean-architecture layout (the parts indexed in this fixture):
 *   ApplicationCore/
 *     Entities/        — domain aggregates: Basket, Order, CatalogItem, Buyer, ...
 *     Services/        — BasketService, OrderService, UriComposer
 *     Specifications/  — Ardalis.Specification query objects (filter/paging)
 *     Interfaces/      — IBasketService, IOrderService, IRepository, ...
 *   Infrastructure/
 *     Data/            — EfRepository<T> (EF Core repository), CatalogContext
 *     Identity/        — IdentityTokenClaimService (JWT), ApplicationUser
 *     Services/        — EmailSender
 *   PublicApi/
 *     *Endpoints/      — minimal-API endpoints (Create/Update/Delete/List catalog)
 *     Middleware/      — ExceptionMiddleware (global error handler)
 *   Web/
 *     Services/        — CatalogViewModelService, CachedCatalogViewModelService
 *     wwwroot/css/     — component stylesheets (rule_set chunks)
 */

export const META = {
    id: 'aspnet',
    displayName: 'eShopOnWeb (ASP.NET Core)',
    language: 'C#/ASP.NET',
    version: 'subset',
    url: 'https://github.com/dotnet-architecture/eShopOnWeb',
    expectedMinChunks: 200,
    expectedMinFiles: 120,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'AN01',
        query: 'BasketService',
        difficulty: 'easy',
        topK: 5,
        description: 'Application service for basket operations (add item, set quantities, transfer, delete)',
        expected_names: ['BasketService', 'IBasketService'],
        expected_files: ['ApplicationCore/Services/BasketService.cs'],
    },
    {
        id: 'AN02',
        query: 'EfRepository entity framework repository',
        difficulty: 'easy',
        topK: 5,
        description: 'Generic EF Core repository implementing the read/write repository interfaces',
        expected_names: ['EfRepository'],
        expected_files: ['Infrastructure/Data/EfRepository.cs'],
    },
    {
        id: 'AN03',
        query: 'ExceptionMiddleware error handler',
        difficulty: 'easy',
        topK: 5,
        description: 'ASP.NET middleware that catches unhandled exceptions and writes a JSON error response',
        expected_names: ['ExceptionMiddleware'],
        expected_files: ['PublicApi/Middleware/ExceptionMiddleware.cs'],
    },

    // ── MEDIUM (keyword lookup) ─────────────────────────────────────────────────

    {
        id: 'AN04',
        query: 'order service create order from basket checkout',
        difficulty: 'medium',
        topK: 5,
        description: 'OrderService.CreateOrderAsync builds an Order from a basket and ships it to an address',
        expected_names: ['OrderService', 'IOrderService'],
        expected_files: ['ApplicationCore/Services/OrderService.cs'],
    },
    {
        id: 'AN06',
        query: 'EmailSender send email account confirmation password reset',
        difficulty: 'medium',
        topK: 5,
        description: 'Email sender implementation used for account confirmation and password reset',
        expected_names: ['EmailSender', 'IEmailSender'],
        expected_files: ['Infrastructure/Services/EmailSender.cs'],
    },
    {
        id: 'AN07',
        query: 'component stylesheet css rules header',
        difficulty: 'medium',
        topK: 10,
        description: 'CSS rule sets for the application and shared header component stylesheets',
        expected_names: ['app_rule_set', 'header_rule_set', 'app.component_rule_set'],
        expected_files: ['Web/wwwroot/css'],
    },

    // ── NL / SEMANTIC (behavioural — target symbol NOT named) ───────────────────

    {
        id: 'AN08',
        query: 'service returning a paged and filtered list of catalog items for display',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Catalog view-model service that produces the paged/filtered catalog index for the storefront',
        expected_names: ['CatalogViewModelService', 'CatalogItemService', 'CachedCatalogViewModelService'],
        expected_files: ['Web/Services'],
    },
    {
        id: 'AN09',
        query: 'issue a signed JSON web token for a user containing their roles after sign in',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Builds a signed JWT carrying the user name and role claims',
        expected_names: ['IdentityTokenClaimService', 'ITokenClaimsService'],
        expected_files: ['Infrastructure/Identity/IdentityTokenClaimService.cs'],
    },
    // ── XC (cross-cutting, phrased behaviourally) ───────────────────────────────

    {
        id: 'AN11',
        query: 'persist a customer basket using the generic data-access repository abstraction',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'The repository interface(s) the basket aggregate is stored through (IRepository / IReadRepository)',
        expected_names: ['IRepository', 'IReadRepository'],
        expected_files: ['ApplicationCore/Interfaces'],
    },
    {
        id: 'AN12',
        query: 'the order aggregate holding order items and a shipping address',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Order aggregate root that encapsulates its order items and ship-to address and totals them (seed)',
        expected_names: ['Order', 'OrderItem'],
        expected_files: ['ApplicationCore/Entities/OrderAggregate/Order.cs'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──────────────────

    {
        id: 'HO-AN1',
        query: 'AuthenticateEndpoint',
        difficulty: 'easy',
        topK: 5,
        description: 'Minimal-API endpoint that authenticates a user and returns a token',
        expected_names: ['AuthenticateEndpoint'],
        expected_files: ['PublicApi/AuthEndpoints/AuthenticateEndpoint.cs'],
        heldOut: true,
    },
    {
        id: 'HO-AN2',
        query: 'record that captures the product details of a catalog item at the moment it was ordered',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Value object snapshotting catalog item name/picture/id on an order line',
        expected_names: ['CatalogItemOrdered'],
        expected_files: ['ApplicationCore/Entities/OrderAggregate/CatalogItemOrdered.cs'],
        heldOut: true,
    },
    {
        id: 'HO-AN3',
        query: 'wrap an inner catalog service to memoize its results in an in-memory cache',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'Caching decorator that stores catalog brand/type/item view models in IMemoryCache',
        expected_names: ['CachedCatalogItemServiceDecorator', 'CachedCatalogLookupDataServiceDecorator'],
        expected_files: ['BlazorAdmin/Services'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "AN13",
        query: "UriComposer",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Service that rewrites a picture-URI placeholder with the configured catalog base URL",
        expected_names: ["UriComposer","IUriComposer"],
        expected_files: ["ApplicationCore/Services/UriComposer.cs","ApplicationCore/Interfaces/IUriComposer.cs"],
    },
    {
        id: "AN14",
        query: "BasketQueryService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Query service that sums total basket item count directly on the database",
        expected_names: ["BasketQueryService","IBasketQueryService"],
        expected_files: ["Infrastructure/Data/Queries/BasketQueryService.cs"],
    },
    {
        id: "AN15",
        query: "OrderController",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "MVC controller exposing MyOrders and order Detail actions via MediatR",
        expected_names: ["OrderController"],
        expected_files: ["Web/Controllers/OrderController.cs"],
    },
    {
        id: "AN16",
        query: "CatalogContext EF Core DbContext DbSet entities",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Entity Framework DbContext exposing Baskets, CatalogItems, Orders, etc. DbSets",
        expected_names: ["CatalogContext"],
        expected_files: ["Infrastructure/Data/CatalogContext.cs"],
    },
    {
        id: "AN17",
        query: "seed catalog brands types and items into the database on startup",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Seeds preconfigured catalog brands, types and items via the catalog context",
        expected_names: ["CatalogContextSeed"],
        expected_files: ["Infrastructure/Data/CatalogContextSeed.cs"],
    },
    {
        id: "AN18",
        query: "register core application services and repositories in the DI container",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Service-collection extension wiring repositories, basket/order services, logger and email sender",
        expected_names: ["ConfigureCoreServices","Dependencies"],
        expected_files: ["Web/Configuration/ConfigureCoreServices.cs","Infrastructure/Dependencies.cs"],
    },
    {
        id: "AN19",
        query: "minimal API endpoint to create a new catalog item restricted to administrators",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Create catalog item endpoint that checks for duplicate name then adds the item, admin-only via JWT",
        expected_names: ["CreateCatalogItemEndpoint"],
        expected_files: ["PublicApi/CatalogItemEndpoints/CreateCatalogItemEndpoint.cs"],
    },
    {
        id: "AN20",
        query: "build a read-only adapter that forwards log calls to the framework logger factory",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Generic logging adapter wrapping ILogger and implementing the app logger abstraction",
        expected_names: ["LoggerAdapter","IAppLogger"],
        expected_files: ["Infrastructure/Logging/LoggerAdapter.cs","ApplicationCore/Interfaces/IAppLogger.cs"],
    },
    {
        id: "AN21",
        query: "query objects that eager-load an order together with its line items",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Ardalis specifications including order items when fetching orders by id or by customer",
        expected_names: ["OrderWithItemsByIdSpec","CustomerOrdersWithItemsSpecification"],
        expected_files: ["ApplicationCore/Specifications"],
    },
    {
        id: "AN22",
        query: "validate that an uploaded product image is a small jpg png or gif",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Extension method validating posted image byte size and allowed file extension",
        expected_names: ["ImageValidators"],
        expected_files: ["PublicApi/ImageValidators.cs"],
    },
    {
        id: "AN23",
        query: "exception thrown when a checkout is attempted on an empty basket",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Domain exception signalling a basket has zero items at checkout",
        expected_names: ["EmptyBasketOnCheckoutException"],
        expected_files: ["ApplicationCore/Exceptions/EmptyBasketOnCheckoutException.cs"],
    },
    {
        id: "AN24",
        query: "AutoMapper profile mapping catalog entities to their DTOs",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Mapping profile configuring CatalogItem/Type/Brand to DTO maps for the public API",
        expected_names: ["MappingProfile"],
        expected_files: ["PublicApi/MappingProfile.cs"],
    },
    {
        id: "AN25",
        query: "the customer entity that owns a collection of payment methods",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Buyer aggregate root keyed by identity guid holding its payment methods",
        expected_names: ["Buyer","PaymentMethod"],
        expected_files: ["ApplicationCore/Entities/BuyerAggregate"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-AN4",
        query: "UserController",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "API controller returning the current user and handling logout / token issuance",
        expected_names: ["UserController"],
        expected_files: ["Web/Controllers/UserController.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN5",
        query: "ApplicationUser",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "ASP.NET Identity user entity used by the identity DbContext and sign-in manager",
        expected_names: ["ApplicationUser"],
        expected_files: ["Infrastructure/Identity/ApplicationUser.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN6",
        query: "SlugifyParameterTransformer",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Outbound route parameter transformer that converts CamelCase to dash-lowercase slugs",
        expected_names: ["SlugifyParameterTransformer"],
        expected_files: ["Web/SlugifyParameterTransformer.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN7",
        query: "CatalogItemListPagedEndpoint",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Minimal API endpoint returning a paged list of catalog items",
        expected_names: ["CatalogItemListPagedEndpoint"],
        expected_files: ["PublicApi/CatalogItemEndpoints/CatalogItemListPagedEndpoint.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN8",
        query: "BasketViewModelService",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Web service mapping a basket aggregate into a basket view model for the storefront",
        expected_names: ["BasketViewModelService","IBasketViewModelService"],
        expected_files: ["Web/Services/BasketViewModelService.cs","Web/Interfaces/IBasketViewModelService.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN9",
        query: "ASP.NET Identity DbContext for users and roles",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Identity-specific EF DbContext deriving from IdentityDbContext of ApplicationUser",
        expected_names: ["AppIdentityDbContext"],
        expected_files: ["Infrastructure/Identity/AppIdentityDbContext.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN10",
        query: "generic EF Core repository configuration registering catalog and identity database contexts",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Infrastructure DI bootstrap choosing in-memory vs SQL Server for both DbContexts",
        expected_names: ["Dependencies"],
        expected_files: ["Infrastructure/Dependencies.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN11",
        query: "cookie authentication options login path and same-site policy setup",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Service-collection extension configuring the application authentication cookie and policy",
        expected_names: ["ConfigureCookieSettings"],
        expected_files: ["Web/Configuration/ConfigureCookieSettings.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN12",
        query: "MediatR request and handler that loads a customer's order history",
        kind: "xc",
        difficulty: "medium",
        topK: 10,
        description: "GetMyOrders request plus its handler reading orders through the read repository",
        expected_names: ["GetMyOrders","GetMyOrdersHandler"],
        expected_files: ["Web/Features/MyOrders"],
        heldOut: true,
    },
    {
        id: "HO-AN13",
        query: "specification that pages and filters catalog items by brand and type",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Paginated catalog filter specification applying skip/take with optional brand and type predicates",
        expected_names: ["CatalogFilterPaginatedSpecification"],
        expected_files: ["ApplicationCore/Specifications/CatalogFilterPaginatedSpecification.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN14",
        query: "reject a signed-in user whose access has been revoked by checking the cache on each request",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Cookie authentication events overriding principal validation to honor server-side revocation",
        expected_names: ["RevokeAuthenticationEvents"],
        expected_files: ["Web/Configuration/RevokeAuthenticationEvents.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN15",
        query: "verify the API and home page respond healthily by fetching a known product page",
        kind: "xc",
        difficulty: "semantic",
        topK: 10,
        description: "Health check probes that GET an endpoint and assert a known product string is present",
        expected_names: ["ApiHealthCheck","HomePageHealthCheck"],
        expected_files: ["Web/HealthChecks"],
        heldOut: true,
    },
    {
        id: "HO-AN16",
        query: "exception raised when no identity user matches the supplied username",
        kind: "nl",
        difficulty: "semantic",
        topK: 5,
        description: "Identity exception thrown by the token service when a username cannot be found",
        expected_names: ["UserNotFoundException"],
        expected_files: ["Infrastructure/Identity/UserNotFoundException.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN17",
        query: "create the default demo and admin users and assign the administrator role",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Identity seed that provisions demo/admin accounts and the administrators role",
        expected_names: ["AppIdentityDbContextSeed"],
        expected_files: ["Infrastructure/Identity/AppIdentityDbContextSeed.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN18",
        query: "build the cache keys and sliding expiration used to memoize catalog lookups",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Static helpers generating brand/type/item cache keys and the default cache duration",
        expected_names: ["CacheHelpers"],
        expected_files: ["Web/Extensions/CacheHelpers.cs"],
        heldOut: true,
    },
    {
        id: "HO-AN19",
        query: "specifications that select catalog items by a set of ids or by exact name",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Catalog item specifications filtering by id collection and by name for duplicate checks",
        expected_names: ["CatalogItemsSpecification","CatalogItemNameSpecification"],
        expected_files: ["ApplicationCore/Specifications"],
        heldOut: true,
    },
    {
        id: "HO-AN20",
        query: "DeleteCatalogItemEndpoint",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Minimal API endpoint that deletes a catalog item by id, admin-only",
        expected_names: ["DeleteCatalogItemEndpoint"],
        expected_files: ["PublicApi/CatalogItemEndpoints/DeleteCatalogItemEndpoint.cs"],
        heldOut: true,
    },
];
