/**
 * test/suites/css.mjs
 *
 * Ground-truth query set for a SCSS subset of Bootstrap.
 * Source: https://github.com/twbs/bootstrap
 *
 * Indexed symbols are SCSS @mixin / @function definitions plus one
 * `<file>_rule_set` chunk per selector block. Names come straight from the
 * fixture's symbol universe (bench/_chunks/css.json) — no invented symbols.
 *
 * Key source layout:
 *   _functions.scss             — to-rgb, color-contrast, contrast-ratio,
 *                                   tint-color, shade-color, shift-color,
 *                                   escape-svg, str-replace, divide, add, subtract
 *   mixins/_breakpoints.scss    — breakpoint-min/max/next/infix,
 *                                   media-breakpoint-up/down/between/only
 *   mixins/_buttons.scss        — button-variant, button-outline-variant, button-size
 *   mixins/_gradients.scss      — gradient-bg, gradient-x/y, gradient-radial, ...
 *   mixins/_border-radius.scss  — valid-radius, border-radius, border-top-radius, ...
 *   mixins/_caret.scss          — caret, caret-down/up/end/start
 *   mixins/_visually-hidden.scss— visually-hidden, visually-hidden-focusable
 *   mixins/_text-truncate.scss  — text-truncate
 *   mixins/_deprecate.scss      — deprecate
 *   mixins/_table-variants.scss — table-variant
 */

export const META = {
    id: 'css',
    displayName: 'Bootstrap SCSS (subset)',
    language: 'SCSS',
    version: 'subset',
    url: 'https://github.com/twbs/bootstrap',
    expectedMinChunks: 200,
    expectedMinFiles: 40,
};

export const QUERIES = [
    // ── EASY (kw — symbolic name / keyword lookup) ──────────────────────────────

    {
        id: 'CSS01',
        query: 'button variant background border color mixin',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'button-variant mixin — emits the CSS custom properties for a coloured button (seed case btn-variant)',
        expected_names: ['button-variant'],
        expected_files: ['mixins/_buttons.scss'],
    },
    {
        id: 'CSS02',
        query: 'media breakpoint min width responsive',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'media-breakpoint-up — generates a min-width media query for a named breakpoint (seed case breakpoint)',
        expected_names: ['media-breakpoint-up'],
        expected_files: ['mixins/_breakpoints.scss'],
    },
    {
        id: 'CSS03',
        query: 'color contrast ratio function',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'color-contrast function — picks a readable foreground colour for a background (seed case contrast-fn)',
        expected_names: ['color-contrast'],
        expected_files: ['_functions.scss'],
    },

    // ── MEDIUM (kw) ─────────────────────────────────────────────────────────────

    {
        id: 'CSS04',
        query: 'linear gradient background image color stops mixin',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Gradient mixins that set a linear/radial gradient background-image',
        expected_names: ['gradient-x', 'gradient-y', 'gradient-bg', 'gradient-radial'],
        expected_files: ['mixins/_gradients.scss'],
    },
    {
        id: 'CSS05',
        query: 'border radius rounded corners mixin',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Border-radius mixins that round one or more corners of an element',
        expected_names: ['border-radius', 'border-top-radius', 'border-bottom-radius'],
        expected_files: ['mixins/_border-radius.scss'],
    },
    {
        id: 'CSS06',
        query: 'caret dropdown triangle arrow indicator',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Caret mixins that draw the little triangle used by dropdown toggles',
        expected_names: ['caret', 'caret-down', 'caret-up'],
        expected_files: ['mixins/_caret.scss'],
    },

    // ── NL / SEMANTIC (describe behaviour without naming the symbol) ────────────

    {
        id: 'CSS07',
        query: 'Hide an element on screen while keeping it readable by screen readers and assistive technology',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Accessibility helper that visually hides content but leaves it in the accessibility tree',
        expected_names: ['visually-hidden', 'visually-hidden-focusable'],
        expected_files: ['mixins/_visually-hidden.scss', 'helpers/_visually-hidden.scss'],
    },
    {
        id: 'CSS08',
        query: 'Clip a single line of overflowing text and end it with an ellipsis',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Truncation helper using overflow hidden, text-overflow ellipsis and nowrap',
        expected_names: ['text-truncate'],
        expected_files: ['mixins/_text-truncate.scss', 'helpers/_text-truncation.scss'],
    },
    {
        id: 'CSS09',
        query: 'Lighten or darken a colour by blending it with white or black by a percentage',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Colour functions that tint (mix with white) or shade (mix with black) a colour',
        expected_names: ['tint-color', 'shade-color', 'shift-color'],
        expected_files: ['_functions.scss'],
    },

    // ── XC (cross-cutting, phrased behaviourally) ───────────────────────────────

    {
        id: 'CSS10',
        query: 'Perform division with a fixed precision to avoid Sass losing units',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Custom divide function implementing long division so units are preserved',
        expected_names: ['divide'],
        expected_files: ['_functions.scss'],
    },
    {
        id: 'CSS11',
        query: 'Compute the relative luminance ratio between a background and a foreground colour',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'Function returning the WCAG contrast ratio of two colours',
        expected_names: ['contrast-ratio'],
        expected_files: ['_functions.scss'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ─────────────────

    {
        id: 'HO-CSS1',
        query: 'escape svg data uri characters for use in a css background',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Held-out: escape-svg encodes reserved characters inside an inline SVG data URI',
        expected_names: ['escape-svg'],
        expected_files: ['_functions.scss'],
        heldOut: true,
    },
    {
        id: 'HO-CSS2',
        query: 'Emit a warning that a mixin or function is obsolete and will be removed in a future release',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Held-out: deprecation helper that @warns about a symbol being removed',
        expected_names: ['deprecate'],
        expected_files: ['mixins/_deprecate.scss'],
        heldOut: true,
    },
    {
        id: 'HO-CSS3',
        query: 'Generate the coloured background and border styles for a contextual table row state',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'Held-out: mixin that builds the .table-<state> variant custom properties',
        expected_names: ['table-variant'],
        expected_files: ['mixins/_table-variants.scss'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "CSS12",
        query: "button-outline-variant",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Symbolic lookup for the outline button variant mixin (emits the ghost/outline btn custom properties)",
        expected_names: ["button-outline-variant"],
        expected_files: ["mixins/_buttons.scss"],
    },
    {
        id: "CSS13",
        query: "button size padding font-size border-radius mixin",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "button-size mixin sets the per-size btn padding/font-size/border-radius custom properties",
        expected_names: ["button-size"],
        expected_files: ["mixins/_buttons.scss"],
    },
    {
        id: "CSS14",
        query: "diagonal angled gradient and barber-pole striped background image mixins",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Directional (angled) and striped linear-gradient background mixins",
        expected_names: ["gradient-directional","gradient-striped"],
        expected_files: ["mixins/_gradients.scss"],
    },
    {
        id: "CSS15",
        query: "round only the left or right side corners with logical start and end border radius",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Logical-property border-radius mixins that round the start (left) or end (right) pair of corners",
        expected_names: ["border-start-radius","border-end-radius"],
        expected_files: ["mixins/_border-radius.scss"],
    },
    {
        id: "CSS16",
        query: "Draw a sideways caret triangle pointing to the start or end for inline dropdowns",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Caret mixins that render the horizontal (start/end) triangle borders for dropend/dropstart toggles",
        expected_names: ["caret-start","caret-end"],
        expected_files: ["mixins/_caret.scss"],
    },
    {
        id: "CSS17",
        query: "media query for screens at most as wide as a breakpoint, and one spanning between two breakpoints",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "media-breakpoint-down (max-width) and media-breakpoint-between (min and max) responsive mixins",
        expected_names: ["media-breakpoint-down","media-breakpoint-between"],
        expected_files: ["mixins/_breakpoints.scss"],
    },
    {
        id: "CSS18",
        query: "breakpoint-infix",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Symbolic lookup: returns the dash-prefixed breakpoint suffix (empty for the smallest) used to build responsive class names",
        expected_names: ["breakpoint-infix"],
        expected_files: ["mixins/_breakpoints.scss"],
    },
    {
        id: "CSS19",
        query: "Convert a color to its comma-separated red green blue channel triplet for css variables",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "to-rgb function returns the r,g,b component list used to populate -rgb custom properties",
        expected_names: ["to-rgb"],
        expected_files: ["_functions.scss"],
    },
    {
        id: "CSS20",
        query: "Find and replace a substring inside a Sass string, used to encode SVG icon backgrounds",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "str-replace recursive string substitution helper backing escape-svg",
        expected_names: ["str-replace"],
        expected_files: ["_functions.scss"],
    },
    {
        id: "CSS21",
        query: "Add or subtract two values that may carry different units by emitting a css calc expression",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "add and subtract functions that fall back to calc() when operands are not directly comparable",
        expected_names: ["add","subtract"],
        expected_files: ["_functions.scss"],
    },
    {
        id: "CSS22",
        query: "Clamp a list of border-radius values so negative radii become zero",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "valid-radius helper function that floors each radius value at 0 before applying border-radius",
        expected_names: ["valid-radius"],
        expected_files: ["mixins/_border-radius.scss"],
    },
    {
        id: "CSS23",
        query: "compute a flex column width as a fraction of the total grid columns",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "make-col grid mixin that sizes a column via percentage(divide(size, columns)); row-cols forces N equal children per row",
        expected_names: ["make-col","make-col-offset","row-cols"],
        expected_files: ["mixins/_grid.scss"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-CSS4",
        query: "media-breakpoint-only",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out symbolic lookup: media query scoped to exactly one breakpoint band (its min up to the next breakpoint's max)",
        expected_names: ["media-breakpoint-only"],
        expected_files: ["mixins/_breakpoints.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS5",
        query: "color-scheme",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out symbolic lookup: thin mixin wrapping a prefers-color-scheme media query around its content",
        expected_names: ["color-scheme"],
        expected_files: ["mixins/_color-scheme.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS6",
        query: "overlay-backdrop",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out symbolic lookup: fixed full-viewport backdrop mixin shared by modals and offcanvas",
        expected_names: ["overlay-backdrop"],
        expected_files: ["mixins/_backdrop.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS7",
        query: "box shadow mixin gated behind enable-shadows flag",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: box-shadow mixin that only emits the property when $enable-shadows is on",
        expected_names: ["box-shadow"],
        expected_files: ["mixins/_box-shadow.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS8",
        query: "transition property mixin respecting reduced motion preference",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: transition mixin that disables transitions under prefers-reduced-motion",
        expected_names: ["transition"],
        expected_files: ["mixins/_transition.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS9",
        query: "Toggle styles based on the user's light or dark theme via prefers-color-scheme or a data-bs-theme attribute",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: color-mode mixin that wraps content in a media query or theme attribute selector",
        expected_names: ["color-mode"],
        expected_files: ["mixins/_color-mode.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS10",
        query: "Reset inherited typography to a neutral baseline so tooltip and popover text renders predictably",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: reset-text mixin normalising font, line-height, alignment and whitespace for overlay components",
        expected_names: ["reset-text"],
        expected_files: ["mixins/_reset-text.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS11",
        query: "Clear floated children by inserting an empty block pseudo element after the container",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: clearfix mixin using ::after { display: block; clear: both }",
        expected_names: ["clearfix"],
        expected_files: ["mixins/_clearfix.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS12",
        query: "Let users drag-resize an element in a chosen direction by setting overflow and the resize property",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: resizable mixin exposing horizontal/vertical/both resize handles",
        expected_names: ["resizable"],
        expected_files: ["mixins/_resize.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS13",
        query: "Generate the valid and invalid feedback, tooltip and focus styles for a form input state",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: form-validation-state builds .valid/.invalid feedback styling; the -selector mixin produces the matching is-valid/was-validated selectors",
        expected_names: ["form-validation-state","form-validation-state-selector"],
        expected_files: ["mixins/_forms.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS14",
        query: "Emit the coloured background, border and link custom properties for a contextual alert variant",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: alert-variant mixin setting --alert-color/-bg/-border-color/-link-color",
        expected_names: ["alert-variant"],
        expected_files: ["mixins/_alert.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS15",
        query: "Build the coloured list group item modifier classes for a contextual state with hover and active styles",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: list-group-item-variant mixin generating .list-group-item-<state> with shaded hover/active backgrounds",
        expected_names: ["list-group-item-variant"],
        expected_files: ["mixins/_list-group.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS16",
        query: "Set the per-size pagination padding, font-size and border-radius custom properties",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: pagination-size mixin defining the --pagination-* sizing variables",
        expected_names: ["pagination-size"],
        expected_files: ["mixins/_pagination.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS17",
        query: "breakpoint-next",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out symbolic lookup: function returning the name of the breakpoint immediately larger than a given one",
        expected_names: ["breakpoint-next"],
        expected_files: ["mixins/_breakpoints.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS18",
        query: "Wrap a css variable reference in rgba so an opacity custom property tints a colour token",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: rgba-css-var function emitting rgba(var(--..-rgb), var(--..-opacity)) for theme colour tokens",
        expected_names: ["rgba-css-var"],
        expected_files: ["_functions.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS19",
        query: "Loop over a utility config map to emit responsive utility classes and their property values",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: generate-utility mixin that turns a utility definition map into the generated CSS classes",
        expected_names: ["generate-utility"],
        expected_files: ["mixins/_utilities.scss"],
        heldOut: true,
    },
    {
        id: "HO-CSS20",
        query: "Center a fixed-width container with horizontal gutter padding and auto side margins",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: make-container mixin setting gutter custom properties, full width and auto left/right margins",
        expected_names: ["make-container"],
        expected_files: ["mixins/_container.scss"],
        heldOut: true,
    },
];
