/**
 * test/suites/django.mjs
 *
 * Ground-truth query set for a django-oscar subset (Python/Django).
 * Source: https://github.com/django-oscar/django-oscar
 *
 * Every expected_name below is a REAL indexed symbol (whole name or a real
 * class_context) taken from bench/_chunks/django.json. Behavioural (nl/xc)
 * queries describe what the code DOES without naming the target symbol.
 *
 * Key source layout (oscar app packages):
 *   address/abstract_models.py     — AbstractAddress + subclasses (postal address models)
 *   customer/forms.py              — generate_username, PasswordResetForm, registration forms
 *   customer/utils.py              — normalise_email
 *   customer/auth_backends.py      — EmailBackend (authenticate by email)
 *   basket/abstract_models.py      — AbstractBasket: add_product, freeze, thaw, totals
 *   basket/middleware.py           — BasketMiddleware: merge_baskets, apply_offers_to_basket
 *   offer/applicator.py            — Applicator.apply (apply offers to a basket)
 *   order/utils.py                 — OrderCreator.place_order, OrderNumberGenerator, record_voucher_usage
 *   checkout/mixins.py             — OrderPlacementMixin: generate_order_number, place_order
 *   payment/bankcards.py           — luhn, bankcard_type (card number checks)
 *   shipping/repository.py         — Repository: get_shipping_methods
 *   voucher/abstract_models.py     — AbstractVoucher: is_available_to_user
 */

export const META = {
    id: 'django',
    displayName: 'django-oscar (subset)',
    language: 'Python/Django',
    version: 'subset',
    url: 'https://github.com/django-oscar/django-oscar',
    expectedMinChunks: 400,
    expectedMinFiles: 100,
};

export const QUERIES = [
    // ── EASY / MEDIUM (kw — symbolic name + domain-keyword lookup) ──────────────

    {
        id: 'DJ01',
        query: 'password reset form email user',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'PasswordResetForm — sends a one-use password reset link to the user (seed: pw-reset)',
        expected_names: ['PasswordResetForm'],
        expected_files: ['customer/forms.py'],
    },
    {
        id: 'DJ02',
        query: 'voucher form code create',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'Voucher creation form and the abstract voucher model',
        expected_names: ['VoucherForm', 'AbstractVoucher'],
        expected_files: ['voucher'],
    },
    {
        id: 'DJ03',
        query: 'order creator place order models',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'OrderCreator.place_order — writes out the order models when placing an order',
        expected_names: ['OrderCreator', 'place_order'],
        expected_files: ['order/utils.py'],
    },
    {
        id: 'DJ04',
        query: 'shipping repository methods available',
        kind: 'kw',
        difficulty: 'medium',
        topK: 5,
        description: 'Repository.get_shipping_methods — returns the available shipping methods for a basket',
        expected_names: ['Repository', 'get_shipping_methods'],
        expected_files: ['shipping/repository.py'],
    },

    // ── SEMANTIC (nl — behavioural, target symbol NOT named) ────────────────────

    {
        id: 'DJ05',
        query: 'generate a unique username derived from a user email address',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'generate_username — picks a random unique username (seed: username-gen)',
        expected_names: ['generate_username'],
        expected_files: ['customer/forms.py'],
    },
    {
        id: 'DJ06',
        query: 'check that a credit card number is valid using the standard checksum digit algorithm',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'luhn — Luhn checksum validation of a bankcard number',
        expected_names: ['luhn', 'bankcard_type'],
        expected_files: ['payment/bankcards.py'],
    },
    {
        id: 'DJ07',
        query: 'work out which promotional discounts apply to the items in a shopping cart and apply them',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Applicator.apply — applies all relevant offers to a basket',
        expected_names: ['Applicator', 'apply'],
        expected_files: ['offer/applicator.py'],
    },

    // ── HARD / SEMANTIC (xc — cross-cutting concerns phrased behaviourally) ──────

    {
        id: 'DJ08',
        query: 'abstract base model describing a postal address with name and country',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'AbstractAddress — superclass postal address model (seed: address-model)',
        expected_names: ['AbstractAddress'],
        expected_files: ['address/abstract_models.py'],
    },
    {
        id: 'DJ09',
        query: 'when an anonymous shopper logs in, combine their session basket with any saved basket',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'BasketMiddleware.merge_baskets — merges the anonymous and authenticated baskets',
        expected_names: ['merge_baskets', 'BasketMiddleware'],
        expected_files: ['basket/middleware.py'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    {
        id: 'HO-DJ1',
        query: 'authentication backend that logs a user in by their email address instead of a username',
        kind: 'xc',
        difficulty: 'semantic',
        topK: 10,
        description: 'EmailBackend — authenticates a user against their email address',
        expected_names: ['EmailBackend'],
        expected_files: ['customer/auth_backends.py'],
        heldOut: true,
    },
    {
        id: 'HO-DJ2',
        query: 'produce a human-readable order number for a basket before the order is saved',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'OrderNumberGenerator — generates an order number from a basket',
        expected_names: ['OrderNumberGenerator'],
        expected_files: ['order/utils.py'],
        heldOut: true,
    },
    {
        id: 'HO-DJ3',
        query: 'normalise_email',
        kind: 'kw',
        difficulty: 'easy',
        topK: 5,
        description: 'normalise_email — lower-cases the domain part of an email address',
        expected_names: ['normalise_email'],
        expected_files: ['customer/utils.py'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "DJ10",
        query: "ActiveOfferManager",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "ActiveOfferManager — model manager filtering offers that are currently live (date-bounded queryset).",
        expected_names: ["ActiveOfferManager"],
        expected_files: ["offer/managers.py"],
    },
    {
        id: "DJ11",
        query: "ProductQuerySet filter products by attributes",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "ProductQuerySet — custom queryset on the catalogue product manager (browsable/public/attribute filtering).",
        expected_names: ["ProductQuerySet"],
        expected_files: ["catalogue/managers.py"],
    },
    {
        id: "DJ12",
        query: "OrderTotalCalculator calculate order total",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "OrderTotalCalculator — computes the order total from basket, shipping charge and surcharges.",
        expected_names: ["OrderTotalCalculator"],
        expected_files: ["checkout/calculators.py"],
    },
    {
        id: "DJ13",
        query: "EmailUserCreationForm registration sign up",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "EmailUserCreationForm — user registration form keyed on email; EmailAuthenticationForm is the matching login form.",
        expected_names: ["EmailUserCreationForm","EmailAuthenticationForm"],
        expected_files: ["customer/forms.py"],
    },
    {
        id: "DJ14",
        query: "freeze and thaw a basket to lock it during checkout",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "AbstractBasket.freeze / thaw — freeze locks a basket while an order is being placed, thaw reopens it.",
        expected_names: ["freeze","thaw"],
        expected_files: ["basket/abstract_models.py"],
    },
    {
        id: "DJ15",
        query: "calculate the average star rating of a product from its reviews and store it",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "calculate_rating / update_rating — recomputes and persists a product's aggregate review score.",
        expected_names: ["calculate_rating","update_rating"],
        expected_files: ["catalogue/abstract_models.py"],
    },
    {
        id: "DJ16",
        query: "tax strategy that picks a price and availability policy for a product",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Selector / Structured — partner strategy that resolves pricing + availability policy for a product.",
        expected_names: ["Selector","Structured"],
        expected_files: ["partner/strategy.py"],
    },
    {
        id: "DJ17",
        query: "condition that is met once the basket holds enough qualifying items",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "CountCondition — offer condition satisfied when the basket contains a minimum number of matching items.",
        expected_names: ["CountCondition"],
        expected_files: ["offer/conditions.py"],
    },
    {
        id: "DJ18",
        query: "ProductReviewQuerySet approved reviews",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "ProductReviewQuerySet — queryset for product reviews (e.g. approved-only filtering).",
        expected_names: ["ProductReviewQuerySet"],
        expected_files: ["catalogue/reviews/managers.py"],
    },
    {
        id: "DJ19",
        query: "add and remove products from a discount range and test membership",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "AbstractRange.contains_product / add_product — manage which products belong to an offer Range.",
        expected_names: ["AbstractRange","contains_product"],
        expected_files: ["offer/abstract_models.py"],
    },
    {
        id: "DJ20",
        query: "weigh a basket by summing the weight of every product line",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Scale — shipping helper that totals product weights across the basket lines.",
        expected_names: ["Scale"],
        expected_files: ["shipping/scales.py"],
    },
    {
        id: "DJ21",
        query: "handler that advances an order's status and records the change event",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "EventHandler.handle_order_status_change — transitions order status and writes the status-change record.",
        expected_names: ["EventHandler","handle_order_status_change"],
        expected_files: ["order/processing.py"],
    },
    {
        id: "DJ22",
        query: "GatewayForm bankcard payment form",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "GatewayForm / BankcardForm — checkout payment-gateway and bankcard entry forms.",
        expected_names: ["GatewayForm","BankcardForm"],
        expected_files: ["checkout/forms.py","payment/forms.py"],
    },
    {
        id: "DJ23",
        query: "AbstractConditionalOffer is_available",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "AbstractConditionalOffer.is_available — whether an offer can currently be applied (date/usage limits).",
        expected_names: ["AbstractConditionalOffer","is_available"],
        expected_files: ["offer/abstract_models.py"],
    },
    {
        id: "DJ24",
        query: "import a catalogue of products from an uploaded CSV file",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "CatalogueImporter — bulk-imports products from a file feed.",
        expected_names: ["CatalogueImporter"],
        expected_files: ["partner/importers.py"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-DJ4",
        query: "OpenBasketManager",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "OpenBasketManager — manager returning only baskets in the OPEN status.",
        expected_names: ["OpenBasketManager"],
        expected_files: ["basket/managers.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ5",
        query: "CategoryQuerySet",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "CategoryQuerySet — queryset over the tree of catalogue categories (browsable/for-menu).",
        expected_names: ["CategoryQuerySet"],
        expected_files: ["catalogue/managers.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ6",
        query: "RangeQuerySet",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "RangeQuerySet — custom queryset for offer ranges.",
        expected_names: ["RangeQuerySet"],
        expected_files: ["offer/queryset.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ7",
        query: "UserManager",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "UserManager — custom manager for the email-based user model.",
        expected_names: ["UserManager"],
        expected_files: ["customer/abstract_models.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ8",
        query: "ConditionForm offer condition validation",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "ConditionForm / BenefitForm — dashboard forms that validate the condition and benefit of an offer.",
        expected_names: ["ConditionForm","BenefitForm"],
        expected_files: ["dashboard/offers/forms.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ9",
        query: "verify a card number passes the mod-10 checksum",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "luhn — mod-10 checksum used to sanity-check a card number before charging.",
        expected_names: ["luhn"],
        expected_files: ["payment/bankcards.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ10",
        query: "decide whether an offer condition is met by the current basket contents",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "CoverageCondition / ValueCondition — conditions judged against basket coverage or monetary value.",
        expected_names: ["CoverageCondition","ValueCondition"],
        expected_files: ["offer/conditions.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ11",
        query: "send the order-confirmation email after a successful checkout",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "send_order_placed_email — dispatches the confirmation email once an order is placed.",
        expected_names: ["send_order_placed_email"],
        expected_files: ["customer"],
        heldOut: true,
    },
    {
        id: "HO-DJ12",
        query: "notify shoppers watching a product once it is back in stock",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "send_product_alerts — emails users with an active alert when their watched product is restocked.",
        expected_names: ["send_product_alerts"],
        expected_files: ["customer/alerts/receivers.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ13",
        query: "build a one-time password-reset link for a user account",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "get_password_reset_url — constructs the signed reset URL sent to a user.",
        expected_names: ["get_password_reset_url"],
        expected_files: ["customer"],
        heldOut: true,
    },
    {
        id: "HO-DJ14",
        query: "walk a category up and down its tree of ancestors and descendants",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "get_ancestors_and_self / get_descendants_and_self — traverse the category MPTT-style tree.",
        expected_names: ["get_ancestors_and_self","get_descendants_and_self"],
        expected_files: ["catalogue/abstract_models.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ15",
        query: "compute the final order total from the basket and shipping charge",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "OrderTotalCalculator — adds shipping and surcharges to the basket total to get the order total.",
        expected_names: ["OrderTotalCalculator"],
        expected_files: ["checkout/calculators.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ16",
        query: "mixin that registers and logs in a new user after they sign up",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "RegisterUserMixin — creates the user account and signs them in during registration.",
        expected_names: ["RegisterUserMixin"],
        expected_files: ["customer/mixins.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ17",
        query: "stash and reuse checkout choices in the session across the wizard steps",
        kind: "xc",
        difficulty: "hard",
        topK: 10,
        description: "CheckoutSessionMixin — reads/writes the checkout selections held in the session.",
        expected_names: ["CheckoutSessionMixin"],
        expected_files: ["checkout/session.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ18",
        query: "GeneratorRepository",
        kind: "kw",
        difficulty: "easy",
        topK: 5,
        description: "GeneratorRepository — registry of dashboard report generators.",
        expected_names: ["GeneratorRepository"],
        expected_files: ["dashboard/reports/utils.py"],
        heldOut: true,
    },
    {
        id: "HO-DJ19",
        query: "turn raw search-engine facet counts into selectable filter links",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "FacetMunger — transforms Solr/ES facet counts into UI-ready facet data with toggle URLs.",
        expected_names: ["FacetMunger"],
        expected_files: ["search/facets.py"],
        heldOut: true,
    },
];
