/**
 * test/suites/express-js.mjs
 *
 * Ground-truth query set for Express 4.18.2 (JavaScript).
 * Source: https://github.com/expressjs/express (tag 4.18.2)
 *
 * Key source layout:
 * lib/application.js         — app.init, app.use, app.listen, app.handle
 * lib/express.js             — createApplication
 * lib/router/index.js        — proto.handle, proto.process_params, proto.route
 * lib/router/layer.js        — Layer (constructor), Layer.match, Layer.handle_request
 * lib/router/route.js        — Route (constructor), Route.dispatch, Route.all
 * lib/request.js             — req.get, req.accepts, req.range
 * lib/response.js            — res.send, res.json, res.render, res.redirect
 * lib/view.js                — View (constructor), View.render, View.lookup
 * lib/middleware/init.js     — init (initialisation middleware)
 * lib/middleware/query.js    — query (query-string middleware)
 * lib/utils.js               — setCharset, etag, etc.
 */

export const META = {
    id: 'express-js',
    displayName: 'Express 4.18.2',
    language: 'JavaScript',
    version: '4.18.2',
    url: 'https://github.com/expressjs/express',
    expectedMinChunks: 60,
    expectedMinFiles: 20,
};

export const QUERIES = [
    // ── EASY ──────────────────────────────────────────────────────────────────

    {
        id: 'EX01',
        query: 'createApplication',
        difficulty: 'easy',
        topK: 5,
        description: 'Factory that creates the top-level Express application object',
        expected_names: ['createApplication'],
        expected_files: ['lib/express'],
    },
    {
        id: 'EX02',
        query: 'Layer match path',
        difficulty: 'easy',
        topK: 5,
        description: 'Router layer that matches a URL path against a regexp',
        expected_names: ['Layer'],
        expected_files: ['router/layer'],
    },
    {
        id: 'EX03',
        query: 'Route dispatch method',
        difficulty: 'easy',
        topK: 5,
        description: 'Route object that dispatches an HTTP request to its handlers',
        expected_names: ['Route'],
        expected_files: ['router/route'],
    },

    // ── MEDIUM ────────────────────────────────────────────────────────────────

    {
        id: 'EX04',
        query: 'router handle request next',
        difficulty: 'medium',
        topK: 5,
        description: 'Main router dispatch function that chains through layers',
        expected_names: ['handle', 'proto.handle'],
        expected_files: ['router/index'],
    },
    {
        id: 'EX05',
        query: 'application listen port server',
        difficulty: 'medium',
        topK: 5,
        description: 'Starts the HTTP server and listens on a given port',
        expected_names: ['listen'],
        expected_files: ['lib/application'],
    },
    {
        id: 'EX06',
        query: 'response send body content type',
        difficulty: 'medium',
        topK: 5,
        description: 'res.send() — sends the HTTP response with auto content-type detection',
        expected_names: ['send'],
        expected_files: ['lib/response'],
    },
    {
        id: 'EX07',
        query: 'response json serialize object',
        difficulty: 'medium',
        topK: 5,
        description: 'res.json() — serialises an object to JSON and sends it',
        expected_names: ['json'],
        expected_files: ['lib/response'],
    },
    {
        id: 'EX08',
        query: 'view render template engine',
        difficulty: 'medium',
        topK: 5,
        description: 'View class that renders a template file using the chosen engine',
        expected_names: ['render', 'View'],
        expected_files: ['lib/view'],
    },
    {
        id: 'EX09',
        query: 'process params router middleware',
        difficulty: 'medium',
        topK: 5,
        description: 'Processes URL parameter callbacks registered with app.param()',
        expected_names: ['process_params'],
        expected_files: ['router/index'],
    },
    {
        id: 'EX10',
        query: 'request get header accept',
        difficulty: 'medium',
        topK: 5,
        description: 'req.get() / req.header() — retrieve a request header value',
        expected_names: ['req.get', 'req.header', 'req.accepts'],
        expected_files: ['lib/request'],
    },

    // ── HARD ──────────────────────────────────────────────────────────────────

    {
        id: 'EX11',
        query: 'redirect response permanent temporary',
        difficulty: 'hard',
        topK: 10,
        description: 'res.redirect() — issues an HTTP redirect with configurable status',
        expected_names: ['redirect'],
        expected_files: ['lib/response'],
    },
    {
        id: 'EX12',
        query: 'initialise request response locals app',
        difficulty: 'hard',
        topK: 10,
        description: 'Initialisation middleware that decorates req/res with Express extras',
        expected_names: ['exports.init', 'init'],
        expected_files: ['middleware/init'],
    },
    {
        id: 'EX13',
        query: 'mount sub application use path middleware stack',
        difficulty: 'hard',
        topK: 10,
        description: 'app.use() — mounts middleware or sub-apps at a path',
        expected_names: ['use'],
        expected_files: ['lib/application'],
    },
    {
        id: 'EX14',
        query: 'content negotiation accept header format',
        difficulty: 'hard',
        topK: 10,
        description: 'Content-type negotiation via Accept header (req.accepts / res.format)',
        expected_names: ['req.accepts', 'req.acceptsEncodings', 'req.acceptsCharsets', 'res.format', 'format'],
        expected_files: ['lib/request', 'lib/response'],
    },

    // ── SEMANTIC — agent-style conceptual queries ──────────────────────────────

    {
        id: 'EX15',
        query: 'iterate registered middleware functions in order passing request response and next callback',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent describing the core request dispatch loop conceptually',
        expected_names: ['handle', 'Layer'],
        expected_files: ['router/index', 'router/layer'],
    },
    {
        id: 'EX16',
        query: 'serialize JavaScript value to JSON string and write body with correct content type header',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for JSON response serialization without knowing method name',
        expected_names: ['json'],
        expected_files: ['lib/response'],
    },
    {
        id: 'EX17',
        query: 'How does the application parse incoming JSON payloads from the client?',
        difficulty: 'semantic',
        topK: 10,
        description: 'Locates the built-in JSON body parsing middleware',
        expected_names: ['json'],
        expected_files: ['lib/express'],
    },
    {
        id: 'EX18',
        query: 'Where is the logic that decides if a requested URL matches a registered route?',
        difficulty: 'semantic',
        topK: 10,
        description: 'Finds the core path-matching logic for incoming HTTP requests',
        expected_names: ['match'],
        expected_files: ['router/layer', 'router/index'],
    },
    {
        id: 'EX19',
        query: 'The global error handler that catches exceptions and sends a 500 status code',
        difficulty: 'semantic',
        topK: 10,
        description: 'Identifies the default Express error handling mechanism',
        expected_names: ['logerror', 'handle'],
        expected_files: ['lib/application', 'router/index'],
    },
    {
        id: 'EX20',
        query: 'Mechanism to render HTML templates and views for the user',
        difficulty: 'semantic',
        topK: 10,
        description: 'Finds the template engine rendering integration',
        expected_names: ['render'],
        expected_files: ['lib/application', 'lib/response'],
    },
    {
        id: 'EX21',
        query: 'Constructing and formatting the final HTTP response to send back to the browser',
        difficulty: 'semantic',
        topK: 10,
        description: 'Locates the general response building functions',
        expected_names: ['send', 'json', 'sendFile'],
        expected_files: ['lib/response'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    { id: 'HO-EX1', query: 'sendfile', difficulty: 'easy', expected_names: ['sendfile'], heldOut: true },
    { id: 'HO-EX2', query: 'parse an Accept header into acceptable media types ordered by quality', difficulty: 'semantic', topK: 10, expected_names: ['acceptParams'], heldOut: true },
    { id: 'HO-EX3', query: 'Router', difficulty: 'easy', expected_names: ['Router'], heldOut: true },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "EX22",
        query: "res.cookie set Set-Cookie header with options",
        difficulty: "medium",
        topK: 5,
        description: "res.cookie() — serialises a cookie and writes the Set-Cookie response header",
        expected_names: ["res.cookie"],
        expected_files: ["lib/response"],
    },
    {
        id: "EX23",
        query: "decode URL-encoded route parameter value",
        difficulty: "hard",
        topK: 10,
        description: "Layer helper that decodes a percent-encoded path parameter (intent, name not spoken)",
        expected_names: ["decode_param"],
        expected_files: ["router/layer"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-EX4",
        query: "res.vary",
        difficulty: "easy",
        topK: 5,
        description: "res.vary() — adds a field name to the Vary response header",
        expected_names: ["res.vary"],
        expected_files: ["lib/response"],
        heldOut: true,
    },
    {
        id: "HO-EX5",
        query: "View prototype lookup resolve template file path",
        difficulty: "easy",
        topK: 5,
        description: "View.lookup — searches the configured view roots for a template file",
        expected_names: ["View.prototype.lookup"],
        expected_files: ["lib/view"],
        heldOut: true,
    },
    {
        id: "HO-EX6",
        query: "app.set setting configuration value",
        difficulty: "easy",
        topK: 5,
        description: "app.set() — assigns an application setting (and compiles etag/query/trust on key settings)",
        expected_names: ["app.set"],
        expected_files: ["lib/application"],
        heldOut: true,
    },
    {
        id: "HO-EX7",
        query: "req.range parse Range header byte ranges",
        difficulty: "medium",
        topK: 5,
        description: "req.range() — parses the Range request header into byte ranges",
        expected_names: ["req.range"],
        expected_files: ["lib/request"],
        heldOut: true,
    },
    {
        id: "HO-EX8",
        query: "res.jsonp JSONP callback wrapped response",
        difficulty: "medium",
        topK: 5,
        description: "res.jsonp() — wraps a JSON body in a callback for cross-origin script consumption",
        expected_names: ["res.jsonp"],
        expected_files: ["lib/response"],
        heldOut: true,
    },
    {
        id: "HO-EX9",
        query: "app.lazyrouter create the router on first use",
        difficulty: "medium",
        topK: 5,
        description: "app.lazyrouter() — lazily instantiates the application's underlying Router",
        expected_names: ["app.lazyrouter"],
        expected_files: ["lib/application"],
        heldOut: true,
    },
    {
        id: "HO-EX10",
        query: "query string parsing middleware that populates req.query",
        difficulty: "medium",
        topK: 10,
        description: "Built-in query middleware that parses the URL query string onto req.query (name not spoken)",
        expected_names: ["module.exports"],
        expected_files: ["middleware/query"],
        heldOut: true,
    },
    {
        id: "HO-EX11",
        query: "normalize a content-type shorthand like json into a full MIME type",
        difficulty: "hard",
        topK: 10,
        description: "Utility that expands a type alias to a full MIME value used by content negotiation",
        expected_names: ["exports.normalizeType","exports.normalizeTypes"],
        expected_files: ["lib/utils"],
        heldOut: true,
    },
    {
        id: "HO-EX12",
        query: "compile the trust proxy setting into a predicate function",
        difficulty: "hard",
        topK: 10,
        description: "Utility that turns the 'trust proxy' setting into a function deciding which addresses to trust",
        expected_names: ["exports.compileTrust"],
        expected_files: ["lib/utils"],
        heldOut: true,
    },
    {
        id: "HO-EX13",
        query: "generate an ETag value from the response body for cache validation",
        difficulty: "hard",
        topK: 10,
        description: "Factory that builds the ETag-generating function used for conditional requests",
        expected_names: ["createETagGenerator","exports.compileETag"],
        expected_files: ["lib/utils"],
        heldOut: true,
    },
    {
        id: "HO-EX14",
        query: "verify a submitted username and password against the stored salted hash",
        difficulty: "semantic",
        topK: 10,
        description: "Auth example login check that hashes the posted password and compares to the stored hash",
        expected_names: ["authenticate"],
        expected_files: ["examples/auth"],
        heldOut: true,
    },
    {
        id: "HO-EX15",
        query: "block a request and bounce to the login page when there is no active session user",
        difficulty: "semantic",
        topK: 10,
        description: "Middleware guarding protected routes by redirecting unauthenticated requests",
        expected_names: ["restrict"],
        expected_files: ["examples/auth"],
        heldOut: true,
    },
    {
        id: "HO-EX16",
        query: "stream a file from disk to the client as the HTTP response",
        difficulty: "semantic",
        topK: 10,
        description: "Response helpers that transfer a file to the client (intent, multiple correct symbols)",
        expected_names: ["res.sendFile","sendfile","res.download"],
        expected_files: ["lib/response"],
        heldOut: true,
    },
    {
        id: "HO-EX17",
        query: "merge captured route parameters from a parent router into the child request params",
        difficulty: "semantic",
        topK: 10,
        description: "Router helper that propagates parent params into nested routers (intent, name not spoken)",
        expected_names: ["mergeParams"],
        expected_files: ["router/index"],
        heldOut: true,
    },
    {
        id: "HO-EX18",
        query: "find which registered layer matches the current request path during dispatch",
        difficulty: "semantic",
        topK: 10,
        description: "Internal router routine that tests a layer's regexp against the pathname while routing",
        expected_names: ["matchLayer","Layer.prototype.match"],
        expected_files: ["router/index","router/layer"],
        heldOut: true,
    },
    {
        id: "HO-EX19",
        query: "res.location set Location header resolve back referrer",
        difficulty: "medium",
        topK: 5,
        description: "res.location() — sets the Location response header, resolving 'back' to the referrer",
        expected_names: ["res.location"],
        expected_files: ["lib/response"],
        heldOut: true,
    },
];