/**
 * test/suites/fastapi.mjs
 *
 * Ground-truth query set for FastAPI 0.103.0 (Python).
 * Source: https://github.com/tiangolo/fastapi (tag 0.103.0)
 *
 * Key source layout (all in fastapi/):
 *   applications.py            — class FastAPI(Starlette)
 *   routing.py                 — class APIRouter, class APIRoute
 *   dependencies/utils.py      — get_dependant, solve_dependencies
 *   security/http.py           — HTTPBearer, HTTPBasic, HTTPAuthorizationCredentials
 *   security/oauth2.py         — OAuth2PasswordBearer, OAuth2PasswordRequestForm
 *   security/api_key.py        — APIKeyHeader, APIKeyCookie, APIKeyQuery
 *   params.py                  — Query, Path, Body, Header, Cookie, Form, File
 *   exceptions.py              — HTTPException, RequestValidationError
 *   encoders.py                — jsonable_encoder
 *   background.py              — BackgroundTask, BackgroundTasks
 *   middleware/cors.py         — CORSMiddleware
 *   openapi/utils.py           — get_openapi
 *   testclient.py              — TestClient
 */

export const META = {
    id: 'fastapi',
    displayName: 'FastAPI 0.103.0',
    language: 'Python',
    version: '0.103.0',
    url: 'https://github.com/tiangolo/fastapi',
    expectedMinChunks: 150,
    expectedMinFiles: 40,
};

export const QUERIES = [
    // ── EASY ──────────────────────────────────────────────────────────────────

    {
        id: 'FA01',
        query: 'FastAPI',
        difficulty: 'easy',
        topK: 5,
        description: 'Main FastAPI application class extending Starlette',
        expected_names: ['FastAPI'],
        expected_files: ['applications'],
    },
    {
        id: 'FA02',
        query: 'APIRouter',
        difficulty: 'easy',
        topK: 5,
        description: 'Router class for grouping routes and dependencies',
        expected_names: ['APIRouter'],
        expected_files: ['routing'],
    },
    {
        id: 'FA03',
        query: 'HTTPException',
        difficulty: 'easy',
        topK: 5,
        description: 'HTTP exception class with status code and detail',
        expected_names: ['HTTPException'],
        expected_files: ['exceptions'],
    },
    {
        id: 'FA04',
        query: 'jsonable_encoder',
        difficulty: 'easy',
        topK: 5,
        description: 'Encodes Python objects to JSON-compatible structures',
        expected_names: ['jsonable_encoder'],
        expected_files: ['encoders'],
    },
    {
        id: 'FA05',
        query: 'OAuth2PasswordBearer',
        difficulty: 'easy',
        topK: 5,
        description: 'OAuth2 password bearer token dependency',
        expected_names: ['OAuth2PasswordBearer'],
        expected_files: ['security/oauth2'],
    },

    // ── MEDIUM ────────────────────────────────────────────────────────────────

    {
        id: 'FA06',
        query: 'get_dependant parameters function',
        difficulty: 'medium',
        topK: 5,
        description: 'Inspects a function and builds a Dependant object with its params',
        expected_names: ['get_dependant'],
        expected_files: ['dependencies/utils'],
    },
    {
        id: 'FA07',
        query: 'solve_dependencies injection request',
        difficulty: 'medium',
        topK: 5,
        description: 'Resolves all dependencies for a route handler at request time',
        expected_names: ['solve_dependencies'],
        expected_files: ['dependencies/utils'],
    },
    {
        id: 'FA08',
        query: 'HTTPBearer authorization header',
        difficulty: 'medium',
        topK: 5,
        description: 'HTTP Bearer token security scheme extracting Authorization header',
        expected_names: ['HTTPBearer', 'HTTPAuthorizationCredentials'],
        expected_files: ['security/http'],
    },
    {
        id: 'FA09',
        query: 'BackgroundTask async after response',
        difficulty: 'medium',
        topK: 10,
        description: 'Runs a task asynchronously after the response is sent; solve_dependencies collects them, get_request_handler executes them',
        expected_names: ['BackgroundTask', 'BackgroundTasks', 'send_notification', 'solve_dependencies', 'get_request_handler'],
        expected_files: ['background', 'fastapi/routing', 'fastapi/dependencies'],
    },
    {
        id: 'FA10',
        query: 'APIRoute endpoint path method',
        difficulty: 'medium',
        topK: 5,
        description: 'Individual route definition with path, method, and endpoint handler',
        expected_names: ['APIRoute'],
        expected_files: ['routing'],
    },

    // ── HARD ──────────────────────────────────────────────────────────────────

    {
        id: 'FA11',
        query: 'validate request body schema pydantic',
        difficulty: 'hard',
        topK: 10,
        description: 'Request body validation using Pydantic model schemas',
        expected_names: ['Body', 'get_dependant', 'solve_dependencies'],
        expected_files: ['params', 'dependencies'],
    },
    {
        id: 'FA12',
        query: 'generate OpenAPI schema documentation',
        difficulty: 'hard',
        topK: 10,
        description: 'Generates the OpenAPI JSON schema from the registered routes',
        expected_names: ['get_openapi', 'openapi'],
        expected_files: ['openapi', 'applications'],
    },
    {
        id: 'FA13',
        query: 'API key header cookie query authentication',
        difficulty: 'hard',
        topK: 10,
        description: 'Security dependencies that extract API keys from headers, cookies, or query params',
        expected_names: ['APIKeyHeader', 'APIKeyCookie', 'APIKeyQuery'],
        expected_files: ['security/api_key'],
    },
    {
        id: 'FA14',
        query: 'path operation decorator route registration',
        difficulty: 'hard',
        topK: 10,
        description: 'The mechanism that registers a path operation (GET/POST/etc.) handler',
        expected_names: ['add_api_route', 'get', 'post'],
        expected_files: ['routing', 'applications'],
    },

    // ── SEMANTIC — agent-style conceptual queries ──────────────────────────────

    {
        id: 'FA15',
        query: 'extract bearer token from Authorization header and pass to route handler for authentication',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent describing OAuth2 bearer auth behavior without naming the class',
        expected_names: ['HTTPBearer', 'OAuth2PasswordBearer'],
        expected_files: ['security'],
    },
    {
        id: 'FA16',
        query: 'run a function asynchronously after the HTTP response has been sent to the client',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent describing background task behavior without naming BackgroundTask',
        expected_names: ['BackgroundTask', 'BackgroundTasks'],
        expected_files: ['background'],
    },
    {
        id: 'FA17',
        query: 'Extracting and parsing query string parameters from the requested URL with automatic type conversion',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for Query parameter extraction',
        expected_names: ['Query'],
        expected_files: ['params'],
    },
    {
        id: 'FA18',
        query: 'Middleware that allows web browsers from different domains to make API requests securely avoiding origin errors',
        difficulty: 'semantic',
        topK: 10,
        description: 'Conceptual search for CORS configuration',
        expected_names: ['CORSMiddleware'],
        expected_files: ['middleware/cors'],
    },
    {
        id: 'FA19',
        query: 'Injecting reusable logic like database connections into route handlers automatically before execution',
        difficulty: 'semantic',
        topK: 10,
        description: 'Describing the dependency injection engine',
        expected_names: ['Depends', 'get_dependant', 'solve_dependencies'],
        expected_files: ['dependencies/utils'],
    },
    {
        id: 'FA20',
        query: 'Creating a grouped set of API endpoints under a common URL prefix like v1 or v2',
        difficulty: 'semantic',
        topK: 10,
        description: 'Searching for APIRouter behavior',
        expected_names: ['APIRouter'],
        expected_files: ['routing'],
    },
    {
        id: 'FA21',
        query: 'Returning a structured error payload to the client when validation rules fail',
        difficulty: 'semantic',
        topK: 10,
        description: 'Looking for HTTP exception handling',
        expected_names: ['HTTPException', 'RequestValidationError'],
        expected_files: ['exceptions'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    { id: 'HO-FA1', query: 'jsonable_encoder', difficulty: 'easy', expected_names: ['jsonable_encoder'], heldOut: true },
    { id: 'HO-FA2', query: 'convert a pydantic model or dataclass into JSON-serialisable primitives', difficulty: 'semantic', topK: 10, expected_names: ['jsonable_encoder'], heldOut: true },
    { id: 'HO-FA3', query: 'solve_dependencies', difficulty: 'medium', expected_names: ['solve_dependencies'], heldOut: true },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "FA22",
        query: "OAuth2PasswordRequestForm",
        difficulty: "easy",
        topK: 5,
        description: "Form dependency collecting username/password/scope from an OAuth2 password-flow login request",
        expected_names: ["OAuth2PasswordRequestForm"],
        expected_files: ["security/oauth2"],
    },
    {
        id: "FA23",
        query: "declare a form field and an uploaded file in a multipart request body",
        difficulty: "medium",
        topK: 10,
        description: "Parameter markers for multipart form-data: Form fields plus File/UploadFile uploads",
        expected_names: ["Form","File","UploadFile"],
        expected_files: ["params","param_functions","datastructures"],
    },
    {
        id: "FA24",
        query: "swagger UI and redoc HTML documentation pages",
        difficulty: "medium",
        topK: 5,
        description: "Builders that render the interactive Swagger UI and ReDoc HTML docs pages",
        expected_names: ["get_swagger_ui_html","get_redoc_html"],
        expected_files: ["openapi/docs"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-FA4",
        query: "create_access_token",
        difficulty: "easy",
        topK: 5,
        description: "Encodes a JWT access token with an expiry claim from a data payload",
        expected_names: ["create_access_token"],
        expected_files: ["security/tutorial004","security/tutorial005"],
        heldOut: true,
    },
    {
        id: "HO-FA5",
        query: "get_current_active_user",
        difficulty: "easy",
        topK: 5,
        description: "Dependency that returns the authenticated user and rejects disabled accounts",
        expected_names: ["get_current_active_user"],
        expected_files: ["security/tutorial003","security/tutorial004","security/tutorial005"],
        heldOut: true,
    },
    {
        id: "HO-FA6",
        query: "get_authorization_scheme_param",
        difficulty: "easy",
        topK: 5,
        description: "Splits an Authorization header value into its scheme and credentials parts",
        expected_names: ["get_authorization_scheme_param"],
        expected_files: ["security/utils"],
        heldOut: true,
    },
    {
        id: "HO-FA7",
        query: "include_router prefix tags",
        difficulty: "easy",
        topK: 5,
        description: "Mounts an APIRouter's routes onto an app or parent router under a prefix",
        expected_names: ["include_router"],
        expected_files: ["applications","routing"],
        heldOut: true,
    },
    {
        id: "HO-FA8",
        query: "run_endpoint_function call sync or async handler",
        difficulty: "medium",
        topK: 5,
        description: "Invokes the path-operation function, awaiting coroutines or offloading sync functions to a threadpool",
        expected_names: ["run_endpoint_function"],
        expected_files: ["routing"],
        heldOut: true,
    },
    {
        id: "HO-FA9",
        query: "serialize and validate response model before sending",
        difficulty: "medium",
        topK: 5,
        description: "Coerces the handler's return value through the response field and jsonable_encoder",
        expected_names: ["serialize_response"],
        expected_files: ["routing"],
        heldOut: true,
    },
    {
        id: "HO-FA10",
        query: "WebSocket endpoint accept connection receive and send messages",
        difficulty: "medium",
        topK: 10,
        description: "WebSocket route handler plus the WebSocket connection primitive and disconnect signal",
        expected_names: ["websocket_endpoint","WebSocket","WebSocketDisconnect"],
        expected_files: ["websockets","fastapi/websockets"],
        heldOut: true,
    },
    {
        id: "HO-FA11",
        query: "common_parameters shared query dependency",
        difficulty: "medium",
        topK: 10,
        description: "Reusable dependency supplying common pagination/query params, as a function and as a class",
        expected_names: ["common_parameters","CommonQueryParams"],
        expected_files: ["dependencies","dependency_testing"],
        heldOut: true,
    },
    {
        id: "HO-FA12",
        query: "application settings loaded from environment variables",
        difficulty: "medium",
        topK: 5,
        description: "Pydantic settings class reading configuration from the environment",
        expected_names: ["Settings"],
        expected_files: ["settings"],
        heldOut: true,
    },
    {
        id: "HO-FA13",
        query: "redirect the client to another URL and stream a large response body in chunks",
        difficulty: "medium",
        topK: 10,
        description: "Response classes for HTTP redirects and chunked streaming output",
        expected_names: ["RedirectResponse","StreamingResponse"],
        expected_files: ["responses"],
        heldOut: true,
    },
    {
        id: "HO-FA14",
        query: "verify username and password against the database and issue a signed token on login",
        difficulty: "hard",
        topK: 10,
        description: "Intent->identifier: the credential-check helper and the token-issuing login route in the JWT tutorial",
        expected_names: ["authenticate_user","create_access_token","login_for_access_token"],
        expected_files: ["security/tutorial004","security/tutorial005"],
        heldOut: true,
    },
    {
        id: "HO-FA15",
        query: "decode the bearer token, look up the user it identifies, and reject invalid credentials",
        difficulty: "hard",
        topK: 10,
        description: "Intent->identifier: the dependency that resolves the current user from a token without naming it",
        expected_names: ["get_current_user","fake_decode_token"],
        expected_files: ["security"],
        heldOut: true,
    },
    {
        id: "HO-FA16",
        query: "build the OpenAPI path item and security definitions for each registered route",
        difficulty: "hard",
        topK: 10,
        description: "Cross-cutting OpenAPI generation internals that walk routes into the schema",
        expected_names: ["get_openapi_path","get_openapi_security_definitions","get_openapi"],
        expected_files: ["openapi/utils"],
        heldOut: true,
    },
    {
        id: "HO-FA17",
        query: "parse the incoming request body into the declared parameters and report validation errors",
        difficulty: "hard",
        topK: 10,
        description: "Intent->identifier: the dependency-resolution helper that maps request body to handler args",
        expected_names: ["request_body_to_args","request_params_to_args"],
        expected_files: ["dependencies/utils"],
        heldOut: true,
    },
    {
        id: "HO-FA18",
        query: "run a blocking synchronous function in a worker thread so it does not block the event loop",
        difficulty: "semantic",
        topK: 10,
        description: "Intent->identifier: the concurrency helper that offloads sync work to a threadpool",
        expected_names: ["run_in_threadpool"],
        expected_files: ["concurrency"],
        heldOut: true,
    },
    {
        id: "HO-FA19",
        query: "measure request handling time and add it as a custom response header via middleware",
        difficulty: "semantic",
        topK: 10,
        description: "Intent->identifier: the timing middleware example without naming the function",
        expected_names: ["add_process_time_header"],
        expected_files: ["middleware/tutorial001"],
        heldOut: true,
    },
    {
        id: "HO-FA20",
        query: "subclass the route class to customize request parsing and decode gzip bodies",
        difficulty: "semantic",
        topK: 10,
        description: "Custom APIRoute subclasses overriding the route handler for bespoke request behavior",
        expected_names: ["GzipRoute","TimedRoute","ValidationErrorLoggingRoute"],
        expected_files: ["custom_request_and_route"],
        heldOut: true,
    },
];
