/**
 * test/suites/gin.mjs
 *
 * Ground-truth query set for Gin v1.9.1 (Go).
 * Source: https://github.com/gin-gonic/gin (tag v1.9.1)
 *
 * Key source layout (Go files in repo root):
 *   gin.go           — type Engine struct, New(), Default(), Run(), RunTLS()
 *   routergroup.go   — type RouterGroup struct, GET, POST, PUT, DELETE, Use,
 *                        Group, calculateAbsolutePath
 *   context.go       — type Context struct, JSON, String, HTML, Redirect, Abort,
 *                        BindJSON, ShouldBindJSON, Param, Query, PostForm, ...
 *   tree.go          — type methodTree / node, addRoute, getValue (radix tree)
 *   middleware.go    — Logger(), LoggerWithConfig(), Recovery()
 *   auth.go          — BasicAuth(), BasicAuthForProxy()
 *   errors.go        — type Error struct, Error.Error()
 *   utils.go         — joinPaths, lastChar, parseAccept, ...
 *   render/
 *     json.go        — type JSON / SecureJSON render
 *     html.go        — type HTML render
 */

export const META = {
    id: 'gin',
    displayName: 'Gin v1.9.1',
    language: 'Go',
    version: 'v1.9.1',
    url: 'https://github.com/gin-gonic/gin',
    expectedMinChunks: 80,
    expectedMinFiles: 20,
};

export const QUERIES = [
    // ── EASY ──────────────────────────────────────────────────────────────────

    {
        id: 'GN01',
        query: 'Engine',
        difficulty: 'easy',
        topK: 5,
        description: 'Gin Engine struct — the top-level HTTP engine and router',
        expected_names: ['Engine', 'New', 'Default'],
        expected_files: ['gin.go'],
    },
    {
        id: 'GN02',
        query: 'RouterGroup',
        difficulty: 'easy',
        topK: 5,
        description: 'RouterGroup — groups routes under a common path prefix',
        expected_names: ['RouterGroup'],
        expected_files: ['routergroup'],
    },
    {
        id: 'GN03',
        query: 'Recovery panic',
        difficulty: 'easy',
        topK: 5,
        description: 'Recovery middleware that catches panics and returns 500',
        expected_names: ['Recovery'],
        expected_files: ['middleware'],
    },
    {
        id: 'GN04',
        query: 'BasicAuth',
        difficulty: 'easy',
        topK: 5,
        description: 'Built-in HTTP Basic Authentication middleware',
        expected_names: ['BasicAuth'],
        expected_files: ['auth'],
    },

    // ── MEDIUM ────────────────────────────────────────────────────────────────

    {
        id: 'GN05',
        query: 'Context JSON response write',
        difficulty: 'medium',
        topK: 5,
        description: 'Context.JSON() — serialises a struct and writes a JSON response; WriteJSON is the underlying renderer',
        expected_names: ['JSON', 'WriteJSON'],
        expected_files: ['context', 'render/json'],
    },
    {
        id: 'GN06',
        query: 'ShouldBindJSON bind request body',
        difficulty: 'medium',
        topK: 5,
        description: 'Context.ShouldBindJSON() — decodes the JSON request body into a struct',
        expected_names: ['ShouldBindJSON', 'ShouldBind', 'BindJSON'],
        expected_files: ['context'],
    },
    {
        id: 'GN07',
        query: 'Logger middleware request log',
        difficulty: 'medium',
        topK: 5,
        description: 'Logger middleware that prints a structured access log for each request',
        expected_names: ['Logger', 'LoggerWithConfig', 'LoggerWithWriter'],
        expected_files: ['middleware'],
    },
    {
        id: 'GN08',
        query: 'GET POST route handler register',
        difficulty: 'medium',
        topK: 5,
        description: 'RouterGroup methods (GET, POST, etc.) that register route handlers',
        expected_names: ['GET', 'POST', 'Handle', 'handle', 'Any'],
        expected_files: ['routergroup'],
    },
    {
        id: 'GN09',
        query: 'Run listen address port',
        difficulty: 'medium',
        topK: 5,
        description: 'Engine.Run() — starts the HTTP server on the given address',
        expected_names: ['Run'],
        expected_files: ['gin.go'],
    },

    // ── HARD ──────────────────────────────────────────────────────────────────

    {
        id: 'GN10',
        query: 'radix tree route insertion node',
        difficulty: 'hard',
        topK: 10,
        description: 'Internal radix tree that stores and resolves URL routes',
        expected_names: ['addRoute', 'insertChild', 'getValue', 'node'],
        expected_files: ['tree'],
    },
    {
        id: 'GN11',
        query: 'path parameter url segment extract',
        difficulty: 'hard',
        topK: 10,
        description: 'Extracting named parameters (e.g. :id) from the URL path',
        expected_names: ['Param', 'Params', 'getValue'],
        expected_files: ['context', 'tree'],
    },
    {
        id: 'GN12',
        query: 'abort request middleware chain stop',
        difficulty: 'hard',
        topK: 10,
        description: 'Stops execution of remaining handlers in the middleware chain',
        expected_names: ['Abort', 'AbortWithStatus', 'AbortWithError'],
        expected_files: ['context'],
    },
    {
        id: 'GN13',
        query: 'group route prefix middleware use',
        difficulty: 'hard',
        topK: 10,
        description: 'Creates a route group with shared prefix and middleware',
        expected_names: ['Group', 'Use'],
        expected_files: ['routergroup'],
    },
    {
        id: 'GN14',
        query: 'Extracting string data submitted via an HTML form POST request safely',
        difficulty: 'semantic',
        topK: 10,
        description: 'Conceptual search for form parsing methods',
        expected_names: ['PostForm', 'DefaultPostForm'],
        expected_files: ['context'],
    },
    {
        id: 'GN15',
        query: 'Safely recovering from a runtime crash to prevent the entire web server process from dying',
        difficulty: 'semantic',
        topK: 10,
        description: 'Agent looking for the panic recovery middleware',
        expected_names: ['Recovery', 'RecoveryWithWriter'],
        expected_files: ['middleware'],
    },
    {
        id: 'GN16',
        query: 'Writing an HTTP response containing HTML rendered from a predefined template file',
        difficulty: 'semantic',
        topK: 10,
        description: 'Searching for HTML rendering engine integration',
        expected_names: ['HTML'],
        expected_files: ['context', 'render/html'],
    },
    {
        id: 'GN17',
        query: 'Creating the central application object that holds all route definitions and global settings',
        difficulty: 'semantic',
        topK: 10,
        description: 'Finding the Engine factory',
        expected_names: ['New', 'Default', 'Engine'],
        expected_files: ['gin.go'],
    },
    {
        id: 'GN18',
        query: 'Grouping multiple API endpoints under a shared version path to apply middleware to all of them',
        difficulty: 'semantic',
        topK: 10,
        description: 'Looking for routing group abstraction',
        expected_names: ['Group', 'RouterGroup'],
        expected_files: ['routergroup'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    { id: 'HO-GN1', query: 'RunTLS', difficulty: 'easy', expected_names: ['RunTLS'], heldOut: true },
    { id: 'HO-GN2', query: 'join two URL path segments while preserving a trailing slash', difficulty: 'semantic', topK: 10, expected_names: ['joinPaths'], heldOut: true },
    { id: 'HO-GN3', query: 'SecureJSON', difficulty: 'easy', expected_names: ['SecureJSON'], heldOut: true },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "GN19",
        query: "ServeHTTP entrypoint dispatch request to handler",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Engine.ServeHTTP — the net/http entrypoint that pulls a Context from the pool and dispatches the request; handleHTTPRequest does the actual routing",
        expected_names: ["ServeHTTP","handleHTTPRequest"],
        expected_files: ["gin.go"],
    },
    {
        id: "GN20",
        query: "ClientIP",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Context.ClientIP — resolves the originating client IP, honoring trusted proxy headers",
        expected_names: ["ClientIP"],
        expected_files: ["context.go"],
    },
    {
        id: "GN21",
        query: "call the next handler in the middleware chain",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Context.Next advances the handler index and invokes remaining handlers; combineHandlers builds the chain",
        expected_names: ["Next","combineHandlers"],
        expected_files: ["context.go","routergroup.go"],
    },
    {
        id: "GN22",
        query: "serve static files from a directory on disk",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "RouterGroup static-file serving: Static/StaticFS register a directory, createStaticHandler builds the file-serving handler",
        expected_names: ["Static","StaticFS","createStaticHandler"],
        expected_files: ["routergroup.go"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-GN4",
        query: "Negotiate",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Context.Negotiate — content negotiation that picks a render format based on the Accept header",
        expected_names: ["Negotiate","NegotiateFormat"],
        expected_files: ["context.go"],
        heldOut: true,
    },
    {
        id: "HO-GN5",
        query: "validate that a request comes from a trusted reverse proxy before trusting forwarded headers",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Trusted-proxy machinery on Engine: SetTrustedProxies configures CIDRs, isTrustedProxy checks an IP, validateHeader reads X-Forwarded-For",
        expected_names: ["SetTrustedProxies","isTrustedProxy","validateHeader"],
        expected_files: ["gin.go"],
        heldOut: true,
    },
    {
        id: "HO-GN6",
        query: "save an uploaded multipart file to disk",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Context multipart upload handling: SaveUploadedFile copies an uploaded file to a destination; FormFile/MultipartForm read the upload",
        expected_names: ["SaveUploadedFile","FormFile","MultipartForm"],
        expected_files: ["context.go"],
        heldOut: true,
    },
    {
        id: "HO-GN7",
        query: "Render interface WriteContentType",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "The render.Render interface and the shared writeContentType helper that sets the Content-Type header for renderers",
        expected_names: ["Render","WriteContentType","writeContentType"],
        expected_files: ["render/render.go","render/json.go"],
        heldOut: true,
    },
    {
        id: "HO-GN8",
        query: "set a cookie on the HTTP response",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Context.SetCookie writes a Set-Cookie header; Cookie reads it back",
        expected_names: ["SetCookie","Cookie"],
        expected_files: ["context.go"],
        heldOut: true,
    },
    {
        id: "HO-GN9",
        query: "longestCommonPrefix",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "tree.go radix-tree helper computing the longest common prefix between two path strings during insertion",
        expected_names: ["longestCommonPrefix"],
        expected_files: ["tree.go"],
        heldOut: true,
    },
    {
        id: "HO-GN10",
        query: "redirect to the canonical path when a trailing slash mismatches",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Engine path-fixup redirects: redirectTrailingSlash and redirectFixedPath issue 301/307 to the corrected URL; cleanPath normalizes it",
        expected_names: ["redirectTrailingSlash","redirectFixedPath","cleanPath"],
        expected_files: ["gin.go","path.go"],
        heldOut: true,
    },
    {
        id: "HO-GN11",
        query: "resolve the listen address falling back to the PORT environment variable",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "utils.resolveAddress derives the bind address from args or the PORT env var, used by Run",
        expected_names: ["resolveAddress"],
        expected_files: ["utils.go"],
        heldOut: true,
    },
    {
        id: "HO-GN12",
        query: "render JSONP with a callback wrapper",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Context.JSONP serializes JSON wrapped in a JavaScript callback for cross-origin scripts",
        expected_names: ["JSONP"],
        expected_files: ["context.go"],
        heldOut: true,
    },
    {
        id: "HO-GN13",
        query: "HTMLProduction HTMLDebug template render engine",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "render HTML engines: HTMLProduction/HTMLDebug implement HTMLRender, producing a Render instance per request via Instance",
        expected_names: ["HTMLProduction","HTMLDebug","HTMLRender","Instance"],
        expected_files: ["render/html.go"],
        heldOut: true,
    },
    {
        id: "HO-GN14",
        query: "the most recent error attached to the request context",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "errors.go: errorMsgs.Last returns the last collected error; Error.Error renders the message",
        expected_names: ["Last","Error"],
        expected_files: ["errors.go"],
        heldOut: true,
    },
    {
        id: "HO-GN15",
        query: "combine a group prefix with a relative route path",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "RouterGroup.calculateAbsolutePath joins the group base path with a relative path when registering routes",
        expected_names: ["calculateAbsolutePath"],
        expected_files: ["routergroup.go"],
        heldOut: true,
    },
    {
        id: "HO-GN16",
        query: "read the raw request body bytes",
        kind: "nl",
        difficulty: "medium",
        topK: 5,
        description: "Context.GetRawData reads the entire request body into a byte slice",
        expected_names: ["GetRawData"],
        expected_files: ["context.go"],
        heldOut: true,
    },
    {
        id: "HO-GN17",
        query: "stream a response body progressively to the client",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Context.Stream writes chunked output via a step callback; SSEvent emits server-sent events",
        expected_names: ["Stream","SSEvent"],
        expected_files: ["context.go"],
        heldOut: true,
    },
];
