/**
 * test/suites/react.mjs
 *
 * Ground-truth query set for a subset of react-bootstrap (TypeScript/React).
 * Source: https://github.com/react-bootstrap/react-bootstrap
 *
 * Key source layout (one component/util per .tsx/.ts file at the fixture root):
 *   Modal.tsx              — Modal overlay dialog (focus trap, backdrop, onHide)
 *   Overlay.tsx            — Overlay positioning wrapper over popper (wrapRefs,
 *                              clearPopperCache); OverlayTrigger.tsx adds
 *                              hover/focus triggers (normalizeDelay, handleMouseOverOut)
 *   Dropdown.tsx           — Dropdown + Toggle/Menu; DropdownMenu.tsx has
 *                              getDropdownMenuPlacement
 *   Button.tsx             — clickable button styled by variant/size props
 *   Carousel.tsx           — slideshow with prev/next; isVisible helper
 *   Collapse.tsx           — expand/collapse height/width transition
 *                              (MARGINS, getDefaultDimensionValue, collapseStyles)
 *   ProgressBar.tsx        — progress bar (getPercentage, renderProgressBar)
 *   ThemeProvider.tsx      — ThemeContext + useBootstrapPrefix / useBootstrapBreakpoints
 *                              / useBootstrapMinBreakpoint / useIsRTL / createBootstrapComponent
 *   createWithBsPrefix.tsx — HOC that resolves a bootstrap class prefix
 *   createChainedFunction.tsx — compose multiple callbacks into one
 *   useAccordionButton.ts  — hook returning the accordion toggle handler
 *   helpers.ts             — getOverlayDirection (placement → bs direction)
 */

export const META = {
    id: 'react',
    displayName: 'react-bootstrap (subset)',
    language: 'TypeScript/React',
    version: 'subset',
    url: 'https://github.com/react-bootstrap/react-bootstrap',
    expectedMinChunks: 200,
    expectedMinFiles: 100,
};

export const QUERIES = [
    // ── EASY (symbolic name lookup) ─────────────────────────────────────────────

    {
        id: 'RB01',
        query: 'Dropdown',
        difficulty: 'easy',
        topK: 5,
        description: 'Dropdown component — toggle button that reveals a menu',
        expected_names: ['Dropdown'],
        expected_files: ['Dropdown'],
    },
    {
        id: 'RB02',
        query: 'progress bar percentage now min max striped',
        difficulty: 'easy',
        topK: 5,
        description: 'ProgressBar component visualising completion as a filled bar',
        expected_names: ['ProgressBar'],
        expected_files: ['ProgressBar'],
    },

    // ── MEDIUM (keyword lookup) ─────────────────────────────────────────────────

    {
        id: 'RB04',
        query: 'dropdown toggle menu context show',
        difficulty: 'medium',
        topK: 5,
        description: 'Dropdown with its toggle and menu sub-components (seed: react/dropdown)',
        expected_names: ['Dropdown', 'DropdownToggle', 'DropdownMenu'],
        expected_files: ['Dropdown'],
    },
    {
        id: 'RB05',
        query: 'modal dialog backdrop show onHide focus',
        difficulty: 'medium',
        topK: 5,
        description: 'Modal component and its dialog/body sub-components',
        expected_names: ['Modal', 'ModalDialog', 'ModalBody'],
        expected_files: ['Modal'],
    },
    {
        id: 'RB06',
        query: 'overlay trigger tooltip popover placement',
        difficulty: 'medium',
        topK: 5,
        description: 'Overlay/OverlayTrigger that positions a tooltip or popover',
        expected_names: ['Overlay', 'OverlayTrigger', 'Tooltip', 'Popover'],
        expected_files: ['Overlay'],
    },

    // ── HARD / SEMANTIC (behavioural — target symbol NOT named) ──────────────────

    {
        id: 'RB08',
        query: 'render an overlay dialog that traps focus and can be dismissed by the user',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Behavioural search for the modal dialog (seed: react/modal-overlay)',
        expected_names: ['Modal'],
        expected_files: ['Modal'],
    },
    {
        id: 'RB09',
        query: 'a clickable element styled by a colour variant and a size prop',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Behavioural search for the button component (seed: react/button-variant)',
        expected_names: ['Button'],
        expected_files: ['Button'],
    },
    {
        id: 'RB10',
        query: 'animate an element expanding and shrinking by transitioning its height or width',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Behavioural search for the collapse transition component',
        expected_names: ['Collapse', 'getDefaultDimensionValue', 'collapseStyles'],
        expected_files: ['Collapse'],
    },
    {
        id: 'RB11',
        query: 'compose several optional callbacks into a single handler that invokes each one in order',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Cross-cutting utility used by transitions to chain event handlers',
        expected_names: ['createChainedFunction'],
        expected_files: ['createChainedFunction'],
    },
    {
        id: 'RB12',
        query: 'resolve the css class prefix for a component, falling back to a theme-provided default',
        kind: 'xc',
        difficulty: 'hard',
        topK: 10,
        description: 'Cross-cutting bsPrefix resolution shared across components',
        expected_names: ['useBootstrapPrefix', 'createWithBsPrefix'],
        expected_files: ['ThemeProvider', 'createWithBsPrefix'],
    },

    // ── HELD-OUT (validation only — never used to tune ranking) ──
    {
        id: 'HO-RB1',
        query: 'a hook that returns the click handler which toggles which accordion panel is open',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Held-out: accordion toggle hook',
        expected_names: ['useAccordionButton'],
        expected_files: ['useAccordionButton'],
        heldOut: true,
    },
    {
        id: 'HO-RB2',
        query: 'getDropdownMenuPlacement',
        difficulty: 'easy',
        topK: 5,
        description: 'Held-out: compute the popper placement for a dropdown menu given drop/align direction',
        expected_names: ['getDropdownMenuPlacement'],
        expected_files: ['DropdownMenu'],
        heldOut: true,
    },
    {
        id: 'HO-RB3',
        query: 'convert a current value into a percentage between a minimum and maximum bound',
        kind: 'nl',
        difficulty: 'semantic',
        topK: 10,
        description: 'Held-out: progress percentage helper',
        expected_names: ['getPercentage'],
        expected_files: ['ProgressBar'],
        heldOut: true,
    },

    // EXPANDED-QUERIES-V2 — benchmark-power upgrade: expanded ground truth (n↑).
    // ── EXPANDED TUNING ───────────────────────────────────────────────────────
    {
        id: "RB13",
        query: "wrapRefs",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Overlay helper that merges the outer ref and arrow ref into popper props",
        expected_names: ["wrapRefs"],
        expected_files: ["Overlay"],
    },
    {
        id: "RB14",
        query: "normalizeDelay",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "OverlayTrigger helper normalizing a show/hide delay into an object",
        expected_names: ["normalizeDelay"],
        expected_files: ["OverlayTrigger"],
    },
    {
        id: "RB15",
        query: "createUtilityClassName responsive breakpoint utility classes",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Build responsive bootstrap utility class names per breakpoint",
        expected_names: ["createUtilityClassName"],
        expected_files: ["createUtilityClasses"],
    },
    {
        id: "RB16",
        query: "carousel slideshow previous next slide interval pause",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Carousel slideshow component cycling through slides",
        expected_names: ["Carousel"],
        expected_files: ["Carousel"],
    },
    {
        id: "RB17",
        query: "tooltip popover overlay positioning components",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Tooltip and Popover overlay content components",
        expected_names: ["Tooltip","Popover"],
        expected_files: ["Tooltip","Popover"],
    },
    {
        id: "RB18",
        query: "hooks reading bootstrap breakpoints and minimum breakpoint from theme context",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Theme hooks exposing breakpoint config",
        expected_names: ["useBootstrapBreakpoints","useBootstrapMinBreakpoint"],
        expected_files: ["ThemeProvider"],
    },
    {
        id: "RB19",
        query: "read the transition duration and delay off an element then fire a callback when the css transition ends",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Parse computed transition timing and attach a transitionend listener",
        expected_names: ["transitionEndListener","parseDuration"],
        expected_files: ["transitionEndListener"],
    },
    {
        id: "RB20",
        query: "force the browser to recalculate layout so the next animation actually runs",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Trigger a synchronous reflow by reading offsetHeight",
        expected_names: ["triggerBrowserReflow"],
        expected_files: ["triggerBrowserReflow"],
    },
    {
        id: "RB21",
        query: "iterate only the valid react element children and find whether one of a given type is present",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Children-iteration helpers operating on valid elements",
        expected_names: ["map","forEach","hasChildOfType"],
        expected_files: ["ElementChildren"],
    },
    {
        id: "RB22",
        query: "map a bootstrap placement string to a start or end direction taking right-to-left into account",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Convert placement to bs direction honoring RTL",
        expected_names: ["getOverlayDirection"],
        expected_files: ["helpers"],
    },
    {
        id: "RB23",
        query: "compute the initial off-screen popper styles before it has been positioned",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Initial hidden absolute styles for a popper element",
        expected_names: ["getInitialPopperStyles"],
        expected_files: ["getInitialPopperStyles"],
    },
    {
        id: "RB24",
        query: "hook computing the popover and tooltip offset modifier for an overlay",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "useOverlayOffset returns popper offset modifier",
        expected_names: ["useOverlayOffset"],
        expected_files: ["useOverlayOffset"],
    },
    // ── EXPANDED HELD-OUT (validation only — frozen, never tuned) ──────────────
    {
        id: "HO-RB4",
        query: "clearPopperCache",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: reset cached popper offsets/styles on the overlay ref",
        expected_names: ["clearPopperCache"],
        expected_files: ["Overlay"],
        heldOut: true,
    },
    {
        id: "HO-RB5",
        query: "handleMouseOverOut",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: OverlayTrigger guard firing handlers only when pointer leaves the element tree",
        expected_names: ["handleMouseOverOut"],
        expected_files: ["OverlayTrigger"],
        heldOut: true,
    },
    {
        id: "HO-RB6",
        query: "getTabTransitionComponent",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: resolve a tab transition component from a boolean or component",
        expected_names: ["getTabTransitionComponent"],
        expected_files: ["getTabTransitionComponent"],
        heldOut: true,
    },
    {
        id: "HO-RB7",
        query: "isAccordionItemSelected",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: test whether an accordion item's eventKey is currently active",
        expected_names: ["isAccordionItemSelected"],
        expected_files: ["AccordionContext"],
        heldOut: true,
    },
    {
        id: "HO-RB8",
        query: "renderProgressBar",
        kind: "sym",
        difficulty: "easy",
        topK: 5,
        description: "Held-out: render a single progress bar element with width from percentage",
        expected_names: ["renderProgressBar"],
        expected_files: ["ProgressBar"],
        heldOut: true,
    },
    {
        id: "HO-RB9",
        query: "switch toggle form check styled as a sliding switch",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: Switch is a FormCheck rendered as a switch",
        expected_names: ["Switch"],
        expected_files: ["Switch"],
        heldOut: true,
    },
    {
        id: "HO-RB10",
        query: "spinner loading indicator animation border grow variant",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: Spinner loading indicator component",
        expected_names: ["Spinner"],
        expected_files: ["Spinner"],
        heldOut: true,
    },
    {
        id: "HO-RB11",
        query: "fade transition opacity component and its style map",
        kind: "kw",
        difficulty: "medium",
        topK: 10,
        description: "Held-out: Fade transition plus its per-state styles",
        expected_names: ["Fade","fadeStyles"],
        expected_files: ["Fade"],
        heldOut: true,
    },
    {
        id: "HO-RB12",
        query: "toast container position classes for placement on the screen",
        kind: "kw",
        difficulty: "medium",
        topK: 5,
        description: "Held-out: ToastContainer placement-to-class lookup",
        expected_names: ["positionClasses"],
        expected_files: ["ToastContainer"],
        heldOut: true,
    },
    {
        id: "HO-RB13",
        query: "hook that detects right-to-left layout direction from the theme",
        kind: "nl",
        difficulty: "medium",
        topK: 10,
        description: "Held-out: useIsRTL reads dir from theme context",
        expected_names: ["useIsRTL"],
        expected_files: ["ThemeProvider"],
        heldOut: true,
    },
    {
        id: "HO-RB14",
        query: "singleton accessor returning a shared modal manager that handles scrollbar padding and stacking",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: getSharedManager lazily creates the BootstrapModalManager",
        expected_names: ["getSharedManager","BootstrapModalManager"],
        expected_files: ["BootstrapModalManager"],
        heldOut: true,
    },
    {
        id: "HO-RB15",
        query: "wrap a forwarded ref and warn in development when it resolves to a class instance instead of a dom node",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: useWrappedRefWithWarning dev-mode ref guard",
        expected_names: ["useWrappedRefWithWarning"],
        expected_files: ["useWrappedRefWithWarning"],
        heldOut: true,
    },
    {
        id: "HO-RB16",
        query: "return the inline style giving an element its collapsing height or width during the transition",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: Collapse dimension-value helper and per-state styles",
        expected_names: ["getDefaultDimensionValue","collapseStyles"],
        expected_files: ["Collapse"],
        heldOut: true,
    },
    {
        id: "HO-RB17",
        query: "pick the default active tab key by scanning children for the first one not disabled",
        kind: "nl",
        difficulty: "hard",
        topK: 10,
        description: "Held-out: Tabs default active key resolution and per-child render",
        expected_names: ["getDefaultActiveKey","renderTab"],
        expected_files: ["Tabs"],
        heldOut: true,
    },
    {
        id: "HO-RB18",
        query: "build the responsive grid column class names and span metadata from breakpoint props",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: useCol computes column spans/offsets/order per breakpoint",
        expected_names: ["useCol"],
        expected_files: ["useCol"],
        heldOut: true,
    },
    {
        id: "HO-RB19",
        query: "convert a numeric aspect ratio into a css percentage string",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: Ratio toPercent helper",
        expected_names: ["toPercent"],
        expected_files: ["Ratio"],
        heldOut: true,
    },
    {
        id: "HO-RB20",
        query: "hook composing placeholder animation, size and background-color classes for skeleton loading",
        kind: "nl",
        difficulty: "semantic",
        topK: 10,
        description: "Held-out: usePlaceholder builds placeholder class names",
        expected_names: ["usePlaceholder"],
        expected_files: ["usePlaceholder"],
        heldOut: true,
    },
];
