/**
 * graph-indexer 2.x for the `cc+v2` arm, installed as its `init` left a repository: its own index
 * (idx-index), its MCP server over it, and CLAUDE.md importing the assembled prompt suite (Layer 1
 * CORE.md plus the language and framework playbooks of the repository's stack) and the domain
 * template. The 2.x tree is a checkout of the last 2.x release with its dependencies installed:
 *
 *   git worktree add --detach "$GI_V2" v2.1.1 && (cd "$GI_V2" && npm ci)
 */
import fs from 'node:fs';
import path from 'node:path';
import { WORK } from './lib.mjs';
import { buildIndexV2 as build } from '../v2-client.mjs';

export const V2_ROOT = path.resolve(process.env.GI_V2 ?? path.join(WORK, 'v2'));

/** The playbooks 2.x `init` selects for each benchmark repository's stack. */
const STACKS = {
    nestjs: { languages: ['JAVASCRIPT_TYPESCRIPT'], frameworks: ['NODE_EXPRESS_NESTJS'] },
    twenty: { languages: ['JAVASCRIPT_TYPESCRIPT'], frameworks: ['NODE_EXPRESS_NESTJS', 'REACT'] },
    caddy: { languages: ['GO'], frameworks: [] },
};

function need() {
    if (!fs.existsSync(path.join(V2_ROOT, 'mcp-server.mjs'))) throw new Error(`graph-indexer 2.x not found at ${V2_ROOT} (set GI_V2)`);
}

/** Build the 2.x index of a checkout (lexical defaults, as `init` builds it); returns the milliseconds. */
export function buildIndexV2(dir) {
    need();
    const t0 = Date.now();
    build(V2_ROOT, dir);
    return Date.now() - t0;
}

/** The MCP server entry 2.x `init` writes. */
export function serverV2(checkout) {
    need();
    return { command: process.execPath, args: [path.join(V2_ROOT, 'mcp-server.mjs'), '--repo', checkout], env: { MCP_PROJECT_ROOT: checkout } };
}

/** What 2.x `init` writes for Claude Code into a project: file name → content. */
export function projectFilesV2(repo) {
    need();
    const stack = STACKS[repo];
    if (!stack) throw new Error(`no 2.x stack recorded for ${repo} (bench/agentic/v2.mjs)`);
    const layer = (rel) => fs.readFileSync(path.join(V2_ROOT, 'prompts', rel), 'utf8').trim();
    const files = ['CORE.md', ...stack.languages.map(l => `languages/${l}.md`), ...stack.frameworks.map(f => `frameworks/${f}.md`)];
    const header = [
        '<!--',
        '  GRAPH_INDEXER_PROMPT.md — generated by `npx graph-indexer init`. Do not edit:',
        '  re-run init after changing languages or frameworks to regenerate.',
        `  Layers: ${files.map(f => path.basename(f, '.md').toLowerCase()).join(' + ')}`,
        '  Project-specific rules (Layer 3) belong in GRAPH_INDEXER_DOMAIN.md.',
        '-->',
    ].join('\n');
    return {
        'GRAPH_INDEXER_PROMPT.md': header + '\n\n' + files.map(layer).join('\n\n') + '\n',
        'GRAPH_INDEXER_DOMAIN.md': layer('DOMAIN_TEMPLATE.md') + '\n',
        'CLAUDE.md': '<!-- graph-indexer agent prompt suite (added by `npx graph-indexer init`) -->\n@GRAPH_INDEXER_PROMPT.md\n@GRAPH_INDEXER_DOMAIN.md\n',
    };
}
