#!/usr/bin/env node
/**
 * bench/fixtures-doc.mjs — emit bench/FIXTURES.md: the full reproducibility record
 * for all 18 benchmark fixtures (repo, commit, subdir, chunk/file count). Reads
 * provenance.json (commits, pinned flag) + bench/results/<fx>__L1.json (chunk/file
 * count of the measured index). Unpinnable fixtures (.git stripped during subdir
 * reduction) are recorded honestly with the reason — no commit is invented.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const RES = path.join(__dirname, 'results');
const prov = JSON.parse(fs.readFileSync(path.join(__dirname, 'provenance.json'), 'utf8'));
const FIX_ORDER = ['axios', 'express-js', 'nestjs', 'react', 'fastapi', 'django', 'gin', 'rust', 'spring', 'android', 'aspnet', 'rails', 'laravel', 'symfony', 'css', 'cjson', 'nvm', 'alamofire'];

function counts(fx) {
    const p = path.join(RES, `${fx}__L1.json`);
    if (!fs.existsSync(p)) return { chunks: '?', files: '?' };
    const c = JSON.parse(fs.readFileSync(p, 'utf8'));
    return { chunks: c.stats?.chunkCount ?? '?', files: c.stats?.fileCount ?? '?' };
}

const L = [];
L.push('# FIXTURES.md — benchmark fixture provenance\n');
L.push('> Generated by `bench/fixtures-doc.mjs` from `bench/provenance.json` + `bench/results/*__L1.json`. The reproducibility record for the 18-fixture matrix (18 fixtures across 14 languages). Commits are the fixture\'s own `git rev-parse HEAD`; fixtures whose `.git` was stripped during subdir reduction are **unpinnable post-hoc** and marked as such — their exact commit cannot be recovered and is not invented.\n');

const pinned = Object.values(prov).filter(p => p.pinned).length;
L.push(`**${pinned}/${Object.keys(prov).length} commit-pinned; ${Object.keys(prov).length - pinned} unpinnable post-hoc.**\n`);

L.push('| Language | fixture | repo | commit | subdir(s) | chunks | files | pinned |');
L.push('|---|---|---|---|---|---|---|---|');
for (const fx of FIX_ORDER) {
    const p = prov[fx]; if (!p) continue;
    const { chunks, files } = counts(fx);
    const subdir = (p.subdirs && p.subdirs.join(',') !== '.') ? '`' + p.subdirs.join('`, `') + '`' : '(repo root)';
    const commit = p.pinned ? '`' + (p.commit || p.ref) + '`' : '**unpinnable** (.git stripped)';
    L.push(`| ${p.language} | ${fx} | [${p.repo.replace('https://github.com/', '')}](${p.repo}) | ${commit} | ${subdir} | ${chunks} | ${files} | ${p.pinned ? '✓' + (p.ref ? ' (' + p.ref + ')' : '') : '✗'} |`);
}

L.push('\n## Unpinnable fixtures — reason & partial reproducibility\n');
const unpinned = FIX_ORDER.filter(fx => prov[fx] && !prov[fx].pinned);
L.push(`The following ${unpinned.length} fixtures were reduced to a language-pure subdir and had \`.git\` stripped, so \`git rev-parse HEAD\` cannot recover the measured commit. They reproduce only up to **repo + subdir + observed chunk/file count** (a clone of today's default branch may differ). This is a stated limitation, not an estimate.\n`);
for (const fx of unpinned) {
    const p = prov[fx]; const { chunks, files } = counts(fx);
    L.push(`- **${fx}** (${p.language}) — ${p.repo}, subdir(s) \`${p.subdirs.join(', ')}\`; measured index = ${chunks} chunks / ${files} files. Commit: unpinnable.`);
}

L.push('\n## Reproduce\n```bash\nnode bench/provenance.mjs   # re-resolve commits from each fixture\'s own .git\nnode bench/fixtures-doc.mjs  # regenerate this file\n```\n');

fs.writeFileSync(path.join(__dirname, '..', 'docs', 'benchmarks', 'FIXTURES.md'), L.join('\n'));
console.log(`wrote docs/benchmarks/FIXTURES.md (${pinned}/${Object.keys(prov).length} pinned)`);
