#!/usr/bin/env node
/**
 * bench/synth-agent.mjs — BENCH_AGENT.md (end-to-end / agent-facing results).
 *
 * Three views, each labelled by how it was obtained:
 *  1. Per-archetype retrieval proxy (nl / kw / xc) — deterministic, derived by
 *     joining strict eval rows (by query id) to each query's `kind`. Strict
 *     rank-1 / s@5 per archetype = "does ranking surface the right symbol for the
 *     way an agent phrased it". No LLM. Available for every language.
 *  2. Token footprint vs naive readFile (bench/results/tokens.json) — per-task.
 *  3. LLM agent-trace (bench/results/agent-trace.json) — real task success +
 *     tool-call counts on a small subset; "not run" elsewhere.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const RES = path.join(__dirname, 'results');
const DOCS = path.join(ROOT, 'docs', 'benchmarks');
const FIX_ORDER = ['axios', 'express-js', 'nestjs', 'react', 'fastapi', 'django', 'gin', 'rust', 'spring', 'android', 'aspnet', 'rails', 'laravel', 'symfony', 'css', 'cjson', 'nvm', 'alamofire'];
const prov = JSON.parse(fs.readFileSync(path.join(__dirname, 'provenance.json'), 'utf8'));
const tokens = fs.existsSync(path.join(RES, 'tokens.json')) ? JSON.parse(fs.readFileSync(path.join(RES, 'tokens.json'), 'utf8')) : {};
const trace = fs.existsSync(path.join(RES, 'agent-trace.json')) ? JSON.parse(fs.readFileSync(path.join(RES, 'agent-trace.json'), 'utf8')) : {};

const pc = (x) => (x == null ? '—' : `${(x * 100).toFixed(0)}%`);
const cell = (fx, cfg) => { const p = path.join(RES, `${fx}__${cfg}.json`); return fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf8')) : null; };
const mean = (xs) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : null);

// best present embedding/rerank config per fixture by semantic s@5
function pickBest(fx) {
    let best = null;
    for (const cfg of ['E0', 'O0', 'O2', 'R0', 'R1', 'R2']) {
        const c = cell(fx, cfg); if (!c?.ok) continue;
        const rows = c.eval.rows.filter(r => r.difficulty === 'semantic');
        const s5 = mean(rows.map(r => r.strictSuccess[5]));
        if (s5 != null && (!best || s5 > best.s5)) best = { cfg, s5 };
    }
    return best?.cfg || null;
}

async function perArchetype(fx, cfg) {
    const c = cell(fx, cfg); if (!c?.ok) return null;
    let kindById = {};
    try { for (const q of (await import(`../test/suites/${fx}.mjs`)).QUERIES) kindById[q.id] = q.kind || (q.difficulty === 'semantic' ? 'nl' : 'kw'); } catch { return null; }
    const byKind = {};
    for (const r of c.eval.rows) {
        const k = kindById[r.id] || '?';
        (byKind[k] ||= []).push(r);
    }
    const out = {};
    for (const k of ['kw', 'nl', 'xc']) {
        const rs = byKind[k]; if (!rs?.length) continue;
        out[k] = { n: rs.length, r1: mean(rs.map(r => r.rank1Strict)), s5: mean(rs.map(r => r.strictSuccess[5])) };
    }
    return out;
}

const A = [];
A.push('# BENCH_AGENT.md — end-to-end / agent-facing results\n');
A.push('> Generated by `bench/synth-agent.mjs`. Section 1 is a deterministic retrieval proxy for every language; section 2 is the per-task token footprint; section 3 is the LLM agent-trace on a small subset (heavy — "not run" elsewhere). Archetypes: **kw**=keyword/symbol lookup, **nl**=behavioural natural language, **xc**=cross-cutting.\n');

A.push('## 1. Per-archetype retrieval proxy (strict rank-1 / s@5)\n');
A.push('Default path (L1) and the best-available embedding/rerank config, per language. "Task success" proxy = the right symbol is in top-5 (s@5); the harder bar (rank-1) = it is #1. **Each archetype cell is `r1% / s@5% (n)`** — `n` is the per-language query count for that archetype. These are **small sets (n=2–14)**; nl/xc (behavioural) n is typically 2–4, so a single query moves rank-1 by 25–50 points. Read them as directional; the symbolic (kw) channel has the larger n.\n');
A.push('> Archetypes here are `kind`-based (kw/nl/xc), which differs slightly from the `difficulty:"semantic"` subset used for the `sem` columns in BENCH_SUMMARY/LANGUAGES. **Structural gaps (which languages lack call-graph / type_refs) are the canonical, invocation-verified table in BENCH_LANGUAGES.md — not re-derived here.**\n');
A.push('| Language | fixture | config | kw r1/s@5 (n) | nl r1/s@5 (n) | xc r1/s@5 (n) |');
A.push('|---|---|---|---|---|---|');
for (const fx of FIX_ORDER) {
    const p = prov[fx]; if (!p) continue;
    for (const cfg of ['L1', pickBest(fx)].filter(Boolean).filter((v, i, a) => a.indexOf(v) === i)) {
        const pa = await perArchetype(fx, cfg); if (!pa) continue;
        const g = (k) => (pa[k] ? `${pc(pa[k].r1)}/${pc(pa[k].s5)} (n=${pa[k].n})` : '—');
        A.push(`| ${cfg === 'L1' ? p.language : ''} | ${cfg === 'L1' ? fx : ''} | ${cfg} | ${g('kw')} | ${g('nl')} | ${g('xc')} |`);
    }
}

A.push('\n## 2. Token footprint vs naive readFile (per task)\n');
if (Object.keys(tokens).length) {
    A.push('Top-5 `search_code` payload vs reading the full source files of those hits; and the honest amortized cost net of ONE `get_chunk` full-body expansion. Per task, not session-amortized.\n');
    A.push('| Language | fixture | top-5 vs full-file | amortized (net 1 get_chunk) |');
    A.push('|---|---|---|---|');
    for (const fx of FIX_ORDER) { const t = tokens[fx]; if (!t) continue; A.push(`| ${prov[fx]?.language} | ${fx} | ${t.avgSavingsPct}% | ${t.avgAmortizedSavingsPct}% |`); }
} else A.push('_not run yet — `node bench/tokens.mjs <fixture...>`_');

A.push('\n## 3. LLM agent-trace (real task success + tool calls)\n');
if (Object.keys(trace).length) {
    A.push('| fixture | tasks | success | avg tool calls | avg tokens/task | model |');
    A.push('|---|---|---|---|---|---|');
    for (const [fx, t] of Object.entries(trace)) A.push(`| ${fx} | ${t.tasks} | ${pc(t.successRate)} | ${t.avgToolCalls} | ${t.avgTokens} | ${t.model} |`);
    A.push(`\n_Run on a subset only; all other languages: not run — cost._`);
} else A.push('_not run yet — LLM agent-trace harness pending (subset only)._');

A.push('\n## Reproduce\n```bash\nnode bench/tokens.mjs <fixture...>\nnode bench/synth-agent.mjs\n```\n');

fs.writeFileSync(path.join(DOCS, 'BENCH_AGENT.md'), A.join('\n'));
console.log('wrote docs/benchmarks/BENCH_AGENT.md');
